### ISSUE TITLE
Error on code action when using telescope

### ISSUE THREAD

**Issue by kevinpita** [mfussenegger/nvim-jdtls#102]
I'm getting
```
Error executing vim.schedule lua callback: ...are/nvim/site/pack/packer/start/nvim-jdtls/lua/jdtls.lua:678: attempt to index local 'x' (a userdata value)
```
when openning code actions while using the telescope config that's available on the wiki

my config: https://gist.github.com/kevinpita/14c212cf7e5443a7af2350a1a86b917b

**Comment by mfussenegger** [comment]
I wasn't able to reproduce this.
In what context are you trying to retrieve the code actions that triggered the error?

**Comment by kevinpita** [comment]
after trying to reduce the plugin config, I found that the error may be on @cjgratacos sample config, as I have put the most basic I could use and it's working ok. At first what I did was copying their config and updating the telescope part while removing the formatter as I do not use that one

**Comment by mfussenegger** [comment]
So this can be closed?

**Comment by kevinpita** [comment]
> So this can be closed?

Yes, sorry for late reply.
