### ISSUE TITLE
E5108 when using jumplist

### ISSUE THREAD

**Issue by jaredculp** [mfussenegger/nvim-jdtls#103]
If I go to the definition of a file and then hit `<C-o>` to jump back, the following error message appears:

```
Error detected while processing BufLeave Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: E539: Illegal character <C>
```

Config:
```
# ~/.config/nvim/ftplugin/java.lua
require'jdtls'.start_or_attach{
  cmd = {'jdtls.sh'}
}
```

**Comment by mfussenegger** [comment]
Do you have any additional `BufLeave` auto commands setup?

You can get a list with: `:autocmd BufLeave *`

**Comment by jaredculp** [comment]
```
:autocmd BufLeave *
--- Autocommands ---
lualine  BufLeave
    *         lua vim.wo.statusline=require'lualine'.statusline()
FileExplorer  BufLeave
    *         if &ft != "netrw"|let w:netrw_prvfile= expand("%:p")|endif
```

**Comment by mfussenegger** [comment]
Does the error also happen if you disable the statusline `BufLeave` autocmd?

**Comment by jaredculp** [comment]
Looks like its an issue with the status line. I'll raise an issue over there. Thanks for the quick response and for a great plugin!
