### ISSUE TITLE
Cannot detect other subprojects in gradle

### ISSUE THREAD

**Issue by dodonut** [mfussenegger/nvim-jdtls#105]
Note: I do not know if this is a nvim-jdtls issue. Could be a config issue but I'm new on this kind stuff :)
dotfiles for reference: https://github.com/dodonut/dotfiles

I followed the installation process, setup the script with the jar and download the lsp from eclipse. On my work project (which I cant post the link here) it starts normal, but the reference to the other subprojects does not load, and I end up with a lot of definition errors. I've downloaded another gradle project to test (https://github.com/jghoman/gradle-subprojects), and this one shows the "Service Ready" like in my work project, but then shows up this message:
![Peek 2021-07-29 14-19](https://user-images.githubusercontent.com/19748045/127536630-079f906e-f9ff-4f1c-9913-23ce058389ee.gif)

and no errors or language features start up!

In the work project, it shows the jdtls features, but it does not recognizes the project where the definition sits. I cant see whats the difference between these two...

I was using the https://github.com/kabouzeid/nvim-lspinstall java feature, and worked out the box with my dotfiles, but it lacks some features like extraction and signature help....

**Comment by mfussenegger** [comment]
Did you try to follow the [Troubleshooting](https://github.com/mfussenegger/nvim-jdtls#troubleshooting) steps?

eclipse.jdt.ls can be a bit fragile and nitpicky when it comes to the project bootstrapping - for example there are issues like [this](https://github.com/eclipse/eclipse.jdt.ls/issues/1288)

Having a [separate data folder](https://github.com/mfussenegger/nvim-jdtls#data-directory-configuration) per project helps prevent some of the issues.

`:JdtCompile full` (or `:lua require('jdtls').compile('full')`) can give some more insights into project loading errors.

Otherwise sometimes wiping the `-data` folder helps.

**Comment by dodonut** [comment]
I followed the troubleshoot, and :JdtUpdateConfig stuck with message: 
![image](https://user-images.githubusercontent.com/19748045/127691465-b734d02b-2a45-4503-ada0-775324ca6700.png)
No errors on startup, i've setted the ft=java, and no messages under :messages. 
Wiped the data folder specified in my launch script every time, no success.
The compile full does not work because he can't find the the dependencies. 
I've tried to setup a root dir, but the project have multiple build.gradle, tried also put a file that only exists on the root, no success!
I've even builded eclipse from source, but again, no success :(

**Comment by mfussenegger** [comment]
> The compile full does not work because he can't find the the dependencies.

Can you elaborate on that? Do you get an error message?

**Comment by dodonut** [comment]
Yes, those error messages running compile full
![image](https://user-images.githubusercontent.com/19748045/127757728-cb87b186-6b4d-494b-9cec-a5551b314986.png)
those definitions are on other subprojects, which he probably did not find the references. 
The :messages command only give me this when running compile full
![image](https://user-images.githubusercontent.com/19748045/127757765-ec5f01c3-3911-4ed5-8276-462f83cfa552.png)

on startup, :messages give me nothing, so I do not know if an error occurred.

**Comment by mfussenegger** [comment]
Sounds like the root directory is not configured correctly and because of that some sub projects are not picked up.

You can call `:lua print(vim.inspect(vim.lsp.get_active_clients()))` to see the active language servers. It's a lot of text but somewhere in it you should find the `root_dir` property. It's value should be set to the project root.
If it isn't you need to [customize](https://github.com/mfussenegger/nvim-jdtls#root_dir-configuration) it.

**Comment by dodonut** [comment]
Sorry for the delay, did not see that u have commented after me :(

But the root is configured correctly, he just does not seem to find the other build.gradle subprojects. In Intellij, is called a module, with its own build.gradle, and in other project, we use the syntax like `implementation project(':project1')`, or a module with another module inside would be like `implementation project(':adapters:submodule')`. The other plugin that I mentioned, deals with it automatically. Don't know the reason for this one not work. The functionality in this plugin seems to be more effective and helpful. Sad that did not worked for me.

**Comment by mfussenegger** [comment]
That kind of setup should actually work. There are some limitation when it comes to trying to use testOutput configurations or something similar (See the [buildship](https://github.com/eclipse/buildship) issue tracker), but a regular multi module setup should work out of the box.

Just make sure the root_dir is set to the parent. E.g.

```
/path/to/project
/path/to/project/project1
/path/to/project/adapters/submodule
```


Here `/path/to/project` should be the `root_dir` with the `settings.gradle`, and the other folders should also contain a `build.gradle`.

**Comment by dodonut** [comment]
It is, and still did not worked. But thanks for the help anyway.

**Comment by DasilvaB** [comment]
I had a similar issue (in nvim) that I finally got working, my situation was like so:

I had a project, project A;
In settings.gradle: `project(":B").projectDir = file("....") `
then in build.gradle: `implementation project(":B")`

when I would launch project A but for some reason it wouldnt be able to find project B throwing import errors (but would work fine in intellij). Eventually I ran into this issue recommending deleting the .settings file: https://github.com/mfussenegger/nvim-jdtls/issues/38 but for me I ended up modifying it so it would delete all the files; .settings .project .classpath bin/. But I had to do this in BOTH projects, after removing those files from project B as well everything worked

**Comment by kishooore** [comment]
I am also facing a similar issue for a multi-module maven project. 

**Error message:** `[className].java is a non-project file, only syntax errors are reported.
`
Tried Solutions: 
- deleted the .workspace folder of the project
- deleted .settings and .project folders in all submodules.

Both of the above solutions are not working for me, please help if I am missing any configuration.

**Comment by TimothyGCY** [comment]
> That kind of setup should actually work. There are some limitation when it comes to trying to use testOutput configurations or something similar (See the [buildship](https://github.com/eclipse/buildship) issue tracker), but a regular multi module setup should work out of the box.
> 
> Just make sure the root_dir is set to the parent. E.g.
> 
> ```
> /path/to/project
> /path/to/project/project1
> /path/to/project/adapters/submodule
> ```
> 
> Here `/path/to/project` should be the `root_dir` with the `settings.gradle`, and the other folders should also contain a `build.gradle`.

this works for me as a temporary solution by changing the root_dir
```lua
-- local root_dir = require('jdtls.setup').find_root(root_markers)
local root_dir = "/home/user/path/to/project/root"
```

but will require to figure out some other solution if i have more than one project.
