### ISSUE TITLE
Decompiler for debugging

### ISSUE THREAD

**Issue by EpsilonKu** [mfussenegger/nvim-jdtls#111]
### Problem Statement

What about auto-decompile class when show frames on debugging?

**Comment by mfussenegger** [comment]
You can use [fernflower](https://github.com/dgileadi/vscode-java-decompiler) - the repository contains a eclipse.jdt.ls extension which you can build and have to add to the bundles jar:

The built jar files are checked into the repo: https://github.com/dgileadi/vscode-java-decompiler/tree/master/server

You've to add them to the `init_options = { bundles = {...} }` property of your config and also set `settings = { java = { contentProvider = { preferred = 'fernflower' ... `. See https://github.com/mfussenegger/nvim-jdtls/issues/8

This is how I integrated it: https://github.com/mfussenegger/dotfiles/commit/06e1a64d80a80b7763f04ad3d28bd3b6071b034c

**Comment by EpsilonKu** [comment]
Alright, it works on `telescope-dap.nvim` but without preview.
