### ISSUE TITLE
Docker image with all bits installed

### ISSUE THREAD

**Issue by VVKot** [mfussenegger/nvim-jdtls#116]
### Problem Statement

Settings things up, especially in Java, is a pain in the back. I know that people have mixed feelings about Docker - but for better or worth it is the least common denominator in 2021. Projects like https://github.com/lspcontainers/lspcontainers.nvim allow me to not care as much about setting up hosts and taking OSes into account.

### Ideas or possible solutions

Publish a docker image with LSP server and debug tools installed.

**Comment by VVKot** [comment]
@mfussenegger thoughts? 🙏

**Comment by mfussenegger** [comment]
If somebody wants to create a Docker image and maintain it, I'm happy to add a link to it in the readme, but you won't see any work from my side into that direction.

If somebody does that, one suggestion: Try to avoid tying it to neovim LSP or nvim-jdtls. Ideally a distribution of a language server would work with any client.
