### ISSUE TITLE
How to integrate with nvim-lspconfig, completion.vim, and diagnostic.vim

### ISSUE THREAD

**Issue by ludwj61** [mfussenegger/nvim-jdtls#13]
I understand this was discussed in a previous issue but after reading through it I am still a bit confused on how to set this up with my lua config file. I already have the jdtls correctly installed.

Essentially, this is what I have in my lua file right now for use with lspconfig's jdtls settings:
```lua
local custom_attach = function(client)
    print("LSP started.")

    require"completion".on_attach(client)
    require"diagnostic".on_attach(client)

    -- Action
    map("n", "gD", "<cmd>lua vim.lsp.buf.declaration()<CR>")
    map("n", "gd", "<cmd>lua vim.lsp.buf.definition()<CR>")
    map("n", "K", "<cmd>lua vim.lsp.buf.hover()<CR>")
    map("n", "gr", "<cmd>lua vim.lsp.buf.references()<CR>")
    map("n", "gs", "<cmd>lua vim.lsp.buf.signature_help()<CR>")
    map("n", "gi", "<cmd>lua vim.lsp.buf.implementation()<CR>")
    map("n", "gt", "<cmd>lua vim.lsp.buf.type_definition()<CR>")
    map("n", "<leader>go", "<cmd>lua vim.lsp.buf.document_symbol()<CR>")
    map("n", "<leader>gw", "<cmd>lua vim.lsp.buf.workspace_symbol()<CR>")

    -- Goto
    map("n", "<leader>ah", "<cmd>lua vim.lsp.buf.hover()<CR>")
    map("n", "<leader>ac", "<cmd>lua vim.lsp.buf.code_action()<CR>")
    map("n", "<leader>dd", "<cmd>lua vim.lsp.util.show_line_diagnostics()<CR>")
    map("n", "<leader>ar", "<cmd>lua vim.lsp.buf.rename()<CR>")
    map("n", "<leader>=", "<cmd>lua vim.lsp.buf.formatting()<CR>")
    map("n", "<leader>ai", "<cmd>lua vim.lsp.buf.incoming_calls()<CR>")
    map("n", "<leader>ao", "<cmd>lua vim.lsp.buf.outgoing_calls()<CR>")

    -- Diagnostic
    map("n", "<leader>ep", "<cmd>PrevDiagnosticCycle<CR>")
    map("n", "<leader>en", "<cmd>NextDiagnosticCycle<CR>")
end

require"nvim.lsp".jdtls.setup{ on_attach = custom_attach }

```

What do I put instead of the last line to make this work?

**Comment by mfussenegger** [comment]
> What do I put instead of the last line to make this work?

See the [configuration](https://github.com/mfussenegger/nvim-jdtls#configuration) part in the readme.


You can call `require('jdtls').start_or_attach({ on_attach = custom_attach; cmd = {'path/to/your/jdtls_launch_script'} })` on a `FileType java` event.


```
au FileType java lua require('jdtls').start_or_attach(config)
```

**Comment by ludwj61** [comment]
Thanks for the help, I didn't understand that I was able to just stick in my custom_attach.

I have this right now in a separate .vim file
```vimscript
lua jdtls = require('jdtls')
lua config = {on_attach = custom_attach; cmd = {'launch_jdtls.sh'}}
augroup lsp
    au!
    au FileType java lua jdtls.start_or_attach(config)
augroup end

```
The server is loaded fine but my completion and diagnostics config are not being loaded (as if my custom attach is not found). I have tried putting all of the commands (my custom_attach and the above code) in the same file but I get the same result. Is there any obvious reason for this?

Thanks again for your help!

**Comment by mfussenegger** [comment]
> The server is loaded fine but my completion and diagnostics config are not being loaded (as if my custom attach is not found)

Probably because `custom_attach` is not in scope. You'd also need some `require` call and it would need to be exposed.

In your lua file you'd need to add a return:


```lua

local custom_attach = function(client)
  -- code as you have it
end

return {
  custom_attach = custom_attach;
}
```

And then you'd need to add a require call in front of the custom attach in the `.vim` file:


```
lua jdtls = require('jdtls')
lua config = {on_attach = require('yourluafilename').custom_attach; cmd = {'launch_jdtls.sh'}}
augroup lsp
    au!
    au FileType java lua jdtls.start_or_attach(config)
augroup end
```

**Comment by ludwj61** [comment]
Ah, yep, you're right. It now sees my config. 

Your help is very much appreciated, I'll close this now.

**Comment by ludwj61** [comment]
Oh and sorry one more thing, is it possible to change the root pattern? I think right now it is looking for a .git, is adding a pom.xml possible instead/in addition?

**Comment by mfussenegger** [comment]
> Oh and sorry one more thing, is it possible to change the root pattern? I think right now it is looking for a .git, is adding a pom.xml possible instead/in addition?

You can set the `root_dir` in the `config`. If you've the lspconfig available, you can use its `root_pattern` function. The one in `jdtls` is currently not exposed. Though I guess I could change that.


```
lua config = { root_dir = require('nvim_lsp.util').root_pattern('.git'), -- ... remaining options
```

(Not sure about the require, maybe it is `require('nvim_lsp').util.root_pattern(...)`)

**Comment by ludwj61** [comment]
Thanks it was ``require('nvim_lsp').util.root_pattern(...)`` e.g. ``require('nvim_lsp').util.root_pattern('pom.xml')``
