### ISSUE TITLE
jdtls starts in every directory

### ISSUE THREAD

**Issue by axelcalixte** [mfussenegger/nvim-jdtls#130]
### LSP client configuration

```lua 
require('jdtls').start_or_attach({
    cmd = {'jdtls.sh', '/home/axel/.config/jdtls-workspace' .. vim.fn.fnamemodify(vim.fn.getcwd(), ':p:h:t')}, root_dir = require('jdtls.setup').find_root({'gradle.build', 'pom.xml'})
})
```

### Eclipse.jdt.ls version

git master

### Steps to Reproduce

I think that by combining the two commands you gave in the README for root-dir and data directory configurations, we can reproduce the behaviour of the language server starting in every directory regardless of the root-dir having a gradle.build or pom.xml file.

### Expected Result

I'd like the language server to start only in directories where there is a gradle.build or pom.xml file.

### Actual Result

Compile successfull for the ` :lua require('jdtls').compile('full')` command.
Didn't manage to get some useful logs :/

**Comment by mfussenegger** [comment]
You'll have to wrap `start_or_attach` in a custom function that checks if there is a `gradle.build` or `pom.xml`. It is expected behavior that it always starts a client or attaches to a running client.

**Comment by EpsilonKu** [comment]
If it's annoying you can attach on special files. 
`
vim.cmd(([[
	autocmd FileType java lua require('jdtls').start_or_attach({
    cmd = {'jdtls.sh', '/home/axel/.config/jdtls-workspace' .. vim.fn.fnamemodify(vim.fn.getcwd(), ':p:h:t')}, root_dir = require('jdtls.setup').find_root({'gradle.build', 'pom.xml'})
})
]]))
`
