### ISSUE TITLE
start_or_attach() not working propperly on Windows

### ISSUE THREAD

**Issue by TheLeoP** [mfussenegger/nvim-jdtls#131]
### LSP client configuration

```
local root_dir = require('jdtls.setup').find_root({'build.gradle', 'pom.xml'})
local java_cmd = "prueba.bat"
local eclipse_wd = home .. 'java-workspace/' .. vim.fn.fnamemodify(root_dir, ':h:t') .. '/' .. vim.fn.fnamemodify(root_dir, ':t')

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
capabilities.textDocument.completion.completionItem.resolveSupport = {
  properties = {
    'documentation',
    'detail',
    'additionalTextEdits',
  }
}

local on_attach_general = function(client, bufnr)
  require('illuminate').on_attach(client)
  require('lsp_signature').on_attach({
      bind = true,
      doc_lines = 0,
      floating_windows = true,
      fix_pos = true,
      hint_enable = false,
      use_lspsaga = false,
      handler_opts = {
        border = lsp_borders
      }
    })
end

local on_attach_java = function(client, bufnr)
  on_attach_general(client, bufnr)
  require('jdtls').setup_dap({ hotcodereplace = 'auto' })
  require('jdtls.dap').setup_dap_main_class_configs()
  require('jdtls.setup').add_commands()
end

local config = {
  flags = {
    allow_incremental_sync = true,
  },
  capabilities = capabilities,
  on_attach = on_attach_java,
  on_init = function(client, _)
    client.notify('workspace/didChangeConfiguration', {
        settings = client.config.settings;
      })
  end,
  cmd = {
    java_cmd,
    eclipse_wd
  },
  root_dir = root_dir,
  init_options = {
    bundles = {
      vim.fn.glob(home .. ".dap-gadgets/java-debug-0.32.0/com.microsoft.java.debug.plugin/target/com.microsoft.java.debug.plugin-0.32.0.jar")
    }
  }
}
```

### Steps to Reproduce

1. Open Neovim and edit a file on a project using "/" in the path. Example: use the command `:e root/to/my/project/main.java`
2. Edit **a different file in the same project** using "\\" in the path. Example: use the command `:e root\to\my\project\foo.java`

Notes:
- the same happens if I first open a file using "\\" for it's path and then a different file on the same project using "/".
- If I continue to open files they will attach to the instance of jdtls with the root that matches exactly (if I open a file with "/" it will attach to the server opened with "/" and viceversa).

### Expected Result

Just one jdls instance will be initialized since both files are from the same project.

### Actual Result

Each file initializes one jdtls instance.

**Comment by mfussenegger** [comment]
Could you post the result of `:lua print(require('jdtls.setup').find_root({'build.gradle', 'pom.xml'}))` in both cases?

**Comment by TheLeoP** [comment]
Here are both screenshots:

![backslash](https://user-images.githubusercontent.com/53507599/132551200-a56be40f-5b6a-4ca5-8e2e-dab7df4219e8.png)
![slash](https://user-images.githubusercontent.com/53507599/132551201-f587c237-53de-4aa1-a5ac-a9438a0ac520.png)

**Comment by mfussenegger** [comment]
The paths look kinda alright.


Given that I don't use windows I'd need somebody else to help out with debugging/fixing this. I suspect that either the find_root method is fishy:

https://github.com/mfussenegger/nvim-jdtls/blob/afe619ec05866a3c2ff6f7af4c4b5b4f1d9fb7c6/lua/jdtls/setup.lua#L93-L106

or there is something strange going on here:

https://github.com/mfussenegger/nvim-jdtls/blob/afe619ec05866a3c2ff6f7af4c4b5b4f1d9fb7c6/lua/jdtls/setup.lua#L20-L33

**Comment by TheLeoP** [comment]
I could try to debug this.

Also, I think [this issue on lspconfig](https://github.com/neovim/nvim-lspconfig/issues/1266) may be relevant. I'm not 100% sure, though

**Comment by TheLeoP** [comment]
![client_id_by_root_dir](https://user-images.githubusercontent.com/53507599/134589142-6701d4a9-0418-46c2-aa16-b72259c636fe.png)

So, nvim-jdtls is starting two separated instances because it creates a different entry on `client_id_by_root_dir` because the root paths are different. That happens because Neovim gives a buffer a different name depending of how it was oppened (`/` vs `\`)

My idea of a fix would be to normalice the path returned by `find_root()` by replacing with a regex all the `\` with `/`). What do you think?

**Comment by mfussenegger** [comment]
Looks like calling `vim.loop.fs_realpath` on the result of `find_root` may be an option. See https://github.com/luvit/luv/blob/727c6e45f7f6414a95cf7e63443d7aa42a4c9481/docs.md#uvfs_realpathpath-callback

**Comment by mfussenegger** [comment]
Could you try with https://github.com/mfussenegger/nvim-jdtls/pull/145 ?

**Comment by TheLeoP** [comment]
It solves the problem, thanks :3
