### ISSUE TITLE
Lsp Action not working on Unknown Symbol

### ISSUE THREAD

**Issue by MasterGordon** [mfussenegger/nvim-jdtls#146]
### LSP client configuration

buf_set_keymap("n", "<leader>a", "<Cmd>lua require('jdtls').code_action()<CR>", opts)

### Eclipse.jdt.ls version

latest

### Steps to Reproduce

Open a file and hover a unknown type and hitting <leader>a in normal mode.
![image](https://user-images.githubusercontent.com/18127395/134746189-649af98b-de01-4506-9199-f5fc5c188fb6.png)

### Expected Result

Completion to show up.
And getting an Import suggested

### Actual Result

Error executing vim.schedule lua callback: ...are/nvim/site/pack/packer/start/nvim-jdtls/lua/jdtls.lua:686: attempt to index local 'x
' (a userdata value)
Press ENTER or type command to continue

**Comment by MasterGordon** [comment]
The same issue appears when hovering the `out` of `System.out.print(...)`

**Comment by mfussenegger** [comment]
1. Which neovim version are you using?

2. Do you have some customization for `require('jdtls.ui').pick_one_async` ?



I can't reproduce the problem.

**Comment by MasterGordon** [comment]
I am using `NVIM v0.6.0-dev+340-g7cb34a341`
And I got no customization for `require('jdtls.ui').pick_one_async`
Here is a minimal reproduction on the java-lsp branch:
https://github.com/MasterGordon/neovim-config/tree/java-lsp

**Comment by baobaoit** [comment]
> I am using `NVIM v0.6.0-dev+340-g7cb34a341`
> And I got no customization for `require('jdtls.ui').pick_one_async`
> Here is a minimal reproduction on the java-lsp branch:
> https://github.com/MasterGordon/neovim-config/tree/java-lsp

The `code_action` is mapped with the combined <kbd>\<Leader\>a</kbd>.
![image](https://user-images.githubusercontent.com/31947091/135009937-88aee865-9e13-48b3-95c4-d65ed994f989.png)

By default, the `<Leader>` = the key <kbd>\\</kbd>.
So you need to press <kbd>\\a</kbd>.

**Comment by mfussenegger** [comment]
Is this still an issue with the latest nvim-jdtls & latest neovim nightly or 0.5.1?

**Comment by sashomasho** [comment]
I had this problem, but then found #102 and the suggestion there worked for me..
