### ISSUE TITLE
Error on jar

### ISSUE THREAD

**Issue by EpsilonKu** [mfussenegger/nvim-jdtls#152]
### LSP client configuration

    local config = {}
    local home = os.getenv("HOME")
    local workspace_folder = home .. "/.workspace/" .. vim.fn.fnamemodify(root_dir, ":p:h:t")
    local bundles = {
        vim.fn.glob(home .. "/.local/bin/java-debug/com.microsoft.java.debug.plugin/target/com.microsoft.java.debug.plugin-*.jar"),
		vim.fn.glob(home .. "/.local/bin/vscode-java-decompiler/server/*.jar")
    }

    config.cmd = {
 		'/usr/lib/jvm/java-11-openjdk/bin/java',
 		'-Declipse.application=org.eclipse.jdt.ls.core.id1',
    	'-Dosgi.bundles.defaultStartLevel=4',
		'-Declipse.product=org.eclipse.jdt.ls.core.product',
  		'-Dlog.protocol=true',
		'-Dlog.level=ALL',
		'-Xmx1G',
  		'-Xmx2G',
		'-jar ' .. vim.fn.glob(home .. "/.local/bin/plugins/org.eclipse.equinox.launcher_*.jar"),
		'-configuration ' .. home .. '/.local/bin/config_linux',
		'-data ' .. workspace_folder,
		'--add-modules=ALL-SYSTEM',
		'--add-opens java.base/java.util=ALL-UNNAMED',
		'--add-opens java.base/java.lang=ALL-UNNAMED'
	}
    config.root_dir = require('jdtls.setup').find_root({'.git', 'mvnw', 'gradlew'})

### Steps to Reproduce

I tried to configure without .sh file. So [eclipse config](https://github.com/eclipse/eclipse.jdt.ls#installation) config ` -jar /path/to/equinox `. Old config configure `-jar $(echo "$JAR")`, but Idk how to do it. Maybe error on `\n`. 

### Expected Result

No error

### Actual Result

[START][2021-09-27 17:13:51] LSP logging initiated
[ERROR][2021-09-27 17:13:52] .../vim/lsp/rpc.lua:462	"rpc"	"/usr/lib/jvm/java-11-openjdk/bin/java"	"stderr"	"Unrecognized option: -jar /home/epsku/.local/bin/plugins/org.eclipse.equinox.launcher_1.6.400.v20210908-1257.jar\nError: Could not create the Java Virtual Machine.\nError: A fatal exception has occurred. Program will exit.\n"

**Comment by mfussenegger** [comment]
What you're doing is like running `java "-jar /path/to/jar"` in the command-line. What you need is `java -jar "/path/tojar"`. You're setting `-jar /path/to/jar` as a single argument, instead of `-jar` and the path being separated.

You'd have to use:

```
'-jar ', vim.fn.glob(home .. "/.local/bin/plugins/org.eclipse.equinox.launcher_*.jar"),
```

Same for `-configuration` and `-data`.

**Comment by EpsilonKu** [comment]
`[ERROR][2021-09-27 19:46:33] .../vim/lsp/rpc.lua:462	"rpc"	"/usr/lib/jvm/java-11-openjdk/bin/java"	"stderr"	"Unrecognized option: -jar \nError: Could not create the Java Virtual Machine.\nError: A fatal exception has occurred. Program will exit.\n"` Doesn't help.

**Comment by mfussenegger** [comment]
Without whitespace in `-jar`, sorry about that.

**Comment by EpsilonKu** [comment]
Huh, now it works. Thanks, enjoy ur coffee.
