### ISSUE TITLE
[Feature request] Add a `codeAction` to generate the serialVersionUID field

### ISSUE THREAD

**Issue by baobaoit** [mfussenegger/nvim-jdtls#153]
### Problem Statement

Which class `implements` the `Serializable`, we need to put a field: `private static final long serialVersionUID = X;`.
Where `X` is a number type `long` be generated by the tool `serialver` of Java.

### Ideas or possible solutions

Reference: [Java – How to generate serialVersionUID](https://mkyong.com/java/how-to-generate-serialversionuid/)

**Comment by mfussenegger** [comment]
This would need to be added to https://github.com/eclipse/eclipse.jdt.ls first. Could you create an issue there?

**Comment by baobaoit** [comment]
I had raised the issue https://github.com/eclipse/eclipse.jdt.ls/issues/1892.
Thank you for replied and your work really awesome.

**Comment by baobaoit** [comment]
Hi @mfussenegger, I had followed the instruction at https://github.com/eclipse/eclipse.jdt.ls/issues/1892#issuecomment-929715918 and it worked.

![image](https://user-images.githubusercontent.com/31947091/135190586-740a2350-20c2-471a-aad8-3260efa6001c.png)

But I have a question that can we handle this with this plugin because I don't want to add that line every time to every project. Would you like to add this line to the global setting?

Thank you.

**Comment by baobaoit** [comment]
Resolved in this comment ➡️ https://github.com/eclipse/eclipse.jdt.ls/issues/1892#issuecomment-931820712

**Comment by abenz1267** [comment]
This seemed to work for me, however: the code-action doesn't seem to work, when the class extends another class implementing Serializable. The warning will show up, same as the code action, but nothing will be generated.

**Comment by mfussenegger** [comment]
> This seemed to work for me, however: the code-action doesn't seem to work, when the class extends another class implementing Serializable. The warning will show up, same as the code action, but nothing will be generated.

If it works for a simpler case it is likely a eclipse.jdt.ls bug and you'd need to open an issue there in order for it to get fixed.
