### ISSUE TITLE
Client quits with exit code 13

### ISSUE THREAD

**Issue by iam-arnab** [mfussenegger/nvim-jdtls#154]
### LSP client configuration

```java
local workspace_dir = vim.fn.fnamemodify(vim.fn.getcwd(), ':p:h:t')
local config = {}
config.cmd = {
    "/usr/lib/jvm/java-11-openjdk-amd64/bin/java",
    "-Declipse.application=org.eclipse.jdt.ls.core.id1 ",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=ALL",
    "-Xms1G",
    "-Xmx2G",
    "-jar", "/home/arnab/Builds/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_*.jar",
    "-configuration", "/home/arnab/Builds/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/config_linux",
    "-data", "/home/arnab/.local/share/eclipse/workspace/" .. workspace_dir,
    "--add-modules=ALL_SYSTEM",
    "--add-opens java.base/java.util=ALL-UNNAMED",
    "--add-opens java.base/java.lang=ALL-UNNAMED"
  }
config.init_options = {
     bundles = {
       vim.fn.glob("/home/arnab/Builds/java-debug/com.microsoft.java.debug.plugin/target/com.microsoft.java.debug.plugin-*.jar")
     }
   }

config.on_attach = function(client, bufnr)
     require('jdtls').setup_dap({ hotcodereplace = 'auto' })
     require('jdtls').add_commands()
   end

```

### Eclipse.jdt.ls version

_1.5.0_

### Steps to Reproduce

Open a java file

### Expected Result

Client should start

### Actual Result

`Client 1 quit with exit code 13 and signal 0`

**Comment by iam-arnab** [comment]
After rebuilding eclipse jdtls from scratch (deleting the complete folder), I can't seem to get exit code 13. Closing this.

**Comment by iam-arnab** [comment]
I am getting the same error again. 
This is from lsp log
`[WARN][2021-10-06 08:56:34] .../lua/vim/lsp.lua:87	"method textDocument/codeAction is not supported by any of the servers registered for the current buffer"`

**Comment by mfussenegger** [comment]
Eclipse.jdt.ls exiting with code 13 may be caused by having a mix of 32/64-bit JVM/eclipse.jds.ls version.

Did you build eclipse with the same java version?

The `textDocument/codeAction` related log entry is unrelated.

**Comment by mfussenegger** [comment]
Why change it if it worked before?
There is no significant disadvantage or advantage to either using an intermediate `java-lsp.sh` script or declaring the eclipse.jdt.ls java cmd directly.

You could also try wiping the workspace folder. I've had issues in the past after eclipse.jdt.ls version updates

**Comment by iam-arnab** [comment]
Yeah sorry, I didn't realise it before. I was having a different problem after I updated and saw the README had different instructions so I thought that might be it. It did fix that though. Thanks for all the help!

**Comment by ZN0N15** [comment]
@iam-arnab Thanks! Apparently the directory where I put my jdtls is a couple folders too deep(?) (my initial directory was in `~/.cache/nvim/nvim-lsp/jdtls`) but when I moved those files and changed my script to the same directory with the [script](https://github.com/iam-arnab/dotfiles/blob/master/neovim/.config/nvim/jdtls_launch) you linked, which is in `~/.local/share/jdtls/` it now works.

**Comment by iam-arnab** [comment]
@ZN0N15 Glad it worked!
