### ISSUE TITLE
Detect --enable-preview commit 9719577 results in invalid launch args resulting in ClassNotFoundException false

### ISSUE THREAD

**Issue by dangerousdaren** [mfussenegger/nvim-jdtls#166]
### LSP client configuration

local config = {
  -- The command that starts the language server
  cmd = {
    '/usr/bin/java',
    '-Dosgi.bundles.defaultStartLevel=4',
    '-Declipse.application=org.eclipse.jdt.ls.core.id1',
    '-Declipse.product=org.eclipse.jdt.ls.core.product',
    '-Dlog.level=ALL',
    '-noverify',
    '-Xmx1G',
    '-jar',
    '/home/centos/jdtls/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar',
    '-configuration',
    '/home/centos/jdtls/jdtls/config_linux',
    '-data',
    '/home/centos/workspace/',
  },

  -- This is the default if not provided, you can remove it. Or adjust as needed.
  -- One dedicated LSP server & client will be started per unique root_dir
  root_dir = require('jdtls.setup').find_root({'.git', 'mvnw', 'gradlew'})
}

-- This bundles definition is the same as in the previous section (java-debug installation)
local bundles = {
  vim.fn.glob("/home/centos/jdtls/java-debug/com.microsoft.java.debug.plugin/target/com.microsoft.java.debug.plugin-*.jar"),
};

-- This is the new part
vim.list_extend(bundles, vim.split(vim.fn.glob("/home/centos/jdtls/vscode-java-test/server/*.jar"), "\n"))
config['init_options'] = {
  bundles = bundles;
}

config['on_attach'] = function(client, bufnr)
  -- With `hotcodereplace = 'auto' the debug adapter will try to apply code changes
  -- you make during a debug session immediately.
  -- Remove the option if you do not want that.
  require('jdtls').setup_dap({ hotcodereplace = 'auto' })
  require('jdtls.setup').add_commands()
end

require('jdtls').start_or_attach(config)

### Eclipse.jdt.ls version

9719577c7b7dce5c2d91489ac159794ea2b41d68

### Steps to Reproduce

Open a Java fale with main from a simple gradle project i.e. ( aditya-sridhar/simple-gradle-java-app )

Execute command :JdtRefreshDebugConfigs

Execute the java configuration :lua require'dap'.continue()

### Expected Result

The simple java projects main is executed 

### Actual Result

Output has this 

Error: Could not find or load main class false
Caused by: java.lang.ClassNotFoundException: false

[Process exited 1]

**Comment by dangerousdaren** [comment]
Using Trace output I noted the following 

[ DEBUG ] 2021-11-02T11:00:38Z+0000 ] ...rvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:536 ] {
  arguments = {
    args = { "/jdk/jdk-11.0.11+9/bin/java", "-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:34134", "false", "-Dfile.encoding=UTF-8", "-cp",....

Note the "false". that appears after the agentlib arg.  This I believe is comming from the jvmArgs config option that is being set to false and is being used as the Mainclass for the jvm to execute.

{
  java = { {
      classPaths = { "/home/centos/workspace/simple-gradle-java-app/bin/main", "/home/centos/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/28.1-jre/b0e91dcb6a44ffb6221b5027e12a5cb34b841145/guava-28.1-jre.jar", "/home/centos/.gradle/caches/modules-2/files-2.1/com.google.guava/failureaccess/1.0.1/1dcf1de382a0bf95a3d8b0849546c88bac1292c9/failureaccess-1.0.1.jar", "/home/centos/.gradle/caches/modules-2/files-2.1/com.google.guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/b421526c5f297295adef1c886e5246c39d4ac629/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar", "/home/centos/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/3.0.2/25ea2e8b0c338a877313bd4672d3fe056ea78f0d/jsr305-3.0.2.jar", "/home/centos/.gradle/caches/modules-2/files-2.1/org.checkerframework/checker-qual/2.8.1/eb2e8ab75598548cc8acf9a1ca227e480e01881e/checker-qual-2.8.1.jar", "/home/centos/.gradle/caches/modules-2/files-2.1/com.google.errorprone/error_prone_annotations/2.3.2/d1a0c5032570e0f64be6b4d9c90cdeb103129029/error_prone_annotations-2.3.2.jar", "/home/centos/.gradle/caches/modules-2/files-2.1/com.google.j2objc/j2objc-annotations/1.3/ba035118bc8bac37d7eff77700720999acd9986d/j2objc-annotations-1.3.jar", "/home/centos/.gradle/caches/modules-2/files-2.1/org.codehaus.mojo/animal-sniffer-annotations/1.18/f7aa683ea79dc6681ee9fb95756c999acbb62f5d/animal-sniffer-annotations-1.18.jar" },
      console = "integratedTerminal",
      javaExec = "/jdk/jdk-11.0.11+9/bin/java",
      mainClass = "simple.gradle.java.app.App",
      modulePaths = {},
      name = "Launch simple.gradle.java.app.App",
      projectName = "simple-gradle-java-app",
      request = "launch",
      type = "java",
      vmArgs = false
    } }
}
 

Running with nvim-jdtls @ 188d68ad9a9641378c6cb83594f10eedfee9eba6 works as expected

**Comment by mfussenegger** [comment]
Can you try with https://github.com/mfussenegger/nvim-jdtls/pull/167 ?

**Comment by dangerousdaren** [comment]
> Can you try with #167 ?

Works perfecly, thank you Mathias.

I'm now so close to being able to use neovim as a daily driver for Java development.

Thank you for all your hard work,  these nvim plugins are really something
