### ISSUE TITLE
Starts Everytime i open a file

### ISSUE THREAD

**Issue by Sakaar19** [mfussenegger/nvim-jdtls#181]
### LSP client configuration

like in docs

### Eclipse.jdt.ls version

1.2.3

### Steps to Reproduce

Simply install

### Expected Result

Start the server in java file only

### Actual Result

Starts the server in every file which i open

**Comment by EpsilonKu** [comment]
Put config on /ftplugin/java.lua.

**Comment by mfussenegger** [comment]
Works as expected. Can't help without more information.

**Comment by Sakaar19** [comment]
Thanks
