### ISSUE TITLE
Diagnostics: <File>.java is a non-project file, only syntax errors are reported

### ISSUE THREAD

**Issue by TornaxO7** [mfussenegger/nvim-jdtls#189]
### LSP client configuration

<details>

```lua
-- See `:help vim.lsp.start_client` for an overview of the supported `config` options.
local config = {
  -- The command that starts the language server
  -- See: https://github.com/eclipse/eclipse.jdt.ls#running-from-the-command-line
  cmd = {

    -- 💀
    'java', -- or '/path/to/java11_or_newer/bin/java'
            -- depends on if `java` is in your $PATH env variable and if it points to the right version.

    '-Declipse.application=org.eclipse.jdt.ls.core.id1',
    '-Dosgi.bundles.defaultStartLevel=4',
    '-Declipse.product=org.eclipse.jdt.ls.core.product',
    '-Dlog.protocol=true',
    '-Dlog.level=ALL',
    '-Xms1g',
    '--add-modules=ALL-SYSTEM',
    '--add-opens', 'java.base/java.util=ALL-UNNAMED',
    '--add-opens', 'java.base/java.lang=ALL-UNNAMED',

    '-jar', '/home/tornax/Apps/jdt-language-server-1.6.0-202111261512/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar',
    '-configuration', '/home/tornax/Apps/jdt-language-server-1.6.0-202111261512/config_linux',
                    -- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        ^^^^^^
                    -- Must point to the                      Change to one of `linux`, `win` or `mac`
                    -- eclipse.jdt.ls installation            Depending on your system.


    -- 💀
    -- See `data directory configuration` section in the README
    '-data', vim.fn.getcwd(),
  },

  -- 💀
  -- This is the default if not provided, you can remove it. Or adjust as needed.
  -- One dedicated LSP server & client will be started per unique root_dir
  root_dir = require('jdtls.setup').find_root({'.git', 'mvnw', 'gradlew'}),

  -- Here you can configure eclipse.jdt.ls specific settings
  -- See https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request
  -- for a list of options
  settings = {
    java = {
    }
  }
}
-- This starts a new client & server,
-- or attaches to an existing client & server depending on the `root_dir`.
require('jdtls').start_or_attach(config)
```

</details>

### Eclipse.jdt.ls version

1.6.0

### Steps to Reproduce

Copy + paste my settings and start open a file in the root of your project. The `.metadata` and the `jdt.ls-java-project` should be generated in your root project. Now open any java file and wait for the LSP.
The message `<File>.java is a non-project file, only syntax errors are reported` should pop up at the top of the file:

![image](https://user-images.githubusercontent.com/50843046/144691236-0ae4d10b-2fae-4f34-801a-1b0b4146c416.png)

### Expected Result

Everything should work fine.

### Actual Result

I'm getting the "error" message above.

**Comment by mfussenegger** [comment]
I think `'-data', vim.fn.getcwd(),` is the problem - afaik the data directory and the project directory cannot be the same.

**Comment by TornaxO7** [comment]
I'm using [`vim-rooter`](https://github.com/airblade/vim-rooter) so `getcwd()` is always pointing to my project directory.

**Comment by mfussenegger** [comment]
> data directory and the project directory cannot be the same.

Did you read my reply? 

> the data directory and the project directory **cannot** be the same.

**Comment by TornaxO7** [comment]
Yes I did, but I think that I missunderstand your reply. I thought you meant it like that: "The data directory and the project cannot be the same, since you could be in a subdirectory, so `getcwd()` doesn't point to the root directory anymore.".

Sorry, I'll try it again :sweat_smile:

**Comment by TornaxO7** [comment]
Hm... ok, so I've put the absolute path to my project directory:

```lua
   ...
    '-data', '/absolute/path/TaskB',
    ...
```

This is the output, if I do `cd /aboslute/path/TaskB` (just an example path) and then `tree -L 2 .`:
```
╰─  tree -L 2 .                                                                                                                                                                           ─╯
.
├── bin
│   ├── Application
│   ├── Organization
│   ├── Persons
│   ├── README.md
│   └── utils
├── jdt.ls-java-project
│   ├── bin
│   └── src
├── README.md
└── src
    ├── Application
    ├── Organization
    ├── Persons
    ├── README.md
    └── utils
```

**Comment by mfussenegger** [comment]
You also need to use either maven or gradle for it to understand your project layout and to recognize dependencies.

**Comment by TornaxO7** [comment]
Ooof.... ok, thank you for the information.
