### ISSUE TITLE
Java 14 support

### ISSUE THREAD

**Issue by Matsuuu** [mfussenegger/nvim-jdtls#19]
Hi, 

Thanks for you work on the nvim plugin.

I've wanted to try out the java 14 features, and have set it up from pom.xml with 

```xml
<maven.compiler.target>14</maven.compiler.target>
<maven.compiler.source>14</maven.compiler.source>
```

However when I open up a project file after setting these, they looks like this: 
![image](https://user-images.githubusercontent.com/16068444/100782809-a0b36100-3415-11eb-8010-7133f3636e9d.png)

Is there something I need to do to enable java 14 support or what's going on?

**Comment by mfussenegger** [comment]
Looks like the language server doesn't know where the jdk 14 on your system is.  I think you could specify the java home path in the initialization options ([see their wiki](https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request)) or you could run the language server itself with jdk 14

**Comment by Matsuuu** [comment]
I've set my JAVA_HOME to point at my jdk14 installation folder. 

When I run ` java --version` , it says it's using the jdk 14, so I would assume the jdtls does too?

I've re-installed the jdtls by removing it, and then running `LspInstall jdtls`, but still doesn't seem to function.

It breaks the lsp as soon as i modify my pom.xml to include 

```
plugins>
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-compiler-plugin</artifactId>
              <configuration>
                  <source>14</source>
                  <target>14</target>
              </configuration>
          </plugin>
      </plugins>
```
and 
```
  <properties>
    <maven.compiler.target>14</maven.compiler.target>
    <maven.compiler.source>14</maven.compiler.source>
  </properties>
```

**Comment by mfussenegger** [comment]
Maybe you need to update the project configuration, you could try using the `:JdtUpdateConfig` command and then `:JdtCompile`. If that doesn't work you might need to clear the eclipse.jdt.ls workspace directory. (The folder you pass to `-data` when starting the language server)

**Comment by mfussenegger** [comment]
Did it work?

If you use different source /target compatibilities you may also have to configure different runtimes in the `init_options` of the `config` you pass to `start_or_attach`.

```lua
config.init_options = {
  settings = {
    java = {
      configuration = {
        runtimes = {
          {
            name = 'JavaSE-15', -- name here matters - must be in `JavaSE-version>` format.
            path = 'path/to/jdk/installation'
          },
          {
            ...
          },
        };
      };
    };
  };
]
```

**Comment by Matsuuu** [comment]
Hi,

I ended up just using the nvim lspconfig implementation.

Cheers!
