### ISSUE TITLE
Getting vim.lsp.diagostics.get deprecated warning from organize_imports

### ISSUE THREAD

**Issue by zijian-x** [mfussenegger/nvim-jdtls#194]
### LSP client configuration

```
local workspace_dir = '/home/zijian/.local/share/workspace/'
local config = {
	cmd = {'java-lsp',
		workspace_dir .. vim.fn.fnamemodify(vim.fn.getcwd(), ':p:h:t')
	},
	root_dir = require('jdtls.setup').find_root({'gradle.build', 'pom.xml'}),
}
require('jdtls').start_or_attach(config)

map("n", "<leader>ca", "<cmd>lua vim.lsp.buf.code_action()<cr>")
map("v", "<leader>ca", "<esc><cmd>lua vim.lsp.buf.range_code_action()<cr>")
map("n", "<leader>ci", "<cmd>lua require('jdtls').organize_imports()<cr>")

```

### Eclipse.jdt.ls version

1.6.3

### Steps to Reproduce

`lua  require('jdtls').organize_imports()`

### Expected Result

No lsp.diagnostics deprecated warnings

### Actual Result

run `lua  require('jdtls').organize_imports()` causes 
`vim.lsp.diagnostic.get is deprecated. See :h deprecated`
warnings

I see in the lastest commit we could use the builtin code action, but there is no corresponding `organize_imports` method. Is the lsp client the roof of the cause of this warning?

**Comment by zijian-x** [comment]
```
nvim -v
NVIM v0.7.0-dev+697-g6063e07a0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
the warnings appear only after today's nvim update, I would assume they are from the nvim client thelmselves.

**Comment by mfussenegger** [comment]
Will be fixed with https://github.com/mfussenegger/nvim-jdtls/pull/195

**Comment by mfussenegger** [comment]
Should be fixed now
