### ISSUE TITLE
Custom code style does not work

### ISSUE THREAD

**Issue by dodonut** [mfussenegger/nvim-jdtls#203]
### LSP client configuration

![image](https://user-images.githubusercontent.com/19748045/146765531-6ff838d7-fbd4-409c-8a62-f80067eb10a4.png)

### Eclipse.jdt.ls version

1.8.0

### Steps to Reproduce

open a java file

### Expected Result

format the language acording to the style by calling the vim.lsp.buf.formatting_sync()

### Actual Result

![image](https://user-images.githubusercontent.com/19748045/146769914-d259a040-bb56-471e-9629-404d25192c74.png)

it format the language in the default style from the vim.lsp.buf.formatting_sync()

By doing the config above, it should replace the default format sync of the language server?

**Comment by dodonut** [comment]
the associated [discussion](https://github.com/mfussenegger/nvim-jdtls/discussions/187)

**Comment by mfussenegger** [comment]
I assume your code style xml doesn't include the `teste` profile.
See https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings

A minimal configuration could look something like this:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profiles version="13">
<profile kind="CodeFormatterProfile" name="MyFormat" version="13">
<setting id="org.eclipse.jdt.core.formatter.join_wrapped_lines" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.lineSplit" value="60"/>
</profile>
</profiles>
```

With the jdtls configuration:

```lua
  config.settings = {
    java = {
      format = {
        settings = {
          url = '/tmp/format.xml'
        }
      },
```

Adding `profile` is only necessary if the xml file has multiple `profile` blocks and it must match the `name=` attribute of one of them.

**Comment by dodonut** [comment]
Oh, I see, did have nothing to do with the plugin. Sorry :)

Works perfectly now. Thanks

**Comment by M4urici0GM** [comment]
I have a similar issue. 
I've set the config:
![image](https://github.com/mfussenegger/nvim-jdtls/assets/37017091/b056a939-2d48-4e3d-b161-dc2e7feb827b)

The profile have indentation of 4, but when i format the code, it still with 2 spaces instead of 4

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-jdtls#indentation-settings-from-eclipse-formatting-configuration-are-not-recognized

**Comment by M4urici0GM** [comment]
after a while i was able to fix it
thanks bud :shipit:

**Comment by nicos68** [comment]
Similar issue here : My formatting settings file, which I have generated using eclipse, is [here](https://codeberg.org/nise/dotfiles/src/commit/e639bd6156208e95ddfd67cd10970b542845eea5/.config/java-formatter-settings.xml) and my jdtls configuration is [here](https://codeberg.org/nise/dotfiles/src/commit/e639bd6156208e95ddfd67cd10970b542845eea5/.config/nvim/ftplugin/java.lua). I made several impactful changes, such as brace positions and maximum line width, which are all correctly applied when I format my code through eclipse. But in neovim any setting that I change makes no difference.

![Image](https://github.com/user-attachments/assets/33697d77-f92a-4284-9d81-322fe3d47649)
![Image](https://github.com/user-attachments/assets/d141253c-daac-4736-984e-1ca6a513bf3e)
