### ISSUE TITLE
autocompletion with nvim-cmp

### ISSUE THREAD

**Issue by abenz1267** [mfussenegger/nvim-jdtls#204]
### LSP client configuration

Config directly from this readme. LSP starts and is working!

### Eclipse.jdt.ls version

latest

### Steps to Reproduce

try to use autocompletion with nvim-cmp

### Expected Result

autocompletion

### Actual Result

no autocompletion

**Comment by EpsilonKu** [comment]
Are u sure that ur nvim-cmp config is working well with other lsp?

**Comment by abenz1267** [comment]
Yes! Works just fine.

**Comment by mfussenegger** [comment]
I suspect eclipse.jdt.ls isn't recognizing the project and is running in syntax-only mode.
See the troubleshooting section in the readme - and try running `:lua require('jdtls').compile('full')`

**Comment by abenz1267** [comment]
No, it's recognizing the project just fine. Otherwise I'd get that "project not recognized only reporting syntax errors" lint message at the beginning of the file.

But according to you it should just work out of the box with nvim-cmp? No source for that needed or any other configuration?

**Comment by mfussenegger** [comment]
I'd suggest to first try the built-in omnicompletion (`CTLR+X CTLR+O`), if that works the problem isn't with jdtls but with nvim-cmp and you better ask there for support.

**Comment by abenz1267** [comment]
thanks for the pointer! i will surely try that out!

**Comment by mfussenegger** [comment]
Did you get the omnifunc to work?

**Comment by abenz1267** [comment]
Hi, 

i was busy working, couldn't play around with my config...but took the time today! Autocompletion works fine. Just took ages to load with this giant project.

Regards
