### ISSUE TITLE
Constant popups when downloading dependencies

### ISSUE THREAD

**Issue by eruizc-dev** [mfussenegger/nvim-jdtls#207]
### LSP client configuration

```lua
function lsp.get_jdtls_config()
  local bundles = {
    vim.fn.glob("$HOME/repos/microsoft/java-debug/com.microsoft.java.debug.plugin/target/com.microsoft.java.debug.plugin-*.jar"),
  }
  vim.list_extend(bundles, vim.split(vim.fn.glob("$HOME/repos/microsoft/vscode-java-test/server/*.jar"), "\n"))

  return {
    cmd = { 'jdtls' },
    root_dir = jdtls_setup.find_root({ '*.gradle', 'pom.xml' }),
    init_options = {
      bundles = bundles
    },
    settings = {
      java = {
        implementationsCodeLens = {
          enabled = true
        },
        completion = {
          importOrder = {}
        },
        sources = {
          organizeImports = {
             starThreshold = 2,
             staticStarThreshold = 2
          }
        }
      }
    },
    capabilities = lspconfig.util.default_config.capabilities,
    on_attach = function(client)
      jdtls_setup.add_commands()
      jdtls.setup_dap({ hotcodereplace = 'auto' })
      jdtls.update_project_config()
    end
  }
end
```

### Eclipse.jdt.ls version

1.6.4

### Steps to Reproduce

In a project using either maven or gradle where the dependencies have not yet been downloaded, open a file and the prompts will begin.

### Expected Result

The download should happen in the background, maybe open a terminal where I can see the progress. The problem with the current implementation is that I get a new prompt for every dependency it installs, making Neovim unusable until all dependencies are downloaded.

### Actual Result

A prompt is created after each package starts downloading, capturing the next input and making Neovim unusable.

![image](https://user-images.githubusercontent.com/58179604/147688899-9e93e246-4b00-45ba-b978-d460dac903f3.png)

**Comment by mfussenegger** [comment]
What's your `cmdheight` setting? (`:set cmdheight`) 

The messages displayed shouldn't trigger a ENTER prompt.


You could disable the display entirely by adding a custom `language/status` handler to your configuration: 

```lua
config.handlers['language/status'] = function() end
```

**Comment by mfussenegger** [comment]
Even with `cmdheight` set to 1 I cannot reproduce this.

**Comment by eruizc-dev** [comment]
`set cmdheight` returns 1

The workaround setting status works

I haven't found a way to replicate this always, it sometimes happens and sometimes don't. May be because I like to spam random keys in my keyboard waiting for it to finish, without noticing. I'll close this if I don't find a way to replicate.

Thanks for your help!

**Comment by mabuchner** [comment]
I'm also getting those popups in my Java project when it's trying to download Gradle dependencies.

<img width="1528" alt="Screenshot 2022-05-12 at 11 13 25" src="https://user-images.githubusercontent.com/6006874/167985898-e89b41eb-617e-4338-a9f2-7a4bba89ca4a.png">

I'm actually using [nvim-notify](https://github.com/rcarriga/nvim-notify), but so far I haven't seen any notifications from nvim-jdtls.

**Comment by elliebodi** [comment]
This occurs when the length of the status messages exceeds `vim.v.echospace`. It can be reproduced when the URLs of dependencies are sufficiently long. #509 fixes this by truncating messages to not exceed that length.
