### ISSUE TITLE
Errors when loading a java file

### ISSUE THREAD

**Issue by yusuphgammut** [mfussenegger/nvim-jdtls#221]
### LSP client configuration

local project_name = vim.fn.fnamemodify(vim.fn.getcwd(), ':p:h:t')
local workspace_dir = '~/.myconfigs/neovim/jdtls-data' .. project_name

```
local config = {
  cmd = {
    'java',
    '-Declipse.application=org.eclipse.jdt.ls.core.id1',
    '-Dosgi.bundles.defaultStartLevel=4',
    '-Declipse.product=org.eclipse.jdt.ls.core.product',
    '-Dlog.protocol=true',
    '-Dlog.level=ALL',
    '-Xms1g',
    '--add-modules=ALL-SYSTEM',
    '--add-opens', 'java.base/java.util=ALL-UNNAMED',
    '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
    '-jar', '~/.config/nvim/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar',
    '-configuration', '~/.config/nvim/jdtls/config_mac',
    '-data', workspace_dir,
  },
  root_dir = require('jdtls.setup').find_root({'.git', 'pom.xml', 'mvnw', 'gradlew'}),
  settings = {
    java = {
    }
  },
  init_options = {
    bundles = {}
  },
}
```

require('jdtls').start_or_attach(config)

### Eclipse.jdt.ls version

jdt-language-server-1.8.0-202112170540

### Steps to Reproduce

I'm using java versions 8.292.10.1 and 17.0.1, downloaded via sdkman. When I open a .java file in a project that has a .git folder and a pom.xml file in the project's root, the errors listed below appear.

I'm using macOS 11.6 and neovim 0.6.0.

I'm new to the Java ecosystem so I'm not sure if I'm doing something wrong in the config or in the way I've installed the binaries. Any guidance will be appreciated.

### Expected Result

jdtls loaded without errors

### Actual Result

jdtls is not loaded and the log shows the following errors when different java versions are used.

When using java 8.292.10.1

```
[ERROR][2022-01-10 19:40:15] .../vim/lsp/rpc.lua:417	"rpc"	"java"	"stderr"	"Unrecognized option: --add-modules=ALL-SYSTEM\nError: Could not create the Java Virtual Machine.\nError: A fatal exception has occurred. Program will exit.\n"
```

When using java 17.0.1

```
[ERROR][2022-01-10 20:44:24] .../vim/lsp/rpc.lua:417	"rpc"	"java"	"stderr"	"Error: Unable to access jarfile ~/.config/nvim/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar\n"
```

**Comment by mfussenegger** [comment]
Eclipse.jdt.ls requires at least java 11 and you must use the full path everywhere.  The tilde isn't getting expanded that's why it can't access the jar file

**Comment by yusuphgammut** [comment]
Thanks @mfussenegger. That makes sense.

**Comment by stefumies** [comment]
I have the same issue on mac, and I still have the same error as above, even with the full path. I have tried with mason installed jdtls (as I need lombok) and with downloaded version in /opt with all correct permissions. Could this be a mac thing?
