### ISSUE TITLE
Cannot detect project, only syntax errors are reported.

### ISSUE THREAD

**Issue by AryanPandeyy** [mfussenegger/nvim-jdtls#222]
### LSP client configuration

require('jdtls').start_or_attach({cmd={'jdtls',
os.getenv('HOME') .. '/workspace/' .. vim.fn.fnamemodify(vim.fn.getcwd(),':p:h:t')},
root_dir = require('jdtls.setup').find_root({'gradle.build', 'pom.xml', '.git'})
})

### Steps to Reproduce

Create a folder. Initialize a git in it. Make a file .java. And when I try to work on that file I only get syntax errors.
![2022-01-11-102457_1366x708_scrot](https://user-images.githubusercontent.com/76730713/148884156-aa13f80e-fb9f-4879-917f-1fb2202bc52b.png)

### Expected Result

It should be working  in the current file with all functionality.

### Actual Result

But only reporting syntax errors.

**Comment by mfussenegger** [comment]
You need a gradle or maven project for the full functionality

**Comment by mfussenegger** [comment]
Can you try deleting the workspace folder? I suspect the data in the workspace folder got corrupt. (The directory/path you pass to `-data` in the cmd)

**Comment by AryanPandeyy** [comment]
Sadly, I've been trying this more than a week deleting workspaces, changing it. Nothing works. It just can't detect my projects. To make sure I even created my project using Eclipse IDE but that doesn't work too. And yeah any commands of Jdt like 
>:Jdtcompile 
Doesn't seems to work too.

**Comment by mfussenegger** [comment]
There is no build.gradle file or .git folder in your last screenshot, could be that your root_dir pattern is not working

**Comment by AryanPandeyy** [comment]
Thanks for your help. Removing workspace and assigning to new location did the work. And even .git is detected as a project.

**Comment by liufuyang** [comment]
Thanks. It seems this -data location cannot be set to the same location of the gradle project (or cannot set being inside of the gradle project folder?)

I am having the same issue here, not quite sure how to solve it yet. I think it would be nice if the doc can mention clear about where -data should be targeted.

So for example, if a gradle project is under
`~/dev/xy/project-1` (which is for example `/User/me/dev/xy/project-1`)
and you set the -data folder to be
`/User/me/dev/xy/project-1` or `/User/me/dev/xy/project-1/.data`?

(And yes I learned later `~` is not allowed, would be nice to mention it in the -data setting session as well I suppose.)
