### ISSUE TITLE
Java refactoring move file does not work

### ISSUE THREAD

**Issue by rishabh3** [mfussenegger/nvim-jdtls#233]
### LSP client configuration

```
    local on_attach = function(client, bufnr)
        require "jdtls".setup_dap()
		require "lsp_signature".on_attach()
        require "jdtls.setup".add_commands()
        local function buf_set_keymap(...)
            vim.api.nvim_buf_set_keymap(bufnr, ...)
        end
        local function buf_set_option(...)
            vim.api.nvim_buf_set_option(bufnr, ...)
        end

        buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")

        -- Mappings.
        local opts = {noremap = true, silent = true}
        buf_set_keymap("n", "gD", "<Cmd>lua vim.lsp.buf.declaration()<CR>", opts)
        buf_set_keymap("n", "gd", "<Cmd>lua vim.lsp.buf.definition()<CR>", opts)
        buf_set_keymap("n", "K", "<Cmd>lua vim.lsp.buf.hover()<CR>", opts)
        buf_set_keymap("n", "gi", "<cmd>lua vim.lsp.buf.implementation()<CR>", opts)
        buf_set_keymap("n", "<C-k>", "<cmd>lua vim.lsp.buf.signature_help()<CR>", opts)
        buf_set_keymap("n", "<leader>wa", "<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>", opts)
        buf_set_keymap("n", "<leader>wr", "<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>", opts)
        buf_set_keymap("n", "<leader>wl", "<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>", opts)
        buf_set_keymap("n", "<leader>D", "<cmd>lua vim.lsp.buf.type_definition()<CR>", opts)
        buf_set_keymap("n", "<leader>rn", "<cmd>lua vim.lsp.buf.rename()<CR>", opts)
		buf_set_keymap('n', '<space>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>', opts)
        buf_set_keymap("n", "gr", "<cmd>lua vim.lsp.buf.references()<CR>", opts)
        buf_set_keymap("n", "<space>e", "<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>", opts)
        buf_set_keymap("n", "[d", "<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>", opts)
        buf_set_keymap("n", "]d", "<cmd>lua vim.lsp.diagnostic.goto_next()<CR>", opts)
        buf_set_keymap("n", "<leader>q", "<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>", opts)
        -- Java specific
        buf_set_keymap("n", "<leader>di", "<Cmd>lua require'jdtls'.organize_imports()<CR>", opts)
        buf_set_keymap("n", "<leader>dt", "<Cmd>lua require'jdtls'.test_class()<CR>", opts)
        buf_set_keymap("n", "<leader>dn", "<Cmd>lua require'jdtls'.test_nearest_method()<CR>", opts)
        buf_set_keymap("v", "<leader>de", "<Esc><Cmd>lua require('jdtls').extract_variable(true)<CR>", opts)
        buf_set_keymap("n", "<leader>de", "<Cmd>lua require('jdtls').extract_variable()<CR>", opts)
        buf_set_keymap("v", "<leader>dm", "<Esc><Cmd>lua require('jdtls').extract_method(true)<CR>", opts)
        buf_set_keymap("n", "<space>f", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)
        buf_set_keymap("v", "<space>f", "<cmd>lua vim.lsp.buf.range_formatting()<CR>", opts)

        vim.api.nvim_exec(
            [[
          hi LspReferenceRead cterm=bold ctermbg=red guibg=LightYellow
          hi LspReferenceText cterm=bold ctermbg=red guibg=LightYellow
          hi LspReferenceWrite cterm=bold ctermbg=red guibg=LightYellow
          augroup lsp_document_highlight
            autocmd!
            autocmd CursorHold <buffer> lua vim.lsp.buf.document_highlight()
            autocmd CursorMoved <buffer> lua vim.lsp.buf.clear_references()
          augroup END
      ]],
            false
        )

		vim.notify("Started jdtls client")
    end

    local root_markers = {".git", "gradlew", "pom.xml"}
    local root_dir = require("jdtls.setup").find_root(root_markers)
    local home = os.getenv("HOME")

    local capabilities = {
        workspace = {
            configuration = true
        },
        textDocument = {
            completion = {
                completionItem = {
                    snippetSupport = true
                }
            }
        }
    }

    local workspace_folder = vim.fn.fnamemodify(root_dir, ":p:h:t")
    local config = {
        flags = {
            allow_incremental_sync = true
        },
        capabilities = capabilities,
        on_attach = on_attach
    }

    config.settings = {
        java = {
            signatureHelp = {enabled = true},
            contentProvider = {preferred = "fernflower"},
            completion = {
                favoriteStaticMembers = {
                    "org.hamcrest.MatcherAssert.assertThat",
                    "org.hamcrest.Matchers.*",
                    "org.hamcrest.CoreMatchers.*",
                    "org.junit.jupiter.api.Assertions.*",
                    "java.util.Objects.requireNonNull",
                    "java.util.Objects.requireNonNullElse",
                    "org.mockito.Mockito.*"
                }
            },
            sources = {
                organizeImports = {
                    starThreshold = 9999,
                    staticStarThreshold = 9999
                }
            },
            codeGeneration = {
                toString = {
                    template = "${object.className}{${member.name()}=${member.value}, ${otherMembers}}"
                }
            },
            configuration = {
                runtimes = {
                    {
                        name = "JavaSE-11",
                        path = os.getenv("JAVA_HOME")
                    }
                }
            }
        }
    }

    config.cmd = {"launch_jdtls", workspace_folder}
    config.on_attach = on_attach

    config.on_init = function(client, _)
        client.notify("workspace/didChangeConfiguration", {settings = client.config.settings})
    end

    local extendedClientCapabilities = require "jdtls".extendedClientCapabilities
    extendedClientCapabilities.resolveAdditionalTextEditsSupport = true
    config.init_options = {
        -- bundles = bundles;
        extendedClientCapabilities = extendedClientCapabilities
    }

    -- UI
    --local finders = require "telescope.finders"
    --local sorters = require "telescope.sorters"
    --local actions = require "telescope.actions"
    --local pickers = require "telescope.pickers"
    --local action_state = require "telescope.actions.state"

    --require("jdtls.ui").pick_one_async = function(items, prompt, label_fn, cb)
    --local opts = {}
    --pickers.new(
    --opts,
    --{
    --prompt_title = prompt,
    --finder = finders.new_table {
    --results = items,
    --entry_maker = function(entry)
    --return {
    --value = entry,
    --display = label_fn(entry),
    --ordinal = label_fn(entry)
    --}
    --end
    --},
    --sorter = sorters.get_generic_fuzzy_sorter(),
    --attach_mappings = function(prompt_bufnr)
    --actions.select_default:replace(
    --function()
    --local selection = action_state.get_selected_entry(prompt_bufnr)

    --actions.close(prompt_bufnr)

    --cb(selection.value)
    --end
    --)

    --return true
    --end
    --}
    --):find()
    --end

    -- Debugger Support
    -- This bundles definition is the same as in the previous section (java-debug installation)
    local bundles = {
        vim.fn.glob(
            home ..
                "/.local/java_debug/java-debug/com.microsoft.java.debug.plugin/target/com.microsoft.java.debug.plugin-*.jar"
        )
    }

    -- This is the new part
    vim.list_extend(bundles, vim.split(vim.fn.glob(home .. "/.local/java_debug/vscode-java-test/server/*.jar"), "\n"))
    vim.list_extend(bundles, vim.split(vim.fn.glob(home .. "/.local/java_debug/vscode-java-decompiler/server/*.jar"), "\n"))
    config["init_options"] = {
        bundles = bundles
    }

```

### Steps to Reproduce

In a maven project, when I try to move a class from one package to another, nothing happens on selecting the destination package.

### Expected Result

The class file should be moved to destination package

### Actual Result

The class file remains in the same package

**Comment by rishabh3** [comment]
Any updates @mfussenegger ??

**Comment by mfussenegger** [comment]
works fine for me:


https://user-images.githubusercontent.com/38700/153376226-ec5f9e79-eea9-4403-9d37-885fdca6d554.mp4

You'd have to provide a minimal but complete reproduction (not some video, but folder layout, minimal pom, etc..)

**Comment by rishabh3** [comment]
Closing issue as this works

**Comment by rishabh3** [comment]
Reopening this issue as the issue persist, please find the following details:
Folder Structure:
<img width="248" alt="Screenshot 2022-02-27 at 1 25 10 PM" src="https://user-images.githubusercontent.com/17352263/155873704-7b9112a2-2ddc-471b-964c-750073c87b11.png">
Here the file I am testing on is under package com.personal.test.trial.bar. There is another sibling folder foo where I want to move my file to.
When I trigger the code action move on the class A java file, the refactoring does not work and the file remains under same package.
Before starting refactoring
<img width="448" alt="Screenshot 2022-02-27 at 1 27 14 PM" src="https://user-images.githubusercontent.com/17352263/155873806-a4d57a74-831a-4ca2-8f25-d52885416c59.png">
During move command, the packages available
<img width="1789" alt="Screenshot 2022-02-27 at 1 27 44 PM" src="https://user-images.githubusercontent.com/17352263/155873838-5bb40e69-b822-45b
<img width="1792" alt="Screenshot 2022-02-27 at 1 28 33 PM" src="https://user-images.githubusercontent.com/17352263/155873876-e0360b62-42a2-4089-a037-ef4596f6e0fa.png">
6-97d6-9ab0beed3312.png">
No change has been observed,
the file layout post running the code action

<img width="249" alt="Screenshot 2022-02-27 at 1 29 14 PM" src="https://user-images.githubusercontent.com/17352263/155873909-14787196-9232-4d07-984b-93b849a44630.png">

Please find the pom.xml for the project here:
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.6</version>
		<relativePath/> 
	</parent>
	<groupId>com.personal</groupId>
	<artifactId>test</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>testproject</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>11</java.version>
		<dal-data-interface.version>13.5</dal-data-interface.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<version>4.9.1</version>
		</dependency>


		<dependency>
			<groupId>com.sendgrid</groupId>
			<artifactId>sendgrid-java</artifactId>
			<version>4.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
		<dependency>
			<groupId>org.liquibase.ext</groupId>
			<artifactId>liquibase-mssql</artifactId>
			<version>4.8.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>javax.persistence</groupId>
			<artifactId>javax.persistence-api</artifactId>
			<version>2.2</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>mssql-jdbc</artifactId>
			<scope>runtime</scope>
		</dependency>



	</dependencies>

	<repositories>
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>cas-virtual-maven</name>
			<url>https://mia-repo.citrite.net/cas-virtual-maven</url>
		</repository>
		<repository>
			<snapshots />
			<id>snapshots</id>
			<name>cas-virtual-maven</name>
			<url>https://mia-repo.citrite.net/cas-virtual-maven</url>
		</repository>
		<repository>
			<id>cc.internal</id>
			<name>Citrix Cloud Internal Repository</name>
			<layout>default</layout>
			<url>https://mia-repo.citrite.net/cc-local-maven</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.liquibase</groupId>
				<artifactId>liquibase-maven-plugin</artifactId>
				<version>4.8.0</version>
				<configuration>
					<propertyFile>liquibase.properties</propertyFile>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.liquibase.ext</groupId>
						<artifactId>liquibase-mssql</artifactId>
						<version>4.8.0</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>

</project>
`
The jdtls configuration I have pasted in the above comment

**Comment by mfussenegger** [comment]
I think the underlying issue has been fixed in Neovim itself. If this is still a problem in neovim 0.8.1 please let me know
