### ISSUE TITLE
Code actions do not work; would like to add missing imports

### ISSUE THREAD

**Issue by fwy** [mfussenegger/nvim-jdtls#239]
### LSP client configuration

I have a complex configuration that I will omit for now, as I believe it works fine.  (I can provide specific details as needed.)

### Eclipse.jdt.ls version

jdt language server 1.4.0-202109161824

### Steps to Reproduce

In neovim, while viewing the buffer for a Java source file that is attached to the jdtls client and language server, the following neovim command does not work:

`:lua require("jdtls").code_action(true)`

The error message is:

```
E5108: Error executing lua [string ':lua']:1: attempt to call field 'code_action' (a nil value)
stack traceback:
        [string: ":lua"]:1: in main chunk
```

I checked jdtls.lua, and can see that no 'code_action' function is defined anywhere.  (I thought this worked at one time, but could be wrong.)

I am still able to use this default LSP code action logic:

`:lua vim.lsp.buf.code_action()
`
However, the code action I really want to do is add missing import statements, not reorganize/resort all import statements already inside the class as with 'organize_imports'.  I thought this code action was possible at one time, but now don't see it even in LSP.

So, two questions: (1) is this a bug; and (2) is there a good solution in nvim-jdtls for adding missing import statements?

### Expected Result

Select the code action to add missing import statements, which are then added to the Java source file.

### Actual Result

Error message from command ':lua require("jdtls").code_action(true)`:

```
E5108: Error executing lua [string ':lua']:1: attempt to call field 'code_action' (a nil value)
stack traceback:
        [string: ":lua"]:1: in main chunk
```'

**Comment by mfussenegger** [comment]
The `code_action` function from nvim-jdtls got removed, see https://github.com/mfussenegger/nvim-jdtls/issues/3#issuecomment-1013530502

`:lua vim.lsp.buf.code_action()` should show an action to add an import if the cursor is on a symbol which is missing.

**Comment by fwy** [comment]
Thanks for the information.  I update my plugins often but don't see these kinds of comments, and haven't used code actions in a while.

I tried vim.lsp.buf.code_action() again, and observe that it is very inconsistent.  Sometimes it will show the desired import action in the code action list; sometimes it won't; and sometimes it says 'No code actions available' with no list at all -- even when focusing on the same unresolved symbol each time!  However, I understand that isn't your problem.

The jdtls plugin is very good, almost indispensable for Java developers using neovim.  Thanks for developing it!

**Comment by mfussenegger** [comment]
> , and observe that it is very inconsistent. Sometimes it will show the desired import action in the code action list; sometimes it won't; and sometimes it says 'No code actions available' with no list at all 

Maybe you could file an upstream issue in eclipse.jdt.ls for that if you have a reliable and small reproduction.
