### ISSUE TITLE
Implement progress endpoint instead of printing to the command area

### ISSUE THREAD

**Issue by pollen00** [mfussenegger/nvim-jdtls#252]
### Problem Statement

Certain plugins use the progress endpoint, and while (I'm pretty sure) jdtls doesn't implement that endpoint, there's still load progress printed in the command area that then can't be used by other plugins since it's not an lsp endpoint.

### Ideas or possible solutions

For people who still want lsp load progress but don't have some other plugin to pick up the lsp endpoint, there could just be a toggle to turn off printing to the command area and instead send it over the lsp progress endpoint.
Endpoint is here in the spec https://microsoft.github.io/language-server-protocol/specifications/specification-current/#progress

**Comment by mfussenegger** [comment]
eclipse.jdt.ls has two different ways to report the progress. One of the per default uses `echo` to report the updates to the user. You can mute that by setting:

```lua
config.handlers['language/status'] = function() end
```

The second way to report the progress is via `language/progressReport`, nvim-jdtls currently adds those messages to the `client.messages.progress` table - which allows to consume them via `vim.lsp.util.get_progress_messages()` (this is the same mechanism that neovim core implements to handle `$/progress`).
