### ISSUE TITLE
Jdtls stopped reporting symbol information

### ISSUE THREAD

**Issue by asmodeus812** [mfussenegger/nvim-jdtls#256]
### LSP client configuration

```Lua
   local root_loc = require('jdtls.setup').find_root(roots)
    local data_loc = fn.get_data_dir() -- nvim data directory

    local cmd = vim.fn.JdtlsCommand(data_loc, root_loc, {})
    cmd = vim.list_extend({ cmd.executable }, cmd.arguments)

    return {
        -- See: https://github.com/eclipse/eclipse.jdt.ls#running-from-the-command-line for jdtls configuration
        cmd = cmd,
        flags = {
            debounce_text_changes = 150,
            allow_incremental_sync = true,
        },
        handlers = {},
        root_dir = root_loc,
        on_attach = require("plugin.lsp.handlers").on_attach,
        capabilities = require("plugin.lsp.handlers").capabilities,
        init_options = {
            bundles = require("plugin.lsp.debugger").java_bundles()
        },
        -- See https://github.com/eclipse/eclipse.jdt.ls/wiki/running-the-java-ls-server-from-the-command-line#initialize-request
        settings = {
            java = {
                trace = {
                    server = "message",
                },
                signatureHelp = {
                    enabled = true
                },
                referenceCodeLens = {
                    enabled = true
                },
                format = {
                    enabled = true,
                    insertSpaces = true
                },
                codeGeneration = {
                    tostring = {
                        listArrayContents = true,
                        skipNullValues = true,
                        template = "${object.className}{${member.name()}=${member.value}, ${otherMembers}}",
                    },
                    useBlocks = true,
                    hashCodeEquals = {
                        useInstanceof = true,
                        useJava7Objects = true
                    },
                    generateComments = true,
                    insertLocation = true
                },
                progressReports = {
                    enabled = true
                },
                eclipse = {
                    downloadSources = true
                },
                maven = {
                    downloadSources = true,
                    updateSnapshots = true
                }
            }
        }
    }

[START][2022-04-08 07:27:07] LSP logging initiated
[WARN][2022-04-08 07:27:18] ...lsp/handlers.lua:109	"The language server jdt.ls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

![image](https://user-images.githubusercontent.com/15955811/162363307-535fc123-6fdc-47c3-9895-c18181af9b1f.png)

### Eclipse.jdt.ls version

Latest (from lsp_install)

### Steps to Reproduce

In a project using maven, up untill very recently i was able to properly access all references for symbols - definitons, references, implementations etc. Now i receive a message "No references found" +"jump_to_location must be called with valid offset encoding" when i try to execute vim.lsp.buf actions such as go to definition or references. The project is spring based. Note that before, i used to notice that when i opened the project for the first time jdtls started downloading maven dependencies, now it just says ServiceReady and seems to not fetch any dependencies. It would be great if we could actually tell what it was doing. I tried attaching handler to the progress endpoint, nothing relevant was printed. Jdtls was just starting and not trying to download anything. 

### Expected Result

That going to references, definition etc works as expected.

### Actual Result

Message shown "No references found", No errors are observed !
NOTE: I also started getting the following message - "jump_to_location must be called with valid offset encoding"

Note that if i go to java core/util elements such as the override annotation i get the decompiled  version instead of the actual source but it does work for those. But that is probably comming from jdtls decompiling on the fly. 
![image](https://user-images.githubusercontent.com/15955811/162364014-35950086-c098-49b5-945c-ebbf89daf535.png)

**Comment by mfussenegger** [comment]
Did you update eclipse.jdt.ls? It's possible that you need to b delete the data folder after an update. See https://github.com/mfussenegger/nvim-jdtls#troubleshooting

**Comment by asmodeus812** [comment]
@mfussenegger  yes for testing purposes i always delete the data folder just to make sure everything is running okay. One more question not related but, i have attached a progress report handler (using fidget) but i would like to remove the echo line from jdtls which gets printed when first loading the workspace/project. Is it possible to disable that 
![image](https://user-images.githubusercontent.com/15955811/162391431-3de91112-c365-4d7b-bbba-396fb5a85ac5.png)

**Comment by mfussenegger** [comment]
What happens if you run `:JdtCompile` (or `require('jdtls').compile()`)?


> NOTE: I also started getting the following message - "jump_to_location must be called with valid offset encoding"

Do you have any other plugins which override the location handlers? Could be that one is interferring.


>  Is it possible to disable that


Extend your `handlers` with:

```lua
handlers = {
  ['language/status'] = function() end,
}
```

**Comment by asmodeus812** [comment]
@mfussenegger  I have no external handlers that mess with the default ones. I used to have lsp_handlers plugin, but this was not happening with or without it back then, it seems to be something recent. I came across a reddit thread from the core nvim team saying that they changed something in nvim core which might break plugins and show this message. 
I have had some progress, i noticed that if i change the location of the cache/data folder for jdtls it did manage to start resolving references, i used to have it in the /path-to-project-root/.cache/jdtls now i moved in /home/user/workspaces/project-name/.cache/jdtls. I have no idea why that matters, clangd stores its cache in the project root by the way

**Comment by mfussenegger** [comment]
nvim-jdtls doesn't make any `jump_to_location` calls, so the error must be coming from something else.
The offset_encoding adjustements required due to neovim core changes were made a while ago: https://github.com/mfussenegger/nvim-jdtls/commit/2cceff656f2bfac38da784f2cd4b202a64a2faf3
