### ISSUE TITLE
springboot项目远程启动debug，好像并没有方法进入调试

### ISSUE THREAD

**Issue by yil3** [mfussenegger/nvim-jdtls#258]
### Problem Statement

junit测试类或者方法都可以成功。
配置调试器后，要如何启动debug呢？

**Comment by yil3** [comment]
E5108: Error executing lua ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:214: `dap.configurations.java` must be a list of configurations, got {
  hostName = "127.0.0.1",
  name = "Debug (Attach) - Remote",
  port = "5005",
  request = "attach",
  type = "java"
}
stack traceback:
        [C]: in function 'assert'
        ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:214: in function 'select_config_and_run'
        ...l/share/nvim/site/pack/packer/start/nvim-dap/lua/dap.lua:565: in function 'continue'
        [string ":lua"]:1: in main chunk

**Comment by yil3** [comment]
配置文件搞错了，即使弄对了也报错
Debug adapter didn't respond. Either the adapter is slow (then wait and ignore this) or there is a problem with your adapter or `java` configuration. Check the logs for errors (:help dap.set_log_level)

**Comment by EpsilonKu** [comment]
Can you share your debug config?

**Comment by hewenjin** [comment]
如果是 springboot 本地项目，不需要远程配置，执行 `:JdtRefreshDebugConfigs` 和 `lua require'dap'.continue()` 后你应该看得到选择启动 debug session 的确认框了

**Comment by yil3** [comment]
> 如果是 springboot 本地项目，不需要远程配置，执行 `:JdtRefreshDebugConfigs` 和 `:lua require'dap'.continue()` 后你应该看得到选择启动 debug session 的确认框了

Configuration:
1: Debug (Attach) - Remote
2: Launch org.ks365.osmp.OsmpApplication
Type number and <Enter> or click with the mouse (q or empty cancels):

1：是我配置的远程debug
2：dap发现的类好像启动后显示找不到类
  1 Error: Could not find or load main class org.ks365.osmp.OsmpApplication
  2 Caused by: java.lang.ClassNotFoundException: org.ks365.osmp.OsmpApplication
-----------------------------
尴尬，捣鼓一阵，本地远程配置debug启动成功了，不过好像也有点问题。第一次进入页面断点的位置不对，各种报错，第二次好像又好了

**Comment by yil3** [comment]
> Can you share your debug config?

use {
    "mfussenegger/nvim-dap",
    config = function()
        require("conf.nvim-dap")
    end
}

conf/nvim-dap.lua  
local dap_config = {
    -- rust = require("dap.rust"),
    java = require("dap.java"),
    go = require("dap.go"),
    -- python = require("dap.python"),
}
-- 设置调试器
for dap_name, dap_options in pairs(dap_config) do
    dap.adapters[dap_name] = dap_options.adapters
    dap.configurations[dap_name] = dap_options.configurations
end

dap/java.lua
return {
    -- adapters = function(callback)
    -- callback({
    --     type = 'server';
    --     host = '127.0.0.1';
    --     port = '5005';
    -- })
    -- end,
    configurations = {
        {
            type = 'java';
            request = 'attach';
            name = "Debug (Attach) - Remote";
            hostName = "127.0.0.1";
            port = 5005;
        }
    }
}

**Comment by hewenjin** [comment]
> 

不确定你的配置是不是有弄错，可以参考我的配置
https://github.com/hewenjin/config/blob/main/nvim/lua/lsp/jdtls/init.lua

**Comment by hewenjin** [comment]
[](url)

> > 如果是 springboot 本地项目，不需要远程配置，执行 `:JdtRefreshDebugConfigs` 和 `:lua require'dap'.continue()` 后你应该看得到选择启动 debug session 的确认框了
> 
> Configuration: 1: Debug (Attach) - Remote 2: Launch org.ks365.osmp.OsmpApplication Type number and or click with the mouse (q or empty cancels):
> 
> 1：是我配置的远程debug 2：dap发现的类好像启动后显示找不到类 Error: Could not find or load main class org.ks365.osmp.OsmpApplication Caused by: java.lang.ClassNotFoundException: org.ks365.osmp.OsmpApplication
> 
> 尴尬，捣鼓一阵，远程配置debug启动成功了，不过好像也有点问题。第一次进入页面断点ui只显示过程有问题，下一步会直接进入各种方法调用的方法里面，各种报错
> 
> 第二次好像又好了

不确定你的配置是不是有弄错，可以参考我的配置
https://github.com/hewenjin/config/blob/main/nvim/lua/lsp/jdtls/init.lua

**Comment by yil3** [comment]
> 不确定你的配置是不是有弄错，可以参考我的配置 https://github.com/hewenjin/config/blob/main/nvim/lua/lsp/jdtls/init.lua

折腾到现在，我终于知道我错在哪了，引入lombok.jar 消除了表面上面的报错，实际上jdtls日志已经报错了，所有错误信息都没了，配置之后启动的cmd也就是有问题的，所以直接:lua require'dap'.continue() 根本就启动不了启动类

终于可以睡觉了

**Comment by yil3** [comment]
添加单元测试，jdtls会有报错日志，这个是怎么回事呀

org.eclipse.core.runtime.CoreException: Load bundle list
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.loadBundles(BundleUtils.java:169)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:91)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:63)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:247)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$0(ParentProcessWatcher.java:123)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Contains: Failed to get bundleInfo for bundle from /home/x/.config/nvim/java_test/com.microsoft.java.test.runner-jar-with-dependencies.jar
!SUBENTRY 1 org.eclipse.jdt.ls.core 4 0 2022-04-19 17:38:04.785
!MESSAGE Load bundle list
!SUBENTRY 2 org.eclipse.jdt.ls.core 4 0 2022-04-19 17:38:04.786
!MESSAGE Failed to get bundleInfo for bundle from /home/x/.config/nvim/java_test/com.microsoft.java.test.runner-jar-with-dependencies.jar

**Comment by hewenjin** [comment]
如果报错但是能正常使用就不用管，这有个类似的问题 #31

**Comment by hewenjin** [comment]
> 添加单元测试，jdtls会有报错日志，这个是怎么回事呀
> 
> org.eclipse.core.runtime.CoreException: Load bundle list at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.loadBundles(BundleUtils.java:169) at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:91) at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:63) at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:247) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65) at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120) at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261) at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190) at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$0(ParentProcessWatcher.java:123) at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194) at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94) at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) Contains: Failed to get bundleInfo for bundle from /home/x/.config/nvim/java_test/com.microsoft.java.test.runner-jar-with-dependencies.jar !SUBENTRY 1 org.eclipse.jdt.ls.core 4 0 2022-04-19 17:38:04.785 !MESSAGE Load bundle list !SUBENTRY 2 org.eclipse.jdt.ls.core 4 0 2022-04-19 17:38:04.786 !MESSAGE Failed to get bundleInfo for bundle from /home/x/.config/nvim/java_test/com.microsoft.java.test.runner-jar-with-dependencies.jar

如果报错但是能正常使用就不用管，这有个类似的问题 #31

**Comment by yil3** [comment]
@hewenjin 

晚上好呀，现在解决了很多很多问题，但是有一个问题始终困扰我～
jdtls启动debug的时候会产生一个打印日志的buffer，这个是一个内置的终端显示的。
它好像不支持中文，打印的日志全是？
<img width="926" alt="image" src="https://user-images.githubusercontent.com/57053484/164271503-90eccb8d-21e6-4eac-822f-6bcc5c504c1f.png">

有办法解决嘛～用着倒是没啥大问题

而且使用的buffer插件无法在buffer显示栏 隐藏这个显示日志的buffer
