### ISSUE TITLE
Diagnostics is not working with Lombok

### ISSUE THREAD

**Issue by loktev-d** [mfussenegger/nvim-jdtls#259]
### LSP client configuration

```
local on_attach = function(client, bufnr)
    require('buf_keymaps')(client, bufnr)

    vim.api.nvim_buf_set_keymap(bufnr, "n", "<space>jr", "<cmd>lua require('jdtls').update_project_config()<CR>", {})
end

local config = {
    cmd = {
        'java',
        '-Declipse.application=org.eclipse.jdt.ls.core.id1',
        '-Dosgi.bundles.defaultStartLevel=4',
        '-Declipse.product=org.eclipse.jdt.ls.core.product',
        '-Dlog.protocol=true',
        '-Dlog.level=ALL',
        '-Xms1g',
        '--add-modules=ALL-SYSTEM',
        '--add-opens', 'java.base/java.util=ALL-UNNAMED',
        '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
        '-javaagent:/usr/share/java/lombok/lombok.jar',
        '-Xbootclasspath/a:/usr/share/java/lombok/lombok.jar',
        '-jar', vim.fn.expand('~/.local/share/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar'),
        '-configuration', vim.fn.expand('~/.local/share/jdtls/config_linux'),
        '-data', vim.fn.expand('~/.cache/jdtls'),
    },
    on_attach = on_attach,
    root_dir = require('jdtls.setup').find_root({ '.git', 'mvnw', 'gradlew', 'pom.xml' }),
}

require('jdtls').start_or_attach(config)
```

### Eclipse.jdt.ls version

1.10.0

### Steps to Reproduce

1. Go to maven project
2. Set Lombok in dependencies in pom.xml
3. Open any .java file
4. Update project config
5. Reopen file
6. Write some invalid java code

### Expected Result

Get an error message from diagnostics

### Actual Result

Nothing happens, other lsp features seem to be working though

**Comment by schrieveslaach** [comment]
BTW: checkout [this plugin](https://gitlab.com/schrieveslaach/nvim-jdtls-bundles) which helps to setup Java Debug and Java Test. And also check the wrapper script. My config is much smaller with these in place:

```
 require('jdtls').start_or_attach({                                                                                                                              
    on_attach = on_attach,                                                                                                                                              
    cmd = {       
       'jdtls',
       '-configuration', vim.env.HOME .. '/.cache/jdtls/configuration',                
       '-data', data_path,
       '--jvm-arg=-javaagent:/path/to/lombok.jar',                                       
    },
                                                                                                                                                                                                       
    init_options = {
       bundles = require('nvim-jdtls-bundles').bundles()
    }
}
```

**Comment by loktev-d** [comment]
I've found the solution.
https://github.com/redhat-developer/vscode-java/issues/580#issuecomment-443302372
This comment helped a lot. Basically, `org.eclipse.jdt.core.compiler.processAnnotations=disabled` and `org.eclipse.jdt.apt.aptEnabled=false` need to be set in project's settings. Issue can be closed.

**Comment by allenhong0715** [comment]
> The issue is `'-Xbootclasspath/a:/usr/share/java/lombok/lombok.jar'`. According to [the documentation](https://projectlombok.org/setup/ecj) `-Xbootclasspath` is only required on older Java or Lombok versions. Remove it and try again.

it work!
i think this way is more easy to solve this problom.

**Comment by schrieveslaach** [comment]
@mfussenegger, `-Xbootclasspath` is shown in [the first example in the wiki](https://github.com/mfussenegger/nvim-jdtls/wiki/Sample-Configurations). Do you mind to remove that example?

**Comment by mfussenegger** [comment]
The wiki is currently public and can be edited by anyone
