### ISSUE TITLE
Add a callback to tests

### ISSUE THREAD

**Issue by axieax** [mfussenegger/nvim-jdtls#264]
### Problem Statement

As mentioned [here](https://github.com/mfussenegger/nvim-jdtls/discussions/261)

> Hi, is there a way to attach a function (for retrieving [dap-repl] content) to run after jdtls.test_class or jdtls.test_nearest_method results are populated in the [dap-repl]? I'm currently deferring a call of this function after 2 seconds, where it has to search all buffers for one with the expected title, then extract its contents. Thanks!

### Ideas or possible solutions

Attaching a callback to running tests

**Comment by mfussenegger** [comment]
Could you have a look at https://github.com/mfussenegger/nvim-jdtls/pull/278 ?

With that you should be able to use `require('jdtls').test_nearest_method( { after_test = function() ... end })`

**Comment by axieax** [comment]
Works like a charm! Love this feature so much :D
Thanks!!
