### ISSUE TITLE
lua vim.lsp.buf.hover() displays document not correctly.

### ISSUE THREAD

**Issue by sa82trip** [mfussenegger/nvim-jdtls#273]
### LSP client configuration

```lua
local config = {
	cmd = {
		"java",
		"-Declipse.application=org.eclipse.jdt.ls.core.id1",
		"-Dosgi.bundles.defaultStartLevel=4",
		"-Declipse.product=org.eclipse.jdt.ls.core.product",
		"-Dlog.protocol=true",
		"-Dlog.level=ALL",
		"-Xms1g",
		"--add-modules=ALL-SYSTEM",
		"--add-opens",
		"java.base/java.util=ALL-UNNAMED",
		"--add-opens",
		"java.base/java.lang=ALL-UNNAMED",
		"-jar",
		"/Users/myname/Documents/java/jdt-language-server-1.8.0-202201261434/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar",
		"-configuration",
		"/Users/myname/Documents/java/jdt-language-server-1.8.0-202201261434/config_mac/",
		"-data",
		"/Users/myname/Documents/java/jdt-language-server-1.8.0-202201261434/workspace/"
	},
	root_dir = require("jdtls.setup").find_root({
		".git", "mvnw", "gradlew"}),
		settings = {

			java = {
				signatureHelp = { enabled = true },
			}
		},
		init_options = {

			bundles = {
			}
		}
	}
```

### Eclipse.jdt.ls version

1.8.0

### Steps to Reproduce

1. open *.java file which contains `StringUtils`
2. hover cursor on `StringUtils` and call `lua vim.lsp.buf.hover()`
3. hover window shows document with raw link 
4. e.g 
```
Operations on [java.lang.String](jdt://contents/java.base/java.lang/String.class?=simple-springboot-app/%5C/Library%5C/Java%5C/JavaVirtualMachines%5C/adoptopenjdk-11.jdk%5C/Contents%5C/Home%5C/lib%5C/jrt-fs.jar%60java.base=/maven.pomderived=/true=/=/javadoc_location=/https:%5C/%5C/docs.oracle.com%5C/en%5C/java%5C/javase%5C/11%5C/docs%5C/api%5C/=/%3Cjava.lang%28String.class#125) that are `null` safe.
```

hover window is not rendering `[java.lang.String](jdt link)` link part.

### Expected Result

hover window should display `link` correctly so I can jump to that link as well.

### Actual Result

![image](https://user-images.githubusercontent.com/38380280/171909718-a1d9d692-eb6c-4140-9d3f-6af2a42e4756.jpeg)
hover window is showing raw test instead of displaying `rendered link`

**Comment by mfussenegger** [comment]
This is more of a upstream neovim issue. `hover` is implemented there. I don't plan to add an override here.

**Comment by sa82trip** [comment]
Thank you for letting me know. 
It is good to know that this is not an issue of nvim-jdtls 👍

**Comment by sa82trip** [comment]
then I will close this.

**Comment by denis-gerder** [comment]
I know that this issue is old and closed, but i cannot, for the life of me, resolve the problem. Is there a way to remove the (jdt://...) part? It is really hard to read the documentation.
