### ISSUE TITLE
Lombok and jvm_args

### ISSUE THREAD

**Issue by jemag** [mfussenegger/nvim-jdtls#28]
I have been trying to make Lombok work with nvim-jdtls with no success.

Previously, I was using coc-java and would have the following setting in my coc-settings.json:
``` json
  "java.jdt.ls.vmargs": "-javaagent:/home/jemag/.config/nvim/dependencies/lombok.jar -Xbootclasspath/a:/home/jemag/.config/nvim/dependencies/lombok.jar",
```
This allowed me to use Lombok in my java projects.

Right now, I am unsure how to achieve the same behavior. I have attempted to put it through jvm_args in init_options in a couple of different ways (I am not the best with lua):
``` lua
function start_jdt()
    print("starting jdt")
    require('jdtls').start_or_attach({
    cmd = {'java-lsp.sh'},
    init_options = {
      bundles = {"/home/jemag/dev/java-debug/com.microsoft.java.debug.plugin/target/com.microsoft.java.debug.plugin-*.jar"},
      --jvm_args = {"-javaagent:/home/jemag/.config/nvim/dependencies/lombok.jar", "-Xbootclasspath/a:/home/jemag/.config/nvim/dependencies/lombok.jar"}
      --jvm_args = {"-javaagent:/home/jemag/.config/nvim/dependencies/lombok.jar -Xbootclasspath/a:/home/jemag/.config/nvim/dependencies/lombok.jar"}
      --jvm_args = {["javaagent"]="/home/jemag/.config/nvim/dependencies/lombok.jar", ["Xbootclasspath/a"]="/home/jemag/.config/nvim/dependencies/lombok.jar"}
      --jvm_args = {["java.jdt.ls.vmargs"]="-javaagent:/home/jemag/.config/nvim/dependencies/lombok.jar -Xbootclasspath/a:/home/jemag/.config/nvim/dependencies/lombok.jar"}
    },
    on_attach = function(client)
    on_attach_common(client)
    on_attach_java(client)
    end
    })

end;

local autocmds = {
	lsp = {
		{"FileType",     "java",   "lua start_jdt()"};
	};
}
```
But none of the  commented jvm_args would work. I then tried to modify my java-lsp.sh by adding it there:
``` sh
 #!/bin/bash
 # -Xbootclasspath/a "/home/jemag/.config/nvim/dependencies/lombok.jar" \

JAR="$HOME/dev/eclipse/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_*.jar"
export GRADLE_HOME=/usr/bin/gradle
java \
  -Declipse.application=org.eclipse.jdt.ls.core.id1 \
  -Dosgi.bundles.defaultStartLevel=4 \
  -Declipse.product=org.eclipse.jdt.ls.core.product \
  -Dlog.protocol=true \
  -Dlog.level=ALL \
  -Xms1g \
  -Xmx2G \
  -jar $(echo "$JAR") \
  -configuration "$HOME/dev/eclipse/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/config_linux" \
  -javaagent:/home/jemag/.config/nvim/dependencies/lombok.jar \
  -data "$HOME/dev/eclipse/workspace" \
  --add-modules=ALL-SYSTEM \
  --add-opens java.base/java.util=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED
```

This also did not seem to work. Both methods resulted in me still getting Lombok errors in my projects.

 I was wondering if you had any ideas how this could be achieved properly with nvim-jdtls?

**Comment by mfussenegger** [comment]
`coc-java` uses the `java.jdt.ls.vmargs` option to adjust the command that is used to start the language server. So your variant that adjusts the `java-lsp.sh` script should be correct.

You could try using `coc-java` again, then use `ps aux | grep java` to find the exact command `coc-java` uses to start the language server and then adapt the `java-lsp.sh` based on that.

`eclipse.jdt.ls` itself doesn't support the `vmargs` or `jvm_args` option. So setting any of those within `init_options` won't have any affect.

**Comment by jemag** [comment]
Thanks for the tips.

So apparently -javaagent must always come before the -jar flag, once I did that change in my java-lsp.sh file, it started working properly. So basically:
``` sh
 #!/bin/bash

JAR="$HOME/dev/eclipse/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/plugins/org.eclipse.equinox.launcher_*.jar"
export GRADLE_HOME=/usr/bin/gradle
java \
  -Declipse.application=org.eclipse.jdt.ls.core.id1 \
  -Dosgi.bundles.defaultStartLevel=4 \
  -Declipse.product=org.eclipse.jdt.ls.core.product \
  -Dlog.protocol=true \
  -Dlog.level=ALL \
  -Xms1g \
  -Xmx2G \
  -javaagent:/home/jemag/.config/nvim/dependencies/lombok.jar \
  -Xbootclasspath/a:/home/jemag/.config/nvim/dependencies/lombok.jar \
  -jar $(echo "$JAR") \
  -configuration "$HOME/dev/eclipse/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/config_linux" \
  -data "$HOME/dev/eclipse/workspace" \
  --add-modules=ALL-SYSTEM \
  --add-opens java.base/java.util=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED

```

**Comment by guysherman** [comment]
Just adding some extra info on top of @jemag's post...
I was getting class def not found issues when the LSP was trying to load. (It couldn't find `javax.annotation.processing.AbstractProcessor`) I found it was the `-Xbootclasspath` argument, apparently you *shouldn't* need it for recent versions of java, according to the lombok docs on using Lombok with ECJ/JDT (I'm guessing Java 11 on). Removing it resolved my issue.

**Comment by davidsoles** [comment]
> Just adding some extra info on top of @jemag's post... I was getting class def not found issues when the LSP was trying to load. (It couldn't find `javax.annotation.processing.AbstractProcessor`) I found it was the `-Xbootclasspath` argument, apparently you _shouldn't_ need it for recent versions of java, according to the lombok docs on using Lombok with ECJ/JDT (I'm guessing Java 11 on). Removing it resolved my issue.

Thank you very much my friend. You solved my problem 🥇
