### ISSUE TITLE
Jdtls error

### ISSUE THREAD

**Issue by JjersaR** [mfussenegger/nvim-jdtls#294]
### Problem Statement

Today trying to program with java in neovim I get this error, what can I do?

I had upgraded jdtls to version 13 but from there I got the error, I don't know if there is anything I can do..

Error initializing server
![image](https://user-images.githubusercontent.com/86206596/178780079-b94583d4-5e8a-4860-a035-59ea98466b5c.png)

version of neovim using bob
![image](https://user-images.githubusercontent.com/86206596/178780212-d961bd96-bc66-4fe4-841a-32308556cbea.png)

Error
![image](https://user-images.githubusercontent.com/86206596/178780302-ebdc7c52-8ae1-4927-b575-61bd91a63832.png)

java version I use
![image](https://user-images.githubusercontent.com/86206596/178780443-285cbf75-4646-4963-99fb-702a006f8690.png)

jdtls route file
[log.file](https://gist.github.com/JjersaR/fdf8515714bf5d3daf149355bdbae01d)

Server information 
![image](https://user-images.githubusercontent.com/86206596/178781442-8fb13579-7b40-4e3b-8663-fd7a6a3dccb6.png)

### Ideas or possible solutions

I have no idea what a solution might be

**Comment by mfussenegger** [comment]
> Caused by: java.lang.IllegalStateException: Workspace is already closed or not ready yet. Consider tracking the org.eclipse.core.resources.IWorkspace service (using your favorite technique, e.g. Declarative Services, ServiceTracker, Blueprint, ...) instead of calling the static method here to prevent such issues!
	at org.eclipse.core.resources.ResourcesPlugin.getWorkspace(ResourcesPlugin.java:474)
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.start(JavaLanguageServerPlugin.java:159)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	... 32 more


This indicates that your workspace folder (`-data` directory) is corrupt. Try to delete it. See https://github.com/mfussenegger/nvim-jdtls#the-client-exits-with-an-error--eclipsejdtls-stopped-working

**Comment by mfussenegger** [comment]
Can you try to delete the folder manually then?

**Comment by JjersaR** [comment]
Finally I could fix it, with a script that makes you a launcher and with that everything was fine, thanks

**Comment by nbardiuk** [comment]
@JjersaR can you please share the script?

**Comment by JjersaR** [comment]
Yes, https://github.com/eruizc-dev/jdtls-launcher#uninstall
