### ISSUE TITLE
workspace  and creation of java  project 

### ISSUE THREAD

**Issue by caamittiwari** [mfussenegger/nvim-jdtls#299]
### Problem Statement

i have  created   java  project  inside workspace   by  creating   new folder 
afterward   i created  file  App.java    and    find   error   that  App.java is not on the classpath of project jdt.ls-java-project (2), only syntax errors are reported;

there   is  nothing     documentation   or  wiki     how   to create    java project     in  simple  way 
please  guide

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-jdtls#is-a-non-project-file-only-syntax-errors-are-reported

You need a gradle or maven project. You can refer to their documentation learn how to get started. E.g. https://docs.gradle.org/current/samples/sample_building_java_applications.html

**Comment by caamittiwari** [comment]
Thanks  u very  much for helping   me   now  its  work perfectly   and   your plugin  put me  next level   working  on java  in neovim
