### ISSUE TITLE
Static import symbols

### ISSUE THREAD

**Issue by asmodeus812** [mfussenegger/nvim-jdtls#302]
### Problem Statement

Would it be feasible to add support for a new action which allows us to add a static import to symbols. Also organize imports does not seem to handle (ask for) static imports

**Comment by mfussenegger** [comment]
This is entirely up to the server and the client can't do much about it. eclipse.jdt.ls by default doesn't resolve static methods, but you can configure `favoriteStaticMembers` to have those static methods show up as completion candidates and to make organize imports resolve them.

 (See https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line or an example: https://github.com/mfussenegger/dotfiles/blob/1bdc9d50a7ed6ad98950d0d7407f87bd3442c6f8/vim/.config/nvim/ftplugin/java.lua#L12-L20 )

There should also be a code action to turn a call like `MyClass.staticMethod(foo)` into `staticMethod(foo)`

**Comment by asmodeus812** [comment]
That seems very useful indeed, thanks. If i decide to dynamically put the current project's root package inside favourite static members, would jdtls recognize / search for static imports from the project itself as well ?

> There should also be a code action to turn a call like `MyClass.staticMethod(foo)` into `staticMethod(foo)`
Can you elaborate on that ? Does nvim jdtls support adding custom actions to the list of available ones ? Or do you mean that once adding favourite static members, this action will become available ?

**Comment by mfussenegger** [comment]
> If i decide to dynamically put the current project's root package inside favourite static members, would jdtls recognize / search for static imports from the project itself as well ?

I think so, yes.

> Does nvim jdtls support adding custom actions to the list of available ones ? 

No

> Or do you mean that once adding favourite static members, this action will become available ?

Converting `ClassName.staticMethod(..)` to `staticMethod(...)` should always work, even if it's not within the favorite static members.

https://user-images.githubusercontent.com/38700/183304693-9c82dd29-2403-4252-a875-811433bf345c.mp4

**Comment by DasGandlaf** [comment]
Is there still no way to static import methods, without adding favoritestaticmembers? If it could work like in IntelliJ, that'd be awesome (I know they use a different language server)

**Comment by DasGandlaf** [comment]
FYI, I opened an issue on the repo from the LS:https://github.com/eclipse/eclipse.jdt.ls/issues/2445
