### ISSUE TITLE
Question!?

### ISSUE THREAD

**Issue by MurdeRMelodY** [mfussenegger/nvim-jdtls#32]
Does nvim-jdtls have an "on_attach" property ?

**Comment by mfussenegger** [comment]
Yes it does.

From the readme:

> The argument passed to start_or_attach is the same config mentioned in :help vim.lsp.start_client.

`:help vim.lsp.start_client` lists the `on_attach` property.

**Comment by MurdeRMelodY** [comment]
augroup nvim-jdtls
      autocmd!
      autocmd FileType java lua require("jdtls").start_or_attach({on_attach = on_attach, cmd = {"java-lsp.sh"}})
    augroup end
Here's a snippet of my config. Do you have any idea what I'm doing wrong?

**Comment by mfussenegger** [comment]
> Do you have any idea what I'm doing wrong?

Looks okay. What's the problem?

**Comment by MurdeRMelodY** [comment]
the on_attach function doesn't trigger. I set my keymaps in the function.

**Comment by mfussenegger** [comment]
> the on_attach function doesn't trigger. I set my keymaps in the function.

It could be that there is an error in your `on_attach` function. You could try invoking it manually using something like `:lua require('your-module-name').your_attach_function()` 

If you make use of the `client` or `bufnr` arguments:

- You can get the client from `vim.lsp.get_active_clients()`, it returns a list, so maybe use `vim.lsp.get_active_clients()[1]`
- You can get the bufnr for the current buffer using `vim.api.nvim_get_current_buf()`


So all together: `:lua require('your-module-name').your_attach_function(vim.lsp.get_active_clients()[1], vim.api.nvim_get_current_buf())`

**Comment by MurdeRMelodY** [comment]
ok, thanks for your help!
