### ISSUE TITLE
Javadoc highlight

### ISSUE THREAD

**Issue by leaxoy** [mfussenegger/nvim-jdtls#333]
### Problem Statement

In both vscode-java and coc-java, javadoc highlight different from regular document colors.
In vscode-java:
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/8556349/192585235-a72a0fe1-1650-4cce-a541-6ebdd6862324.png">
and in coc-java:
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/8556349/192585506-661f622e-0d7a-4067-9944-2ee4a3b94c84.png">
but in nvim-jdtls:
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/8556349/192585601-9687ed4d-2a59-477d-927b-2ddc2f0d2b5c.png">

**Comment by mfussenegger** [comment]
Neovim doesn't support syntax highlighting via semantic tokens yet. This is an upstream issue, nvim-jdtls only takes care of off-spec extensions, not of the core stuff.
