### ISSUE TITLE
support Navigate to the super implementation

### ISSUE THREAD

**Issue by fengwk** [mfussenegger/nvim-jdtls#347]
### Problem Statement

support Navigate to the super implementation. I see that jdtls already supports this capability. Can it be extended in plug-ins.

[Navigate to the super implementation #1165](https://github.com/eclipse/eclipse.jdt.ls/pull/1165)

**Comment by mfussenegger** [comment]
Added a `super_implementation` method in https://github.com/mfussenegger/nvim-jdtls/pull/348

**Comment by fengwk** [comment]
tanks 😁

**Comment by fengwk** [comment]
[support multi clients](https://github.com/mfussenegger/nvim-jdtls/pull/350)
