### ISSUE TITLE
Unable to launch the script while opening a new java file

### ISSUE THREAD

**Issue by TV12mac** [mfussenegger/nvim-jdtls#36]
I have setup jdtls and the launch script, both are working. When I try to open a file (nvim test.java for an example). The following error is given below 
``
E5108: Error executing lua ...than/.config/nvim/plugged/nvim-jdtls/lua/jdtls/setup.lua:63: LSP cmd must be an executable: ~/jdtls_launch.sh
``
To my knowledge I followed what was stated in the README. For some reason it isn't working now.

Expected behaviour: No errors and jdtls to be working properly.

**Comment by mfussenegger** [comment]
I think the problem is that the path isn't expanded automatically, so `~/jdtls_launch.sh` is literally `~/jdtls_launch.sh` and not `/home/<user>/jdtls_launch.sh` or something like that.

You could use the `vim.fn.expand('~/jdtls_launch.sh')` to get the full path.

**Comment by TV12mac** [comment]
Alright that works. Thanks a lot
