### ISSUE TITLE
Failed to run the plugin

### ISSUE THREAD

**Issue by peleusj** [mfussenegger/nvim-jdtls#37]
Hi, I cannot run the plugin successfully. 
I basically follow the introduction, i test the jdtls launch script, and it runs as example showed.
But after I add the plugin configuration, and try to open a java file, an error happens, the error message is:

```
Error detected while processing FileType Autocommands for "java":
E5108: Error executing lua /Users/albert/.vim/plugged/nvim-jdtls/lua/jdtls.lua:321: attempt to index field 'handlers' (a nil v
alue)
```
I am a little confused where goes wrong.
Thanks.

**Comment by mfussenegger** [comment]
The error is an indication that `vim.lsp.handlers` is missing which should be present if you're using a recent build of neovim.
You can check your version with `nvim --version` or you can see if `:help vim.lsp.handlers` brings anything up. If it doesn't you'll need to update your neovim.

**Comment by peleusj** [comment]
Thanks a lot, it worked now!
