### ISSUE TITLE
Run tests from another buffer/from another file.

### ISSUE THREAD

**Issue by DasGandlaf** [mfussenegger/nvim-jdtls#381]
### Problem Statement

Hey there, thanks for the plugin! It has been working great so far. And I also love the simplicity 👍

I am trying to make a mapping, which toggles automatic test running on the active buffer, whenever I save. It works, as long as I don't leave the buffer which contains the tests. When I go to the implementation, change code, and then save, it can't find the tests, because it tries to run tests in the current buffer.
If it would be possible to run tests from another buffer I could do that, but there would be a problem if I would f.e. close the test buffer. So preferably, I would like to run tests from a given file path, rather than a buffer, or something that usually stays the same. I don't know if there is already a possibility for that, but I haven't found any.

### Ideas or possible solutions

I only would have a solution for running the tests in an inactive buffer, which would be this:
(in file under: `lua/jdtls/dap.lua`)
```lua
function M.test_class(opts)
  ...
  local context = make_context() -- Change this to: `local context = opts.context or make_context()`
  ...
end
```
But I don't know if that would actually work or not.
I appreciate the help.

**Comment by mfussenegger** [comment]
Opened up https://github.com/mfussenegger/nvim-jdtls/pull/386

The first commit would add the `context` parameter to the options as you suggested, but I added another commit that instead adds the `bufnr` and `lnum` options. I think that's easier to use.

With that you should be able to do something like:


```lua
local bufnr = vim.fn.bufadd('/path/to/file/to/test')
require('jdtls').test_class({ bufnr = bufnr })
```

**Comment by DasGandlaf** [comment]
Thank you! I'll definitely be using that. I appreciate it.
