### ISSUE TITLE
test_nearest_methd() does not work with Junit5's @Nested

### ISSUE THREAD

**Issue by schrieveslaach** [mfussenegger/nvim-jdtls#401]
### LSP client configuration

https://gitlab.com/schrieveslaach/dotfiles/-/blob/34d0c43f0b71b6ff7a4f78756c4814e435d86fb5/dot_config/nvim/plugins/lsp.vim.tmpl#L59-75

### Eclipse.jdt.ls version

1.18.0

### Steps to Reproduce

Checkout the example from [here](https://github.com/bluetata/java-maven-junit5-example) and execute `require('jdtls').test_nearest_method()`, as shown below:

![output](https://user-images.githubusercontent.com/16558417/210548403-8166e3fa-f53c-4636-9867-1e3270aa4783.gif)

### Expected Result

The method within the `@Nested`  class should be executed.

### Actual Result

The method just before the `@Nested`  class has been executed.

**Comment by mfussenegger** [comment]
Should be fixed with https://github.com/mfussenegger/nvim-jdtls/pull/402

**Comment by schrieveslaach** [comment]
Works! Thank you for your quick response.

**Comment by schrieveslaach** [comment]
BTW: would it be possible to support more JUnit features? For example, `@DisplayName` to modify the test display (see [JUnit guide](https://junit.org/junit5/docs/current/user-guide/)).

**Comment by mfussenegger** [comment]
> BTW: would it be possible to support more JUnit features? For example, `@DisplayName` to modify the test display (see [JUnit guide](https://junit.org/junit5/docs/current/user-guide/)).

That would depend on https://github.com/microsoft/vscode-java-test providing the data.

Currently the commands used to discover the test cases return data like this:


```
7: table: 0x7f1015774c78
  children: table: 0x7f10156fb468
    1: table: 0x7f10156fb4b0
      fullName: com.example.junit5.test.nested.BookingServiceTest$History#history
      id: java-maven-junit5-example@com.example.junit5.test.nested.BookingServiceTest$History#history
      jdtHandler: =java-maven-junit5-example/src\/test\/java=/optional=/true=/=/maven.pomderived=/true=/=/test=/true=/<com.example.junit5.test.nested{BookingServiceTest.java[BookingServiceTest[History~history
      label: history()
      projectName: java-maven-junit5-example
      range: table: 0x7f10156fb710
        end: table: 0x7f10156fb7d8
          character: 9
          line: 74
        start: table: 0x7f10156fb758
          character: 13
          line: 72
      testKind: 0
      testLevel: 6
      uri: file:///home/user/dev/bluetata/java-maven-junit5-example/src/test/java/com/example/junit5/test/nested/BookingServiceTest.java
    2: table: 0x7f1015736a50
```
