### ISSUE TITLE
neovim cannot start client

### ISSUE THREAD

**Issue by Ralghs** [mfussenegger/nvim-jdtls#418]
### LSP client configuration

I checked the Log and found this error. I don't understand what this error means please can someone have a look and tell me how to fix this problem

`[ERROR][2023-02-09 17:52:06] .../vim/lsp/rpc.lua:733    "rpc"   "java"  "stderr"        "Unrecognized option: --add-modules=ALL-SYSTEM\nError: Could not create the Java Virtual Ma      chine.\nError: A fatal exception has occurred. Program will exit.\n"`

### Eclipse.jdt.ls version

1.5.0

### Steps to Reproduce

:LspStart
:LspLog

### Expected Result

Lsp to run

### Actual Result

Client 1 quit with exit code 1 and signal 0

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-jdtls#unrecognized-option---add-modulesall-system

**Comment by Ralghs** [comment]
so if my project uses Java 1.8 does that mean I have to move away from nvim-jdtls?

**Comment by Ralghs** [comment]
> Owner


so if my project uses Java 1.8 does that mean I have to move away from nvim-jdtls?

**Comment by mfussenegger** [comment]
eclipse.jdt.ls itself requires java 17 but I think it can still handle java 1.8 in your project if you setup runtimes and configure the language level in your project. See https://github.com/mfussenegger/nvim-jdtls#java-xy-language-features-are-not-available
