### ISSUE TITLE
Implementing Progress Support for jdtls

### ISSUE THREAD

**Issue by avinashsivaraman** [mfussenegger/nvim-jdtls#434]
### Problem Statement

Today, Progress while attaching and loading the package is provided as message which blocks the current work and we need to "Press any Key to continue". This essentially blocks us from working till all the packages are loaded. 

Please add support for https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#progress which will not block your current flow and there are lot of plugins which makes use this messages to make us more productive. 

https://github.com/j-hui/fidget.nvim

**Comment by mfussenegger** [comment]
`$/progress` support is already implemented in both neovim upstream and eclipse.jdt.ls.

See https://github.com/mfussenegger/nvim-jdtls/commit/efefcdc1087caa4466c00bf338227725eff82965

You can disable the echo messages setting `config.handlers['language/status'] = function() end`

**Comment by avinashsivaraman** [comment]
I am getting the below error message while setting the config handlers 
```
Error executing lua callback: ...ar/neovim/HEAD-982fef6_1/share/nvim/runtime/filetype.lua:20: Vim(lua):E5108: Error executing lua .config/nvim/lua/java.lua:211: attempt to index field 'handlers' (a nil value)
```
