### ISSUE TITLE
How to run for Java 8?

### ISSUE THREAD

**Issue by jakobkhansen** [mfussenegger/nvim-jdtls#44]
Hello,

I want to run the Java server with a Java 8 runtime. Changing the launch script to this and removing add-modules, add-opens does not work for me, the server crashes with exit code 13.

In coc-java, it is possible to launch the server with Java 11, but configure a different runtime, like so:

```json
"java.configuration.runtimes": [
  {
    "name": "JavaSE-1.11",
    "path": "/path/to/jdk-11",
  },
  {
    "name": "JavaSE-11",
    "path": "/path/to/jdk-11",
  },
  {
    "name": "JavaSE-14",
    "path": "/path/to/jdk-14",
    "default": true
  },
]
```
Is it possible to configure the launch script to do something similar? I'm mostly interested in getting this server to run with Java 8.

**Comment by mfussenegger** [comment]
You can configure the runtimes within the `config.settings`:

```
local config = {
  -- <here goes your normal configuration, like the cmd etc>

  settings = {
    java = {
      configuration = {
        runtimes = {
          {
            name = "JavaSE-11",
            path = "/usr/lib/jvm/java-11-openjdk/",
          }
        }
      }
    }
  },
  -- This is currently required to have the server read the settings,
  -- In a future neovim build this may no longer be required
  on_init = function(client)
    client.notify('workspace/didChangeConfiguration', { settings = client.config.settings })
  end
}
```

Keep in mind that eclipse.jdt.ls itself no longer can be launched with Java 8
but requires at least Java 11, so you must stick to that for the `java-lsp.sh`
script.

**Comment by jakobkhansen** [comment]
Thanks, that worked! Is there anywhere I can read about all these options for configuration? This is part of Neovim LSP right? I'm very new to both Lua and Neovim LSP.

**Comment by mfussenegger** [comment]
> Is there anywhere I can read about all these options for configuration? This is part of Neovim LSP right?

`:help vim.lsp.start_client` describes all options for the configuration which are specific to the LSP client in neovim.

`settings` there is table that can contain language server specific configuration:

> Map with language server specific settings. These are returned to the
> language server if requested via `workspace/configuration` . Keys are
> case-sensitive.

The available settings for `eclipse.jdt.ls` are partially documented in the [eclipse.jdt.ls wiki](https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request) 
I think the `package.json` of the vscode-java project is more complete, but unfortunately it mixes server settings and client settings together, so you can't tell for sure which is which unless you read the code :(

**Comment by jakobkhansen** [comment]
Thanks!
