### ISSUE TITLE
can not open a class

### ISSUE THREAD

**Issue by mycf** [mfussenegger/nvim-jdtls#458]
### LSP client configuration

local function get_install_path(package_name)
  return require("mason-registry").get_package(package_name):get_install_path()
end

local jdtls = require "jdtls"
local root_markers = { "gradlew", "pom.xml" }
local root_dir = require("jdtls.setup").find_root(root_markers)
local home = os.getenv "HOME"
local workspace_folder = home .. "/.local/share/eclipse/" .. vim.fn.fnamemodify(root_dir, ":p:h:t")
local config = require("custom.conf").mk_config()
config.cmd = {
  -- "/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/java", -- or '/path/to/java17_or_newer/bin/java'
  -- "/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/bin/java",
  "/usr/local/opt/openjdk@17/bin/java",
  "-Declipse.application=org.eclipse.jdt.ls.core.id1",
  "-Dosgi.bundles.defaultStartLevel=4",
  "-Declipse.product=org.eclipse.jdt.ls.core.product",
  "-Dlog.protocol=true",
  "-Dlog.level=ALL",
  "-Xms1g",
  "--add-modules=ALL-SYSTEM",
  "--add-opens",
  "java.base/java.util=ALL-UNNAMED",
  "--add-opens",
  "java.base/java.lang=ALL-UNNAMED",
  "-jar",
  vim.fn.glob(get_install_path "jdtls" .. "/plugins/org.eclipse.equinox.launcher_*.jar"),
  "-configuration",
  get_install_path "jdtls" .. "/config_mac",
  "-data",
  workspace_folder,
}

config.root_dir = require("jdtls.setup").find_root { ".git", "mvnw", "gradlew" }
config.settings = {
  java = {
    signatureHelp = { enabled = true },
    contentProvider = { preferred = "fernflower" },
    completion = {
      favoriteStaticMembers = {
        "org.hamcrest.MatcherAssert.assertThat",
        "org.hamcrest.Matchers.*",
        "org.hamcrest.CoreMatchers.*",
        "org.junit.jupiter.api.Assertions.*",
        "java.util.Objects.requireNonNull",
        "java.util.Objects.requireNonNullElse",
        "org.mockito.Mockito.*",
      },
      filteredTypes = {
        "com.sun.*",
        "io.micrometer.shaded.*",
        "java.awt.*",
        "jdk.*",
        "sun.*",
      },
    },
    sources = {
      organizeImports = {
        starThreshold = 9999,
        staticStarThreshold = 9999,
      },
    },
    codeGeneration = {
      toString = {
        template = "${object.className}{${member.name()}=${member.value}, ${otherMembers}}",
      },
      hashCodeEquals = {
        useJava7Objects = true,
      },
      useBlocks = true,
    },
    configuration = {
      runtimes = {
        {
          name = "JavaSE-11",
          path = "/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home",
        },
        {
          name = "JavaSE-1.8",
          path = "/Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home",
        },
        {

          name = "JavaSE-17",
          path = "/usr/local/opt/openjdk@17",
        },
      },
    },
  },
}

local extendedClientCapabilities = require("jdtls").extendedClientCapabilities
extendedClientCapabilities.resolveAdditionalTextEditsSupport = true

local bundles = {
  vim.fn.glob(get_install_path "java-debug-adapter" .. "/extension/server/com.microsoft.java.debug.plugin-*", true),
}
vim.list_extend(bundles, vim.split(vim.fn.glob(get_install_path "java-test" .. "/extension/server/*.jar", true), "\n"))

-- for _, value in pairs(bundles) do
--   print(value)
-- end
bundles = vim.tbl_filter(function(s)
  return not vim.endswith(s, "com.microsoft.java.test.runner-jar-with-dependencies.jar")
end, bundles) or {}
config.init_options = {
  bundles = bundles,
  extendedClientCapabilities = extendedClientCapabilities,
}
config.on_attach = function(client, bufnr)
  jdtls.setup_dap { hotcodereplace = "auto" }
  jdtls.setup.add_commands()
  local opts = { silent = true, buffer = bufnr }
  vim.keymap.set("n", "<A-o>", jdtls.organize_imports, opts)
  vim.keymap.set("n", "<leader>df", jdtls.test_class, opts)
  vim.keymap.set("n", "<leader>dn", jdtls.test_nearest_method, opts)
  vim.keymap.set("n", "crv", jdtls.extract_variable, opts)
  vim.keymap.set("v", "crm", [[<ESC><CMD>lua require('jdtls').extract_method(true)<CR>]], opts)
  vim.keymap.set("n", "crc", jdtls.extract_constant, opts)
end
-- This starts a new client & server,
-- or attaches to an existing client & server depending on the `root_dir`.
require("jdtls").start_or_attach(config)

### Steps to Reproduce

when I open a class by <c-]>
like cursor in System
<img width="535" alt="image" src="https://user-images.githubusercontent.com/36999825/229523382-1b8c365c-4fef-4546-89f0-03355c3e601d.png">

### Expected Result

open class right

### Actual Result

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/36999825/229522024-c1be7eb2-3e0e-4e07-bcb3-a926cf540cde.png">

**Comment by mfussenegger** [comment]
I can't reproduce this and a segfault is most likely an issue with neovim itself and not with this plugin.
