### ISSUE TITLE
Breakpoints not working properly

### ISSUE THREAD

**Issue by alvarosevilla95** [mfussenegger/nvim-jdtls#46]
Trying to debug a class/method on a gradle project, it works fine and shows the results on the REPL. When I set some breakpoints, the program stops on the breakpoints, but I get the following error:
```
Error retrieving stack traces: Model not available for <project>
```
The program is stopped  but I can't access any frames neither in hovers or the repl. Trying to run anything on the REPL results in the following error:
```
  1 Evaluation failed because the thread is not suspended.
```
If I type continue however, the program resumes and finshes, and does show the output on the REPL

**Comment by mfussenegger** [comment]
Any chance you could provide some sort of minimal gradle build files that would let me reproduce the problem?

If that's not possible, could you activate trace logging (`:lua require('dap').set_log_level('trace')`) and post the log contents from a debug run where you encounter the error?

**Comment by alvarosevilla95** [comment]
Unfortunately the repo I'm testing this on is private, I'll see if I can reproduce on a toy project. It's a multi project gradle repo with springboot.
I tried running with 'trace' enabled, although I didn't seem to get any TRACE log entries. Anyway here's the output, had to remove classpaths and similar:
https://gist.github.com/alvarosevilla95/988c1e0822020ffbba71e02ba8c59ea7

**Comment by mfussenegger** [comment]
Unfortunately the log doesn't give any more insights.

If you run `:JdtCompile true` (might take a while) does it return any errors?
I suspect that jdtls may have some problem with the project configuration. 
Does the lsp log contain any errors?

**Comment by alvarosevilla95** [comment]
Yeah I figured. Thanks for the suggestions though! Turns out I had some issues with my jdtls installation. Surprisingly all other lsp features were working fine... After rebuilding it debugginng is now working properly. 
And thank you for your great work with the plugin!
