### ISSUE TITLE
Show runtime path information in runtime selection

### ISSUE THREAD

**Issue by jnk22** [mfussenegger/nvim-jdtls#463]
### Problem Statement

Hi @mfussenegger, first of all, thank you for this plugin!

I have multiple Java SDKs setup in the `settings.java.configurations.runtime`, some with the same major version (19, 18, 1.8, etc.), but different minor versions, or system-wide/custom paths.

Due to the the shown `runtime.name` in the selection being based on the `enum ExecutionEnvironment` as defined in [eclipse.jdt.ls](https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request), multiple Java runtimes with the same major versions are not differentiable:

![2023-04-13_19-51](https://user-images.githubusercontent.com/24391401/231843143-41bee02d-38e8-4f49-a30a-3c74bc131ff3.png)

_(My runtimes are generated dynamically based on input paths, but this can also affect manual configuration setups where people use the same major versions multiple times.)_

### Ideas or possible solutions

I suggest to add **additional output to the runtime selection**.

A simple method would be to just show the path after the name. This attribute is required and always present as stated in the configuration guide, and also defined as required in the respective interface `RuntimeOption` on the eclipse.jdt.ls side.

### Possible solution with always showing the path

```lua
function(r)
  return r.name .. " (" .. r.path .. ")"
end,
```

**Runtime selection with Telescope UI:**
![2023-04-13_19-16](https://user-images.githubusercontent.com/24391401/231843617-b139ea65-8151-49f5-8420-2a3edb226704.png)

**Runtime selection with default view:**
![2023-04-13_19-15](https://user-images.githubusercontent.com/24391401/231843602-7b42e07e-b143-4799-802a-5c4752628d39.png)

A few more ideas for possible output:

- Only show path/additional info if `runtime.name` is ambigous
- Implement an additional field like `runtime.details`, that can show custom infos if present (could be the path, own notes, or whatever - fields would differ from `RuntimeOption` then though)
- Use other format, e.g. `JavaSE-19: /path/to/java/sdk`

I have pushed the above solution to my fork: https://github.com/jnk22/nvim-jdtls

Is this something you think would be beneficial and could be added?

**Comment by mfussenegger** [comment]
> Implement an additional field like runtime.details, that can show custom infos if present (could be the path, own notes, or whatever - fields would differ from RuntimeOption then though)

Given that these are settings sent to the server, adding additional fields is not an option.

I added the path with https://github.com/mfussenegger/nvim-jdtls/pull/465
