### ISSUE TITLE
Support change signature refactoring

### ISSUE THREAD

**Issue by gbroques** [mfussenegger/nvim-jdtls#464]
### Problem Statement

I'd like LSP support when refactoring the signature of existing methods.

vscode-java and the Eclipse JDT LS recently added support for this:
* https://github.com/redhat-developer/vscode-java/pull/2967
* https://github.com/eclipse/eclipse.jdt.ls/pull/2497

Thank you, let me know if you have any thoughts! :)

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-jdtls/pull/444

**Comment by gbroques** [comment]
> See #444

Thank you for the fast reply, and work on this great plugin @mfussenegger! :) 

Is it worth documenting this in the [README](https://github.com/mfussenegger/nvim-jdtls#extensions)?

I didn't realize support for this feature was already complete.

Also a demo GIF / mp4 showcasing this functionality would be fantastic!

Thank you again for the work on this plugin and others like [nvim-dap](https://github.com/mfussenegger/nvim-dap).

**Comment by mfussenegger** [comment]
> https://github.com/eclipse/eclipse.jdt.ls/pull/2598

Done in https://github.com/mfussenegger/nvim-jdtls/commit/aa04fc0e4d8acbfa43efc6a6f7162b01987257a1

> Also a demo GIF / mp4 showcasing this functionality would be fantastic!

The linked PR contains one.

**Comment by gbroques** [comment]
Thanks @mfussenegger! I appreciate this. :)
