### ISSUE TITLE
How to make it work (or at least know what wrong) ?

### ISSUE THREAD

**Issue by dodonut** [mfussenegger/nvim-jdtls#48]
i've installed the plugin, followed the steps, and the server does not start. How can I see any logs or errors to know what to fix?

**Comment by rakin406** [comment]
Same issue :(

**Comment by mfussenegger** [comment]
Did you see the Troubleshooting section and try to follow the steps [outlined in "vim.lsp.buf functions don't do anything"](https://github.com/mfussenegger/nvim-jdtls#vimlspbuf-functions-dont-do-anything) ?

**Comment by dodonut** [comment]
It worked! It was a problem with the run script... it did not found some dependencies.... Just run the script and see the output log error

**Comment by dodonut** [comment]
I got it, it was a problem with the script launch... which I solved by doing exactly the same folder structure as showed in this video https://www.youtube.com/watch?v=E-MvQC04Cbo&t=376s . But now, Its stuck on 
![image](https://user-images.githubusercontent.com/19748045/111386436-078a1c80-868b-11eb-8cb7-f44531b1d949.png). Any ideas?

**Comment by dodonut** [comment]
I've rebooted and now it's not starting again....
