### ISSUE TITLE
Add Command Line Arguments Prompt as part of a Default Configuration for DAP

### ISSUE THREAD

**Issue by MahboobMMonza** [mfussenegger/nvim-jdtls#487]
### Problem Statement

Currently, `nvim-jdtls`'s default DAP configuration for Main classes does not have any way to pass in command line arguments, and this issue is a request to place this as an option (e.g. `Launch yourProject : Main with command line args` in addition to the default configurations).

### Ideas or possible solutions

Add a "duplicate" configuration with the following passed in for the `args` parameter:

```lua
args = function()
    local argstr = vim.fn.input('Args: ')
    return argstr
end,
```

Provide the user with the choice between a no-args configuration and an argument-friendly configuration to run.

**Comment by mfussenegger** [comment]
You can either override/extend the configuration using the `config_overrides` option of `setup_dap_main_class_configs`. For example:


```
:lua require("jdtls.dap").setup_dap_main_class_configs( { config_overrides = { args = function() return vim.fn.input("Args: ") end } })
```

See `:help jdtls.dap.setup_dap_main_class_configs`


Or you can use `fetch_main_configs` and customize the configurations completely.
See `:help jdtls.dap.fetch_main_configs`



I won't be adding more specific custom options as the combinations that people may want explode very quickly.


I'd in general recommend to add a `.vscode/launch.json` file to a project if it's frequently launched with the same arguments or if it requires custom options.

And if the arguments frequently change you're probably better of creating test cases and debug those.

**Comment by MahboobMMonza** [comment]
Does the `launch.json` file have to be located in a `.vscode` folder?

**Comment by mfussenegger** [comment]
You can also specify the path. See `:help dap.ext.vscode.load_launchjs`

**Comment by MahboobMMonza** [comment]
Thank you

**Comment by MahboobMMonza** [comment]
Is is possible to export the current dap configs inside `nvim-jdtls` for a project as a JSON? Was hoping to use this feature to speed up creation of my own customized launchs.
