### ISSUE TITLE
Connecting to language server

### ISSUE THREAD

**Issue by PitcherTear22** [mfussenegger/nvim-jdtls#5]
coc.nvim launches jdt.ls for completion (coc-java), how do I connect to the already launched server?

**Comment by mfussenegger** [comment]
nvim-jdtls is an extension to the built-in LSP support in neovim. It won't work with coc. 

There is a PR pending in [nvim-lsp](https://github.com/neovim/nvim-lsp/pull/245) for the basic setup. Otherwise you'd need to follow the instructions in `:help lsp` on how to launch a LSP client.

**Comment by PitcherTear22** [comment]
No I meant coc would already launch the server

**Comment by mfussenegger** [comment]
> No I meant coc would already launch the server

Even if coc starts the server, nvim-jdtls won't be able to use it. The server must be started with the built-in neovim client for nvim-jdtls to work.

> So ig I can use steelsojka's fork for the time being?

yep you could. But to use the full functionality of nvim-jdtls you'll have to set some additional options, as described here https://github.com/mfussenegger/nvim-jdtls#usage

**Comment by PitcherTear22** [comment]
Thanks !!
