### ISSUE TITLE
Use vim.ui.select to choose options

### ISSUE THREAD

**Issue by IlyasYOY** [mfussenegger/nvim-jdtls#500]
### Problem Statement

Thank you for your work. 

I've been using the extension for quite some time and I faced a problem with selection dialog.

There are usages of `vim.ui.select` and `vim.fn.input,` `vim.fn.inputlist`.

I found [here](https://github.com/mfussenegger/nvim-jdtls/wiki/UI-Extensions) that
> nvim-jdtls uses `vim.ui.select`, that means plugins providing a `vim.ui.select` implementation are used.

So, is this possible to use select everywhere?  It'd make extension more compatible with the others vim plugins.

I found 2 places where input is used: 

- https://github.com/mfussenegger/nvim-jdtls/blob/master/lua/jdtls/ui.lua#L21
- https://github.com/mfussenegger/nvim-jdtls/blob/master/lua/jdtls/ui.lua#L65

### Ideas or possible solutions

Replace `input` usages with `select` where possible. Maybe you already know why it's not.

I'd be glad to propose a PR, if you think it might be useful and possible.

**Comment by mikehaertl** [comment]
Hmm, why was this closed? I'd also find this useful.

**Comment by IlyasYOY** [comment]
Hello @mikehaertl 

I thought that the issue is related to https://github.com/mfussenegger/nvim-jdtls/issues/358. I closed this as a duplicate. 

You can reopen this one, if you think that it's worthy being open.
