### ISSUE TITLE
Snippet completion for `sout` is not as expected

### ISSUE THREAD

**Issue by abshekh** [mfussenegger/nvim-jdtls#520]
### LSP client configuration

local config = {
  cmd = {"jdt-language-server", "-data", workspace_dir},
  capabilities = capabilities,
  root_dir = root_dir,

  -- Here you can configure eclipse.jdt.ls specific settings
  -- See https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request
  -- or https://github.com/redhat-developer/vscode-java#supported-vs-code-settings
  -- for a list of options
  settings = {
    java = {
      eclipse = {
        downloadSources = true,
      },
      maven = {
        downloadSources = true,
      },
      implementationsCodeLens = {
        enabled = false,
      },
      referencesCodeLens = {
        enabled = false,
      },
      references = {
        includeDecompiledSources = true,
      },
      inlayHints = {
        parameterNames = {
          enabled = "all", -- literals, all, none
        },
      },
    },
    signatureHelp = { enabled = true },
    completion = {
      enabled = true,
      -- overwrite = true,
      favoriteStaticMembers = {
        "org.hamcrest.MatcherAssert.assertThat",
        "org.hamcrest.Matchers.*",
        "org.hamcrest.CoreMatchers.*",
        "org.junit.jupiter.api.Assertions.*",
        "java.util.Objects.requireNonNull",
        "java.util.Objects.requireNonNullElse",
        "org.mockito.Mockito.*",
      },
    },
    contentProvider = { preferred = "fernflower" },
    extendedClientCapabilities = extendedClientCapabilities,
    sources = {
      organizeImports = {
        starThreshold = 9999,
        staticStarThreshold = 9999,
      },
    },
    codeGeneration = {
      toString = {
        template = "${object.className}{${member.name()}=${member.value}, ${otherMembers}}",
      },
      useBlocks = true,
    },
  },

  flags = {
    allow_incremental_sync = true,
  },

  init_options = {
    bundles = {},
  },
  handlers = {
    ['language/status'] = function() end,  
  },
}

### Eclipse.jdt.ls version

1.21.0

### Steps to Reproduce

Snippet completion for `sout`
![java_snippet](https://github.com/mfussenegger/nvim-jdtls/assets/46927550/bd481d16-eec0-4405-820e-b2e2775a3ee2)

### Expected Result

it should replace the prefix with `System.out.println()`

### Actual Result

the prefix does not get replaced and instead i get `soSystem.out.println()`

**Comment by mfussenegger** [comment]
This is an issue with your completion/snippet plugin, not nvim-jdtls
