### ISSUE TITLE
Gradle menu

### ISSUE THREAD

**Issue by sledigabel** [mfussenegger/nvim-jdtls#524]
### Problem Statement

Working mostly with gradle, I fall back to the terminal to run my tasks.
Nothing wrong with this, just wondering if you see some Gradle menu and wrappers being part of this project or a separate plugin?

### Ideas or possible solutions

Bottom line is I'd be happy to work on a PR to add some Gradle functionality, equally happy to go a write my own if you feel that's beyond the scope of this project.
Basic functionality would be to run a gradle task, perhaps selecting it thorugh telescope, and get the results in a buffer.

I found this project: https://github.com/HiPhish/gradle.nvim but it seems abandonned.

**Comment by mfussenegger** [comment]
I can't say for sure without knowing more about the planned functionality, but it does sound like something for a separate plugin. I'd like to keep the scope focused around the language server functionality and spawning gradle tasks and processing their output seems unrelated?

Is there any advantage you see in having it integrated in nvim-jdtls?

**Comment by sledigabel** [comment]
I entirely agree with you @mfussenegger my thinking is leaning towards a separate plug-in.

I wasn't sure if you had thought this plug-in more as a Swiss Army knife for Java (being such a bundled ecosystem) or rather a more advanced integration with jdtls itself so I wasn't sure where you'd see the limit of liability. The clue was in the name, but thought I'd check 😊

**Comment by mfussenegger** [comment]
> I wasn't sure if you had thought this plug-in more as a Swiss Army knife for Java (being such a bundled ecosystem) 

I tend to prefer more granular plugins. It's easier to glue some components together instead of the opposite. 

If people would want a `nvim-java`, I think an approach like the [Extension Pack for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) could work - a plugin that just bundles a couple of other plugins and glue's them together.  But that's for someone else to do
