### ISSUE TITLE
Goto definition of external libraries not working

### ISSUE THREAD

**Issue by paulkre** [mfussenegger/nvim-jdtls#532]
### LSP client configuration

```lua
nmap('gd', vim.lsp.buf.definition, '[G]oto [D]efinition')
```

### Eclipse.jdt.ls version

1.25.0

### Steps to Reproduce

When I try to access the definition of a symbol defined in an external library with `vim.lsp.buf.definition` nothing happens. It works as expected when I run the function on symbols defined in the local project.

It should be possible to reproduce this by running `gd` on the `String` class from Java's standard library.

### Expected Result

The definition of the `String` class should be opened in a new buffer.

### Actual Result

Nothing happens (not even an error).

**Comment by mfussenegger** [comment]
Works fine for me. Check the logs and troubleshooting steps

**Comment by paulkre** [comment]
Whoops I thought this was the Mason plugin. Works now, thanks!
