### ISSUE TITLE
Need to login to install vscode-java-test?

### ISSUE THREAD

**Issue by ChristianChiarulli** [mfussenegger/nvim-jdtls#55]
I saw you're thread over on the vscode-java-test repo. Were you able to resolve this issue without logging in?

**Comment by mfussenegger** [comment]
I ended up installing the bundle directly with maven, skipping the npm step altogether. Here's how that looked:

https://github.com/mfussenegger/dotfiles/commit/f465a02f6ede83e275628b3c8431d103bc532d64

**Comment by mfussenegger** [comment]
@ChristianChiarulli did this answer your question?

**Comment by ChristianChiarulli** [comment]
Sorry I have t looked at this in a while, I'd really like to address the root cause of the issue with that team so that I can build it normally. I've never run into this issue anywhere else.

**Comment by mfussenegger** [comment]
Okay, maybe you can bump up https://github.com/microsoft/vscode-java-test/issues/1153 again or see if there's already a resolution in https://github.com/npm/cli/issues/2508

I'll close this here since there isn't much more I can do about this.
