### ISSUE TITLE
Jdt timeout duration

### ISSUE THREAD

**Issue by q12321q** [mfussenegger/nvim-jdtls#56]
Hello,
I have regularly a timeout error when I try to navigate to source code that needs to be fetched from a remote location:
```
Failed to load content for uri
jdt://contents/xxxx-0.0.10.jar/com.xxxx/Xxxx.class?=tests/%5C/Users%5C/xxx%5C/.m2%5C/repository%5C/xx%5C/0.0.10%5C/xxx-0.0.10.jar=/maven.pomderived=/true=/=/maven.pomderived=/true=/=/test=/true=/=/maven.groupId=/com.xxxx=/=/maven.artifactId=/vyg-xxxx=/=/maven.version=/0.0.10=/=/maven.scope=/test=/%3Ccom.xxxxx(Xxxxx.class

Error was: 
timeout

Check the log file for errors
/Users/xxxx/.cache/nvim/lsp.log
```
If I remove the buffer with `bd!` and I have the decompiled version of the java class.
Then If I remove again the buffer and try another time I get the real source code version.

Would it be possible to increase or specify the timeout duration to fetch the jdt content?

Thanks,
q12321q

**Comment by mfussenegger** [comment]
Could you try out https://github.com/mfussenegger/nvim-jdtls/pull/57 ?

**Comment by q12321q** [comment]
@mfussenegger Thanks a lot!
It's better! I don't have the `Failed to load content for uri`.
Unfortunately I still have the disassembled version:
```
 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
```
It still works if I remove the buffer (`bd!`) though.

I suspect there's also a timeout on the jdtls service side? Do you have any idea where it could be?

I'm looking at https://github.com/eclipse/eclipse.jdt.ls/pull/986. I defined the flag `java.maven.downloadSources` but it changes nothing.

**Comment by mfussenegger** [comment]
Could you try with an even larger timeout? Something like this

```lua
require('jdtls').settings.jdt_uri_timeout_ms = 20000
```

On a quick look at the eclipse.jdt.ls sources it looks as if there are several checks on `IProgressMonitor` to see if the operation is canceled. I'm not sure if there is a timeout behind that, or if it's only related to the client canceling operations.


Is your project compiling correctly? ( `:JdtCompile true`)

**Comment by mfussenegger** [comment]
@q12321q Were you able to solve the issue?

**Comment by q12321q** [comment]
@mfussenegger kind of... I managed to make it work by increasing the timeout value in the java code of the jdtls server: https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/MavenSourceDownloader.java#L44
It's not ideal but it works. I'll open an issue on the jdtls repo to see if something can be done.

I think we can close this issue.
Thanks a lot for your work!
