### ISSUE TITLE
command for full compile

### ISSUE THREAD

**Issue by crhf** [mfussenegger/nvim-jdtls#562]
### Problem Statement

Can we have a `JdtFullCompile` command alongside `JdtCompile`? Seems that `JdtCompile` defaults to incremental build, and I have to use `JdtCompile full` to run a full compile. But I don't want to type `full` every time; would be better to have another command, so it can be auto-completed.

Also, I didn't see in the doc that `JdtCompile` defaults to incremental; I had to dig into the source to find out. So I got confused when I had removed `target/` and tried buiding again with `JdtCompile` - nothing happend. It would be good if the doc can make this clear.

### Ideas or possible solutions

- Add a `JdtFullCompile` command;
- Explain `JdtCompile` in the doc.

**Comment by mfussenegger** [comment]
You can define your own `JdtFullCompile`. I'm not adding a second command to safe typing out the parameter (which is only 1 space longer, and you can use completion). With `wildoptions+=fuzzy` even something like `:JdtCo full` works

**Comment by crhf** [comment]
Useful tip. Thanks!
