### ISSUE TITLE
Error fetching test candidates: org/eclipse/jdt/ls/core/internal/hover/JavaElementLabels

### ISSUE THREAD

**Issue by Delice0** [mfussenegger/nvim-jdtls#570]
### LSP client configuration

I'm using the default configuration from LazyVim.

### Eclipse.jdt.ls version

v1.28.0                                   

### Steps to Reproduce

go to test file and try to run test using the following:

* Run nearest test
* Run all test
* Run test

### Expected Result

I expect that the test(s) runs

### Actual Result

Error fetching test candidates: org/eclipse/jdt/ls/core/internal/hover/JavaElementLabels

**Comment by mfussenegger** [comment]
Duplicate of https://github.com/mfussenegger/nvim-jdtls/issues/565
