### ISSUE TITLE
Unable to Run Test after Updating Nvim to v0.9.4

### ISSUE THREAD

**Issue by eatgrass** [mfussenegger/nvim-jdtls#588]
### LSP client configuration

{
  cmd = {

    "/Users/mbp/Library/Java/JavaVirtualMachines/azul-17.0.8/Contents/Home/bin/java",
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-javaagent:" .. home .. "/.local/share/nvim/mason/packages/jdtls/lombok.jar",
    "-Dlog.level=ALL",
    "-Xms1g",
    "--add-modules=ALL-SYSTEM",
    "--add-opens",
    "java.base/java.util=ALL-UNNAMED",
    "--add-opens",
    "java.base/java.lang=ALL-UNNAMED",
    "-jar",
    home .. "/.local/share/nvim/mason/packages/jdtls/plugins/org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar",
    "-configuration",
    home .. "/.local/share/nvim/mason/packages/jdtls/config_mac",
    "-data",
    home .. "/.cache/jdtls/workspace/" .. project_name,
  },

  root_dir = require("jdtls.setup").find_root { ".git", "mvnw", "gradlew", "pom.xml" },
  on_attach = on_attach,
  capabilities = capabilities,
  settings = {
    java = {
      eclipse = {
        downloadSources = true,
      },
      configuration = {
        updateBuildConfiguration = "interactive",
        runtimes = {
          {
            name = "JavaSE-1.8",
            path = home .. "/Library/Java/JavaVirtualMachines/azul-1.8.0_382/Contents/Home",
          },
          {
            name = "JavaSE-17",
            path = home .. "/Library/Java/JavaVirtualMachines/azul-17.0.8/Contents/Home",
          },
        },
      },
      maven = {
        enabled = true,
        downloadSources = true,
      },
      implementationsCodeLens = {
        enabled = true,
      },
      referencesCodeLens = {
        enabled = true,
      },
      references = {
        includeDecompiledSources = true,
      },
      inlayHints = {
        parameterNames = {
          enabled = "all",
      },
      format = {
        enabled = true,
        settings = {
          url = home .. "/.config/nvim/jars/eclipse-java-google-style.xml",
        },
      },
      signatureHelp = { enabled = true },
      contentProvider = { preferred = "fernflower" },
    },
  },
  completion = {
    favoriteStaticMembers = {
      "org.hamcrest.MatcherAssert.assertThat",
      "org.hamcrest.Matchers.*",
      "org.hamcrest.CoreMatchers.*",
      "org.junit.jupiter.api.Assertions.*",
      "java.util.Objects.requireNonNull",
      "java.util.Objects.requireNonNullElse",
      "org.mockito.Mockito.*",
    },
  },
  sources = {
    organizeImports = {
      starThreshold = 9999,
      staticStarThreshold = 9999,
    },
  },
  codeGeneration = {
    toString = {
      template = "${object.className}{${member.name()}=${member.value}, ${otherMembers}}",
    },
    useBlocks = true,
  },
  init_options = {
    bundles = bundles,
    extendedClientCapabilities = extendedClientCapabilities,
  },
  flags = {
    allow_incremental_sync = true,
  },
}

### Eclipse.jdt.ls version

1.29.0

### Steps to Reproduce

1. Open the test source code.
2. run `lua require('jdtls').test_nearest_method()`.

### Expected Result

The testing method needs to be executed.

### Actual Result

The testing method encountered an error: "Error fetching test candidates: org/eclipse/jdt/ls/core/internal/hover/JavaElementLabels".

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-jdtls/issues/565, mason contains a java-debug version that's not compatible with eclipse.jdt.ls 1.28.0

Please use [the search](https://github.com/search?q=repo%3Amfussenegger%2Fnvim-jdtls+JavaElementLabels&type=issues) before opening new issues

**Comment by IlyasYOY** [comment]
Seems like it works for this version now: https://github.com/eclipse-jdtls/eclipse.jdt.ls/releases/tag/v1.31.0

![image](https://github.com/mfussenegger/nvim-jdtls/assets/18665585/a6469e75-d054-45fe-bb8f-cb5a4b9fad62)

![image](https://github.com/mfussenegger/nvim-jdtls/assets/18665585/8ef5f2cd-eb4b-4394-a23c-5b5dc735478e)
