### ISSUE TITLE
Goto definition of library class results in error and empty buffer

### ISSUE THREAD

**Issue by alimfeld** [mfussenegger/nvim-jdtls#59]
Whenever I try to goto definition of a library class (either a class in a maven dependency or the Java standard library) I get an error saying:

`Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:892: Cursor position outside buffer`

I'm then presented with an empty buffer. It seems that jdt URLs can't be opened properly. I see e.g. the following buffer URLs (with buffer being empty):
- `jdt://contents/reactive-streams-1.0.3.jar/org.reactivestreams/Publisher.class?=rxjava/%5C/home%5C/aimfeld%5C/.gradle%5C/caches%5C/modules-2%5C/files-2.1%5C/org.reactivestreams%5C/reactive-streams%5C/1.0.3%5C/d9fb7a7926ffa635b3dcaa5049fb2bfa25b3e7d0%5C/reactive-streams-1.0.3.jar=/gradle_used_by_scope=/jmh,main,test=/%3Corg.reactivestreams(Publisher.class`
- `jdt://contents/java.base/java.lang/Math.class?=rxjava/%5C/home%5C/aimfeld%5C/.sdkman%5C/candidates%5C/java%5C/11.0.10-open%5C/lib%5C/jrt-fs.jar%60java.base=/javadoc_location=/https:%5C/%5C/docs.oracle.com%5C/en%5C/java%5C/javase%5C/11%5C/docs%5C/api%5C/=/%3Cjava.lang(Math.class`

Goto definition of a Java class in the same project works flawlessly.

I'm using the latest neovim 0.5.0-dev nightly build, latest version of nvim-jdtls (master) and version 0.70.0 of jdtls.

Any idea what could be the issue here or how I best narrow it down? It seems this is related to #14.

Thanks for your support and the awesome work you put into nvim-jdtls!

**Comment by mfussenegger** [comment]
Could you try again with https://github.com/mfussenegger/nvim-jdtls/pull/57 being merged?

The language server returns an empty response if the operation is cancelled (I'm not sure yet if this is due to the timeout set by nvim-jdtls, or whether there's another timeout on the server side)

The `Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:892: Cursor position outside buffer` error is a side effect of the empty buffer and goto definition trying to jump to the position.

**Comment by alimfeld** [comment]
Thanks for the quick response. I updated and tried again. However, I still experience the same issue. Also I don't seem to run into any sort of timeout. I immediately see the error, as if neovim wouldn't know how to handle jdt URLs. Maybe I'm missing something crucial in the configuration...

**Comment by mfussenegger** [comment]
Could you try running:

```
:lua require('jdtls').open_jdt_link('jdt://contents/reactive-streams-1.0.3.jar/org.reactivestreams/Publisher.class?=rxjava/%5C/home%5C/aimfeld%5C/.gradle%5C/caches%5C/modules-2%5C/files-2.1%5C/org.reactivestreams%5C/reactive-streams%5C/1.0.3%5C/d9fb7a7926ffa635b3dcaa5049fb2bfa25b3e7d0%5C/reactive-streams-1.0.3.jar=/gradle_used_by_scope=/jmh,main,test=/%3Corg.reactivestreams(Publisher.class')
```

Does this populate the contents into the buffer?


Could you also post the output of:

```
:verbose autocmd BufReadCmd jdt://*
```

(Both commands need to be executed when you're within a java buffer)

**Comment by alimfeld** [comment]
This does indeed populate my buffer with the content of the Publisher class!

This is the output of the autocmd:
```
:verbose autocmd BufReadCmd jdt://*
--- Autocommands ---
BufReadCmd
    jdt://*   call jdtls#FileUrlEdit(expand("<amatch>"))
        Last set from ~/.local/share/nvim/site/pack/plugins/start/nvim-jdtls/plugin/nvim_jdtls.vim line 6
```

**Comment by mfussenegger** [comment]
Do you have anything related to `'eventignore'` configured or have something setup with `noautocmd` ?

Given that calling `:lua require('jdtls').open_jdt_link` directly works, it looks as if the `BufReadCmd` event is not fired, although it's correctly defined.

**Comment by alimfeld** [comment]
No, I have no such configurations.

I increased the verbosity to 15 and set a vfile just before I did the 'goto definition'. This is what I see in the log:

```
Executing BufReadCmd Autocommands for "jdt://*"
autocommand lua require('jdtls').open_jdt_link(vim.fn.expand('<amatch>'))

Executing: lua require('jdtls').open_jdt_link(vim.fn.expand('<amatch>'))
Exception thrown: Vim(lua):E5108: Error executing lua ...re/nvim/site/pack/plugins/start/nvim-jdtls/lua/jdtls.lua:855: Must have a buffer open with a language client connected to eclipse.jdt.ls to load JDT URI

Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:892: Cursor position outside buffer
```

**Comment by mfussenegger** [comment]
The error here is interesting:

```
Exception thrown: Vim(lua):E5108: Error executing lua ...re/nvim/site/pack/plugins/start/nvim-jdtls/lua/jdtls.lua:855: Must have a buffer open with a language client connected to eclipse.jdt.ls to load JDT URI
```

It cannot find the lsp client which is connected to eclipse.jdt.ls. 
Maybe because your current buffer becomes unloaded and there is no other buffer open with the java filetype?

Could you try out https://github.com/mfussenegger/nvim-jdtls/pull/61 ? It makes the client resolving logic a less restrictive.

**Comment by alimfeld** [comment]
Great! I switched to the branch and now the jdt URLs open properly. Many thanks for the support!

**Comment by mfussenegger** [comment]
Glad we could figure this out :)
