### ISSUE TITLE
Show message on status bar

### ISSUE THREAD

**Issue by eeeXun** [mfussenegger/nvim-jdtls#595]
### Problem Statement

Display the message of loading jdtls or downloading package to status bar instead of command-line.

### Ideas or possible solutions

In [nvim-metals config example](https://github.com/scalameta/nvim-metals/discussions/39#discussion-82302). It provides `statusBarProvider` to change the settings. Then I can use `g:metals_status` to show the message on status bar.

**Comment by mfussenegger** [comment]
You can disable the loading messages in the command-line by overriding the handler:

```lua
config.handlers['language/status'] = function() end
```

To get the messages in the statusline, you can use the `vim.lsp.status()` function if you're on nightly/0.10, for 0.9 or earlier you have to write a bit of [custom logic](https://zignar.net/2022/01/21/a-boring-statusline-for-neovim/#language-server-status-or-filename) or use a statusline plugin which provides something out of the box.
