### ISSUE TITLE
Documentation? How to use?

### ISSUE THREAD

**Issue by HiPhish** [mfussenegger/nvim-jdtls#6]
Hello,

I'm trying to use your plugin, but I cannot figure out how to hook it all up. I have my own jdt.lsp config (since there is no official configuration yet), so I can set up the server like this:

~~~lua
nvim_lsp.jdt_ls.setup {
	on_attach = require'completion'.on_attach,
}
~~~

Simple enough. So where do I hook up your plugin? I have the following:

~~~lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.codeAction = {
	dynamicRegistration = false;
	codeActionLiteralSupport = {
		codeActionKind = {
			valueSet = {
				"source.generate.toString",
				"source.generate.hashCodeEquals"
			};
		};
	};
}

nvim_lsp.jdt_ls.setup {
	capabilities = capabilities,
	init_options = {
		extendedCapabilities = require('jdtls').extendedClientCapabilities,
	},
	on_attach = require'completion'.on_attach,
}
~~~

This *seems* to work, I can for example execute `:lua require'jdtls'.code_action()` and I get a working menu of code actions. However, if I select the action with `:lua vim.lsp.buf.code_action` the same actions don't work. Why is that? I thought all the client did was pass the selection to the server, but event something simple like extracting a variable to a field does not work with the built-in code actions. Did I set up my server right?

And two more related questions:
- How do you jump into a class file like in one of your GIFs?
- You are getting feedback as your server is starting up. How did you do that? I always have to listen to my computer's fans to know when it's ready.

**Comment by mfussenegger** [comment]
> This seems to work, I can for example execute :lua require'jdtls'.code_action() and I get a working menu of code actions. However, if I select the action with :lua vim.lsp.buf.code_action the same actions don't work. Why is that? I thought all the client did was pass the selection to the server, but event something simple like extracting a variable to a field does not work with the built-in code actions. Did I set up my server right?


`eclipse.jdt.ls` sends custom commands to the client as response to the `code_action` request. These are not part of the standard and the client needs to know how to handle them. The built-in `vim.lsp.buf.code_action` currently doesn't know how to do that, but if you use `require'jdtls'.code_action()` it does. [This issue](https://github.com/neovim/neovim/issues/12326) explains the problem a bit more. I haven't gotten around to propose a patch for the commands extension.

> How do you jump into a class file like in one of your GIFs?

This should work with your setup already if you use `vim.lsp.buf.definition()`
Although it will only work to jump into the first class. If you want to be able to jump from a class-file to another class-file you'd need to make sure that `jdt://` buffers also get attached to the lsp-client. I use something like this for it:


```lua
  if vim.startswith(bufname, 'jdt://') then
    if attach_to_active_buf(bufnr) then
      return
    end
  end
```

```lua
local function attach_to_active_buf(bufnr)
  local client
  for _, buf in pairs(vim.fn.getbufinfo({bufloaded=true})) do
    if api.nvim_buf_get_option(buf.bufnr, 'filetype') == 'java' then
      local clients = vim.lsp.buf_get_clients(buf.bufnr)
      if #clients > 0 then
        client = clients[1]
        break
      end
    end
  end
  if not client then
    print('No active LSP client found to use for jdt:// document')
    return false
  end
  lsp.buf_attach_client(bufnr, client.id)
  return true
```

(See https://github.com/mfussenegger/dotfiles/blob/b9def3f0023196877b449c02c148dee8697bb7a8/vim/.config/nvim/lua/lsp-config.lua#L165-L169)


> You are getting feedback as your server is starting up. How did you do that? I always have to listen to my computer's fans to know when it's ready.

Oh, that's another special callback. It's currently in my dotfiles but I should probably move it into this plugin as well:

```lua
local lsp4j_status_callback = vim.schedule_wrap(function(_, _, result)
  api.nvim_command(string.format(':echohl Function | echo "%s" | echohl None', result.message))
end)
config['callbacks']["language/status"] = lsp4j_status_callback
```



I know that the setup is currently a bit difficult - it's something I want to make easier, but given that it works for me I've been lazy about it :)

**Comment by HiPhish** [comment]
> I know that the setup is currently a bit difficult - it's something I want to make easier, but given that it works for me I've been lazy about it :)

I don't mind difficulty, my problem is when I don't know where to start. Maybe I'm just stupid, but I need a high-level overview of how things fit together before I can understand the details. When it comes to LSP all I can find is either the highest-level overview (what is LSP and why do we need it), or the detailed reference documentation. Other people like you seem to get it, so there must be something I'm missing.

> `eclipse.jdt.ls` sends custom commands to the client as response to the `code_action` request. These are not part of the standard and the client needs to know how to handle them.

I'm still not sure I understand. When I request code actions (`vim.lsp.buf.code_actions()`) Neovim issues a request to the server and the server responds with a list of supported actions. Then I select "organize import" and then something weird happens?

> This should work with your setup already if you use `vim.lsp.buf.definition()`

It only works if I have the source of the class (i.e. classes I have written myself). If I position my cursor on top of a standard class and call that function nothing happens.

> Oh, that's another special callback. It's currently in my dotfiles but I should probably move it into this plugin as well:

I see, I can register custom callbacks for when the server sends certain notifications to the client. That's pretty useful to know.

**Comment by HiPhish** [comment]
Here is also my jdt.ls configuration, maybe I have set it up incorrectly. Saved as a `.txt` file because GitHub does not allow me to upload Lua files.

[jdt_ls.txt](https://github.com/mfussenegger/nvim-jdtls/files/4950030/jdt_ls.txt)

**Comment by mfussenegger** [comment]
> Here is also my jdt.ls configuration, maybe I have set it up incorrectly. Saved as a `.txt` file because GitHub does not allow me to upload Lua files.
> 
> [jdt_ls.txt](https://github.com/mfussenegger/nvim-jdtls/files/4950030/jdt_ls.txt)


It looks like the `init_options` part that you [mentioned](https://github.com/mfussenegger/nvim-jdtls/issues/6#issue-661020066) is missing?

```
init_options = {
		extendedCapabilities = require('jdtls').extendedClientCapabilities,
	},
```

That's one of the important pieces to opt-in to the extensions that this plugin provides.



> I'm still not sure I understand. When I request code actions (vim.lsp.buf.code_actions()) Neovim issues a request to the server and the server responds with a list of supported actions. Then I select "organize import" and then something weird happens?

If you invoke `vim.lsp.buf.code_actions` the client ask the server to send a list of code-actions. Each code-action has associated some kind of action. The built-in callback to `vim.lsp.buf.code_actions` can only handle two types of actions: applying a `WorkspaceEdit` or sending a `command` to the server (which in turn, should then tell the client what to do).

If you use `require'jdtls'.code_action()` the same thing happens. It requests the code-actions from the server. But it uses a different callback or request-handler which additionally knows that it must handle certain commands on the client directly.

Currently `require'jdtls'.code_action()` is a superset of `vim.lsp.buf.code_actions()`, so you can use it as a full replacement (also for non-jdtls language servers)

I plan to upstream some logic so that in the future one can use `vim.lsp.buf.code_actions()` in all cases.

**Comment by HiPhish** [comment]
> It looks like the `init_options` part that you [mentioned](https://github.com/mfussenegger/nvim-jdtls/issues/6#issue-661020066) is missing?

Ah yes, I forgot to mention I have a two-layered configuration. The first layer is the file I attached above, which only uses vanilla features. Then when I actually set up the server I add the features from your plugin:

~~~lua
local nvim_lsp = require 'nvim_lsp'
local api = vim.api

require 'lsp_config/jdt_ls'  -- My vanilla configuration
local jdt_ls_extra = require 'jdtls'
local jdt_ls_capabilities = require'nvim_lsp/configs'.jdt_ls.capabilities

local lsp4j_status_callback = vim.schedule_wrap(function(_, _, result)
	api.nvim_command(string.format(':echohl function | echo "%s" | echohl none', result.message))
end)

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textdocument.codeaction = {
	dynamicregistration = false;
	codeactionliteralsupport = {
		codeactionkind = {
			valueset = {
				"source.generate.tostring",
				"source.generate.hashcodeequals"
			};
		};
	};
}

nvim_lsp.jdt_ls.setup {
	capabilities = capabilities,
	init_options = {
		extendedCapabilities = require('jdtls').extendedClientCapabilities,
	},
	callbacks = {
		['language/status'] = lsp4j_status_callback
	},
	on_attach = require'completion'.on_attach,
}

~~~

**Comment by HiPhish** [comment]
> If you use `require'jdtls'.code_action()` the same thing happens. It requests the code-actions from the server. But it uses a different callback or request-handler which additionally knows that it must handle certain commands on the client directly.

Let's see if I understand the difference between renaming a symbol and organizing imports. Both are actions which change the buffers, but only one of them works out of the box.

So if I use `vim.lsp.buf.rename()` the client sends a message to the server like "rename this symbol to that", the server figures out which changes need to be made, sends the places back to the client and the client then updates the buffers. The server does not change any source code. If I select the code action to organize my imports, then the server does a similar thing and tells the client what changes to make, but the built-in client does not know what the message from the server means. Is that correct? And what your plugin does is register a handler for that non-standard message from the server.

**Comment by mfussenegger** [comment]
I can't spot a mistake in your configs.

Could you post the output of 

```
:lua print(vim.inspect(vim.lsp.buf_get_clients()))
```


>  If I select the code action to organize my imports, then the server does a similar thing and tells the client what changes to make, but the built-in client does not know what the message from the server means. Is that correct? And what your plugin does is register a handler for that non-standard message from the server.

Yes.
In the organize-imports case it will also offer choices in case imports are ambigious. This is an extra step that the client (and this plugin) implements.

**Comment by HiPhish** [comment]
> Could you post the output of
> 
> ```
> :lua print(vim.inspect(vim.lsp.buf_get_clients()))
> ```
Sure.

```lua
{ {
    _on_attach = <function 1>,
    callbacks = <1>{
      ["language/status"] = <function 2>,
      ["window/logMessage"] = <function 3>,
      ["window/showMessage"] = <function 4>,
      ["workspace/configuration"] = <function 5>,
      <metatable> = <2>{
        __tostring = <function 6>
      }
    },
    cancel_request = <function 7>,
    config = {
      _on_attach = <function 8>,
      callbacks = <table 1>,
      capabilities = {
        callHierarchy = {
          dynamicRegistration = false,
          <metatable> = <table 2>
        },
        offsetEncoding = { "utf-8", "utf-16" },
        textDocument = {
          codeAction = {
            codeActionLiteralSupport = {
              codeActionKind = {
                valueSet = { "source.generate.toString", "source.generate.hashCodeEquals" },
                <metatable> = <table 2>
              },
              <metatable> = <table 2>
            },
            dynamicRegistration = false,
            <metatable> = <table 2>
          },
          completion = {
            completionItem = {
              commitCharactersSupport = false,
              deprecatedSupport = false,
              documentationFormat = { "markdown", "plaintext" },
              preselectSupport = false,
              snippetSupport = true,
              <metatable> = <table 2>
            },
            completionItemKind = {
              valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },
              <metatable> = <table 2>
            },
            contextSupport = false,
            dynamicRegistration = false,
            <metatable> = <table 2>
          },
          declaration = {
            linkSupport = true,
            <metatable> = <table 2>
          },
          definition = {
            linkSupport = true,
            <metatable> = <table 2>
          },
          documentHighlight = {
            dynamicRegistration = false,
            <metatable> = <table 2>
          },
          documentSymbol = {
            dynamicRegistration = false,
            hierarchicalDocumentSymbolSupport = true,
            symbolKind = {
              valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },
              <metatable> = <table 2>
            },
            <metatable> = <table 2>
          },
          hover = {
            contentFormat = { "markdown", "plaintext" },
            dynamicRegistration = false,
            <metatable> = <table 2>
          },
          implementation = {
            linkSupport = true,
            <metatable> = <table 2>
          },
          references = {
            dynamicRegistration = false,
            <metatable> = <table 2>
          },
          signatureHelp = {
            dynamicRegistration = false,
            signatureInformation = {
              documentationFormat = { "markdown", "plaintext" },
              <metatable> = <table 2>
            },
            <metatable> = <table 2>
          },
          synchronization = {
            didSave = true,
            dynamicRegistration = false,
            willSave = false,
            willSaveWaitUntil = false,
            <metatable> = <table 2>
          },
          typeDefinition = {
            linkSupport = true,
            <metatable> = <table 2>
          },
          <metatable> = <table 2>
        },
        workspace = {
          applyEdit = true,
          configuration = true,
          symbol = {
            dynamicRegistration = false,
            hierarchicalWorkspaceSymbolSupport = true,
            symbolKind = {
              valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },
              <metatable> = <table 2>
            },
            <metatable> = <table 2>
          },
          <metatable> = <table 2>
        },
        <metatable> = <table 2>
      },
      cmd = { "java", "-Declipse.application=org.eclipse.jdt.ls.core.id1", "-Dosgi.bundles.defaultStartLevel=4", "-Declipse.product
=org.eclipse.jdt.ls.core.product", "-Dlog.level=ALL", "-noverify", "-Xmx1G", "-jar", "/home/hiphish/.bin/eclipse.jdt.ls/plugins/
org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar", "-configuration", "/home/hiphish/.bin/eclipse.jdt.ls/config_linux", "-
data", "/home/hiphish/.local/share/eclipse/workspace/gradle.nvim", "--add-modules=ALL-SYSTEM", "--add-opens", "java.base/java.ut
il=ALL-UNNAMED", "--add-opens", "java.base/java.lang=ALL-UNNAMED" },
      filetypes = { "java" },
      init_options = {
        extendedCapabilities = {
          advancedExtractRefactoringSupport = true,
          advancedOrganizeImportsSupport = true,
          classFileContentsSupport = true,
          generateConstructorsPromptSupport = true,
          generateDelegateMethodsPromptSupport = true,
          generateToStringPromptSupport = true,
          hashCodeEqualsPromptSupport = true,
          <metatable> = <table 2>
        },
        <metatable> = <table 2>
      },
      log_level = 2,
      message_level = 2,
      name = "jdt_ls",
      on_attach = <function 9>,
      on_exit = <function 10>,
      on_init = <function 11>,
      root_dir = "/home/hiphish/Developer/vim/gradle.nvim",
      settings = {},
      <metatable> = <table 2>
    },
    id = 1,
    initialized = true,
    is_stopped = <function 12>,
    name = "jdt_ls",
    notify = <function 13>,
    offset_encoding = "utf-16",
    request = <function 14>,
    resolved_capabilities = {
      call_hierarchy = true,
      code_action = true,
      declaration = false,
      document_formatting = true,
      document_highlight = true,
      document_range_formatting = true,
      document_symbol = true,
      find_references = true,
      goto_definition = true,
      hover = true,
      implementation = true,
      signature_help = true,
      signature_help_trigger_characters = <3>{ "(" },
      text_document_did_change = 2,
      text_document_open_close = true,
      text_document_save = <4>{
        includeText = true
      },
      text_document_save_include_text = true,
      text_document_will_save = false,
      text_document_will_save_wait_until = false,
      type_definition = true,
      workspace_symbol = true
    },
    rpc = {
      handle = <userdata 1>,
      notify = <function 15>,
      pid = 51929,
      request = <function 16>
    },
    server_capabilities = {
      callHierarchyProvider = true,
      codeActionProvider = true,
      codeLensProvider = {
        resolveProvider = true
      },
      completionProvider = {
        resolveProvider = true,
        triggerCharacters = { ".", "@", "#", "*" }
      },
      definitionProvider = true,
      documentFormattingProvider = true,
      documentHighlightProvider = true,
      documentOnTypeFormattingProvider = {
        firstTriggerCharacter = ";",
        moreTriggerCharacter = { "\n", "}" }
      },
      documentRangeFormattingProvider = true,
      documentSymbolProvider = true,
      executeCommandProvider = {
        commands = { "java.edit.organizeImports", "java.project.getSettings", "java.project.refreshDiagnostics", "java.project.upda
teSourceAttachment", "java.project.removeFromSourcePath", "java.project.listSourcePaths", "java.project.isTestFile", "java.project.
getClasspaths", "java.project.resolveSourceAttachment", "java.project.addToSourcePath" }
      },
      foldingRangeProvider = true,
      hoverProvider = true,
      implementationProvider = true,
      referencesProvider = true,
      renameProvider = {
        prepareProvider = true
      },
      selectionRangeProvider = true,
      signatureHelpProvider = {
        triggerCharacters = <table 3>
      },
      textDocumentSync = {
        change = 2,
        openClose = true,
        save = <table 4>
      },
      typeDefinitionProvider = true,
      workspace = {
        workspaceFolders = {
          changeNotifications = true,
          supported = true
        }
      },
      workspaceSymbolProvider = true
    },
    stop = <function 17>,
    workspace_did_change_configuration = <function 18>,
    <metatable> = {
      __index = <function 19>
    }
  } }

```

**Comment by mfussenegger** [comment]
I think `extendedCapabilities` is wrong and needs to be `extendedClientCapabilities`:

```
extendedClientCapabilities = {
          advancedExtractRefactoringSupport = true,
          advancedOrganizeImportsSupport = true,
          classFileContentsSupport = true,
          generateConstructorsPromptSupport = true,
          generateDelegateMethodsPromptSupport = true,
          generateToStringPromptSupport = true,
          hashCodeEqualsPromptSupport = true,
        },
```

Instead of 

```
extendedCapabilities = {
          advancedExtractRefactoringSupport = true,
          advancedOrganizeImportsSupport = true,
          classFileContentsSupport = true,
          generateConstructorsPromptSupport = true,
          generateDelegateMethodsPromptSupport = true,
          generateToStringPromptSupport = true,
          hashCodeEqualsPromptSupport = true,
        },
```

**Comment by HiPhish** [comment]
OK, that was a step into the right direction. Now I get an error:

```
Error executing vim.schedule lua callback: ...nvim.a27Oxhy/usr/share/nvim/runtime/lua/vim/lsp/util.lua:548: Cursor position outside buffer
```

A new buffer opens with the following contents:

```
Failed to load contents for uri
jdt://contents/java.base/java.util/Map.class?=gradle.nvim/%5C/home%5C/hiphish%5C/.dotfiles%5C/java-stuff%5C/store%5C/jdk-11.0.6+10%5C/lib%5C/jrt-fs.jar%60java.base=/javadoc_location=/https:%5C/%5C/docs.oracle.com%5C/en%5C/java%5C/javase%5C/11%5C/docs%5C/api%5C/=/%3Cjava.util(Map.class
```

When I go back (`ctrl-o`) and repeat the process I get a different error:

```
Error executing vim.schedule lua callback: ...nvim.a27Oxhy/usr/share/nvim/runtime/lua/vim/lsp/util.lua:543: Vim(call):E5108: Error executing lua ....local/share/nvim/site-packages/nvim-jdtls/lua/jdtls.lua:583: Vim(lua):E5108: Error executing lua .../share/nvim/sit
e-packages/nvim-lsp/lua/nvim_lsp/util.lua:131: bad argument #1 to 'fs_stat' (string expected, got function)
```

**Comment by mfussenegger** [comment]
Which nvim version are you  using? You'll need a fairly recent nightly build

**Comment by HiPhish** [comment]
I have `NVIM v0.5.0-595-g08efa7037`

**Comment by HiPhish** [comment]
I just tried the latest appimage build `NVIM v0.5.0-607-g459800db4` and the same thing happens. I am on GNU/Linux Kubuntu 20.04 if it matters.

**Comment by mfussenegger** [comment]
Oh, the error is actually raised from nvim-lsp (https://github.com/neovim/nvim-lsp/blob/master/lua/nvim_lsp/util.lua#L131)

It tries to call `fs_stat` on the `jdt://...` uri.
Maybe this is because of your `root_dir` function. You could add some logic there that if the fname starts with `jdt://` it should instead try to get the root-dir from an active client. Something like this (untested):

``lua
local function root_dir(fname)
  if vim.startswith(fname, 'jdt://') then
    for _, client in ipairs(vim.lsp.buf_get_clients()) do
      if client.config.name == 'jdt.ls' then
        return client.config.root_dir
      end
    end
  end
  return nvim_lsp.util.find_git_ancestor(fname)
    or util.root_pattern('build.gradle')
    or util.root_pattern('pom.xml')
    or util.root_pattern('build.xml')
    or vim.call('getcwd')
end
```

**Comment by HiPhish** [comment]
No, I get the same error. (I did change the name to `jdt_ls`)

**Comment by mfussenegger** [comment]
Looks like I'll have to take a closer look at what exactly of nvim-lsp gets in the way.

In the meantime you could change `classFileContentsSupport = true,` to `false` (it is part of the extendedClientCapabilities) to opt-out of `jdt://` urls. So you could at least make use of the other functionality. But you also won't be able to open class files.

**Comment by HiPhish** [comment]
> But you also won't be able to open class files.

Good enough for the time being.

**Comment by PitcherTear22** [comment]
Do I need to download the lsp separately? (can't find it in this plugin)
Where do I have to place it?

**Comment by mfussenegger** [comment]
I extended the readme a bit and also added some convenience methods to make the setup easier. See https://github.com/mfussenegger/nvim-jdtls/pull/7

**Comment by p00f** [comment]
Hey!
Instead of building it manually, i used this aur package https://aur.archlinux.org/packages/jdtls/

For the `config_linux` folder, i copied `/usr/share/java/jdtls/config_linux` to `$HOME/.jdtls_config` and used that as the `configuration` argument in the script

So my `~/.local/bin/jdtls_launcher.sh` looks like this now
```sh
#!/usr/bin/env bash

JAR="/usr/share/java/jdtls/plugins/org.eclipse.equinox.launcher_*.jar"
GRADLE_HOME=$HOME/gradle /usr/lib/jvm/java-14-openjdk/bin/java \
  -Declipse.application=org.eclipse.jdt.ls.core.id1 \
  -Dosgi.bundles.defaultStartLevel=4 \
  -Declipse.product=org.eclipse.jdt.ls.core.product \
  -Dlog.protocol=true \
  -Dlog.level=ALL \
  -Xms1g \
  -Xmx2G \
  -jar $(echo "$JAR") \
  -configuration "$HOME/.jdtls_config" \
  -data "$HOME/workspace" \
  --add-modules=ALL-SYSTEM \
  --add-opens java.base/java.util=ALL-UNNAMED \
  --add-opens java.base/java.lang=ALL-UNNAMED
```

The lsp works, I just wanted to ask if copying the `config_linux` folder was the proper way to do it

**Comment by mfussenegger** [comment]
I think you could change `-configuration ` to point to `/usr/share/java/jdtls/config_linux` directly. I have mine pointed to the one in the local git repo, and the repository is not dirty, so I assume that it's read-only and isn't used for writing configuration changes.

Glad to hear that it works

**Comment by p00f** [comment]
Can I just use the included launcher? https://aur.archlinux.org/cgit/aur.git/tree/launcher.sh?h=jdtls

**Comment by p00f** [comment]
It doesn't start if I do that

**Comment by p00f** [comment]
The package has a launcher included, https://aur.archlinux.org/cgit/aur.git/tree/launcher.sh?h=jdtls, which copies `/usr/share/java/jdtls/config_linux` to a temp directory and deletes the temp directory on exit


In case you are just listing the default arguments to be more explicit, can I use the included launcher?

**Comment by p00f** [comment]
That is
```vim
if has('nvim-0.5')
  packadd nvim-jdtls
  lua jdtls = require('jdtls')
  augroup lsp
    au!
    au FileType java lua jdtls.start_or_attach({cmd={'jdtls'}})
"cmd={'jdtls'} runs /usr/bin/jdtls which is the aforementioned launcher
  augroup end
endif
```

**Comment by p00f** [comment]
Can you please change `jdtls` to something else? It conflicts with https://github.com/neovim/nvim-lspconfig/blob/master/lua/nvim_lsp/jdtls.lua

**Comment by mfussenegger** [comment]
> Can you please change `jdtls` to something else? It conflicts with https://github.com/neovim/nvim-lspconfig/blob/master/lua/nvim_lsp/jdtls.lua

Isn't that namespaced into `nvim_lsp`? You access it via `nvim_lsp.jdtls`, not on top level. I'm not sure I understand how it's conflicting?

> can I use the included launcher?

yep if it works I don't see a reason why you shouldn't be able to.

**Comment by p00f** [comment]
my misunderstanding, sorry

**Comment by p00f** [comment]
> yep if it works I don't see a reason why you shouldn't be able to.
thanks

**Comment by HiPhish** [comment]
> I extended the readme a bit and also added some convenience methods to make the setup easier.

That's nice, but I think you overdid it by adding information about compiling and setting up the language server. I think people should first get the language server to work on its own (using either nvim-lspconfig or one's own configuration) and then add this plugin on top of that. I think having a bullet point list of links to direct people should be good enough.

> Using the new `start_or_attach` method should also make sure that navigating to classes from dependencies works.

Cool, I'll have to give it a try.

**Comment by p00f** [comment]
Hey can you try again with a clean build of neovim master + jdtls ? It doesn't work after I reinstalled arch yesterday

**Comment by mfussenegger** [comment]
> Hey can you try again with a clean build of neovim master + jdtls ? It doesn't work after I reinstalled arch yesterday

For me it works with the latest neovim builds.

Can you elaborate what "doesn't work" means? Are there any errors? What's the behavior you see? What's the behavior you expect?

**Comment by p00f** [comment]
Syntax is off, server doesn't start and i can't save without overriding using `w!`

**Comment by mfussenegger** [comment]
> Syntax is off, server doesn't start and i can't save without overriding using `w!`

Do you get an error messages or see anything in `:messages` after a manual `:set ft=java` ?

**Comment by p00f** [comment]
Ok so i did this again, now syntax is on but the other problems remain.

when i `:set ft=java`, tree-sitter highlighting is applied (earlier it was vim's inbuilt highlighting)

(without `nvim-jdtls`, tree-sitter highlighting is applied by default, as expected)

**Comment by p00f** [comment]
I don't see any error messages

**Comment by p00f** [comment]
And my statusline is the default one instead of tjdevries/express-line.nvim

**Comment by p00f** [comment]
When i open the file directly (`nvim a.java`) I get
```
Error detected while processing function <SNR>9_load:                                                                                                                             
line    1:                                                                                                                                                                        
E5108: Error executing lua shared.lua:512: filename: expected string, got nil                                                                                                     
test 
```

**Comment by mfussenegger** [comment]
I think the root_dir in the configuration may have been missing because it used `.git`, `gradlew` or `mvnw` as markers.

I added a fallback to use the current working directory if none of them exists.
Could you try with the latest commit https://github.com/mfussenegger/nvim-jdtls/commit/175ffc0602aed2d5cab4084441cd35a3f3fbc979 of nvim-jdtls included?

**Comment by p00f** [comment]
It worked after creating .git

After updating to 175ffc0, it works even when there is no .git


Thanks!!

**Comment by p00f** [comment]
It works, thanks!

**Comment by ludwj61** [comment]
I understand this was closed but as someone also using nvim_lspconfig and trying to use this I am still confused. Is there any way I can integrate this with my current config using completion-nvim, diagnostic-nvim, etc?

Essentially, this is what I have in my lua file right now
```lua
local custom_attach = function(client)
    print("LSP started.")

    require"completion".on_attach(client)
    require"diagnostic".on_attach(client)

    -- Action
    map("n", "gD", "<cmd>lua vim.lsp.buf.declaration()<CR>")
    map("n", "gd", "<cmd>lua vim.lsp.buf.definition()<CR>")
    map("n", "K", "<cmd>lua vim.lsp.buf.hover()<CR>")
    map("n", "gr", "<cmd>lua vim.lsp.buf.references()<CR>")
    map("n", "gs", "<cmd>lua vim.lsp.buf.signature_help()<CR>")
    map("n", "gi", "<cmd>lua vim.lsp.buf.implementation()<CR>")
    map("n", "gt", "<cmd>lua vim.lsp.buf.type_definition()<CR>")
    map("n", "<leader>go", "<cmd>lua vim.lsp.buf.document_symbol()<CR>")
    map("n", "<leader>gw", "<cmd>lua vim.lsp.buf.workspace_symbol()<CR>")

    -- Goto
    map("n", "<leader>ah", "<cmd>lua vim.lsp.buf.hover()<CR>")
    map("n", "<leader>ac", "<cmd>lua vim.lsp.buf.code_action()<CR>")
    map("n", "<leader>dd", "<cmd>lua vim.lsp.util.show_line_diagnostics()<CR>")
    map("n", "<leader>ar", "<cmd>lua vim.lsp.buf.rename()<CR>")
    map("n", "<leader>=", "<cmd>lua vim.lsp.buf.formatting()<CR>")
    map("n", "<leader>ai", "<cmd>lua vim.lsp.buf.incoming_calls()<CR>")
    map("n", "<leader>ao", "<cmd>lua vim.lsp.buf.outgoing_calls()<CR>")

    -- Diagnostic
    map("n", "<leader>ep", "<cmd>PrevDiagnosticCycle<CR>")
    map("n", "<leader>en", "<cmd>NextDiagnosticCycle<CR>")
end

lsp.jdtls.setup{ on_attach = custom_attach }

```

What do I put instead of the last line to make this work?
