### ISSUE TITLE
Better Dependancy Managament [Request]

### ISSUE THREAD

**Issue by moha-abdi** [mfussenegger/nvim-jdtls#604]
### Problem Statement

In our current setup with nvim-jdtls for Neovim, managing Java dependencies can be challenging, especially when we're not using build tools like Maven or Gradle. Users often need to manually edit project configuration files to add or update external libraries, which is inefficient compared to the streamlined processes available in other IDEs or editors.

### Ideas or possible solutions

Implement a more user-friendly method for managing Java dependencies directly within Neovim. The goal is to introduce a functionality that allows easy addition, removal, and updating of library dependencies without the need for direct manipulation of configuration files. This would really help a lot of the plugin users including me who don't usually use the build tools like maven, etc. 

1. **Dependency Management Interface**: Develop a user-friendly interface within Neovim that allows users to interactively manage Java dependencies, including adding, removing, and updating libraries.

2. **Command-Line Integration**: Enhance nvim-jdtls with command-line capabilities for dependency management, enabling users to perform these tasks through Neovim commands.

**Comment by mfussenegger** [comment]
I don't have any plans to add something like that. As far as I'm concerned, _not_ using maven or gradle to manage dependencies is an anti-pattern.
