### ISSUE TITLE
Get Active Java Runtime

### ISSUE THREAD

**Issue by schrieveslaach** [mfussenegger/nvim-jdtls#605]
### Problem Statement

Thanks for creating nvim-jdtls. It is a great plugin that enabled me to switch to Neovim.

On top of nvim-jdtls [sonarlint.nvim](https://gitlab.com/schrieveslaach/sonarlint.nvim/) makes use of it to connect Java projects to [sonarlint-language-server](https://github.com/SonarSource/sonarlint-language-server). [As reported recently](https://gitlab.com/schrieveslaach/sonarlint.nvim/-/issues) sonarlint.nvim still has a fixed assumption of what JDK version is in use (see [here](https://gitlab.com/schrieveslaach/sonarlint.nvim/-/blob/4fecb6c8a705ade98c909a820c8ff3602a300bb4/lua/sonarlint/java.lua#L50)).

I'm aware of `:JdtSetRuntime` so I'm wondering if there is a way to query the version of the JDK that is currently in use.

### Ideas or possible solutions

Maybe add a dedicated function in `jdtls.utils` next to `with_classpath`

**Comment by mfussenegger** [comment]
I had a quick look at what vscode-java is doing to show the version in the statusline and I think it boils down to querying the compiler source level setting. So something like this should work:

```lua
local bufnr = 1 -- CHANGE THIS
local _, client = next(vim.lsp.get_clients({name = "jdtls"}))
local command = {
  command = "java.project.getSettings",
  arguments = {
    vim.uri_from_bufnr(bufnr),
    {
      "org.eclipse.jdt.core.compiler.source",
      "org.eclipse.jdt.ls.core.vm.location"
    }
  },
}
client.request("workspace/executeCommand", command, function(err, result)
  if err then
    vim.print(err)
  else
    vim.print(result)
  end
end)
```

This is using stock neovim lsp client API. You could also go through `jdtls.util.execute_command` to have the client lookup, command validation and coroutine handling.

**Comment by schrieveslaach** [comment]
Thanks for the great response. That helps a lot.
