### ISSUE TITLE
extract_variable: use `var` instead of concrete type

### ISSUE THREAD

**Issue by abenz1267** [mfussenegger/nvim-jdtls#615]
### Problem Statement

Right now the code actions for extracting to a local variable will always use the concrete type of the return value.

```String someVar = getSomeString()```

instead of

```var someVasr = getSomeString()```

JDTLS does have a code-action to convert to var, changing it manually doesn't exactly take much effort either. But isn't this something that could be done automagically?

### Ideas or possible solutions

Maybe a config option "preferVarOverType"?

**Comment by mfussenegger** [comment]
I think this is something that would have to be done in https://github.com/eclipse-jdtls/eclipse.jdt.ls
