### ISSUE TITLE
Goto definition of library class results in error

### ISSUE THREAD

**Issue by WizardStark** [mfussenegger/nvim-jdtls#639]
### LSP client configuration

		opts = {
			root_markers = { ".git", "mvnw", "gradlew", "pom.xml", "build.gradle" },
		},
		config = function(_, opts)
			local resolve_opts = function()
				local root_dir = require("jdtls.setup").find_root(opts.root_markers)
				local project_name = vim.fn.fnamemodify(vim.fn.getcwd(), ":p:h:t")
				local workspace_dir = vim.fn.stdpath("cache") .. "/jdtls/workspace-root/" .. project_name
				if vim.loop.fs_stat(workspace_dir) == nil then
					os.execute("mkdir " .. workspace_dir)
				end
				local install_path = require("mason-registry").get_package("jdtls"):get_install_path()
				local os
				if vim.fn.has("macunix") then
					os = "mac"
				else
					os = "linux"
				end

				return {
					cmd = {
						"java",
						"-Declipse.application=org.eclipse.jdt.ls.core.id1",
						"-Dosgi.bundles.defaultStartLevel=4",
						"-Declipse.product=org.eclipse.jdt.ls.core.product",
						"-Dlog.protocol=true",
						"-Dlog.level=ALL",
						"-javaagent:" .. install_path .. "/lombok.jar",
						"-Xmx1g",
						"--add-modules=ALL-SYSTEM",
						"--add-opens",
						"java.base/java.util=ALL-UNNAMED",
						"--add-opens",
						"java.base/java.lang=ALL-UNNAMED",
						"-jar",
						vim.fn.glob(install_path .. "/plugins/org.eclipse.equinox.launcher_*.jar"),
						"-configuration",
						install_path .. "/config_" .. os,
						"-data",
						workspace_dir,
					},
					root_dir = root_dir,
				}
			end

### Eclipse.jdt.ls version

1.31.0

### Steps to Reproduce

In a maven project (in this case, https://github.com/OpenAPITools/openapi-generator), call `vim.lsp.buf.definition` on a library class (either a class in a maven dependency or the Java standard library).

In this case the standard `java.util.Arrays` class.

### Expected Result

Open relevant class file

### Actual Result

I get the following error:
```
Error executing vim.schedule lua callback: BufReadCmd Autocommands for "jdt://*": Vim(lua):E5108: Error executing lua /home/user/.local/share/nvim/lazy/nvim-jdtls/lua/jdtls.lua:1134: Must have a `jdtls` client to load class file or jdt uri
stack traceback:
	[C]: in function 'assert'
	/home/user/.local/share/nvim/lazy/nvim-jdtls/lua/jdtls.lua:1134: in function 'open_classfile'
	[string ":lua"]:1: in main chunk
	[C]: in function 'bufload'
	/usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:272: in function 'get_lines'
	/usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1822: in function 'locations_to_items'
	/usr/local/share/nvim/runtime/lua/vim/lsp/handlers.lua:398: in function 'handler'
	/usr/local/share/nvim/runtime/lua/vim/lsp.lua:1393: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
	[C]: in function 'bufload'
	/usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:272: in function 'get_lines'
	/usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1822: in function 'locations_to_items'
	/usr/local/share/nvim/runtime/lua/vim/lsp/handlers.lua:398: in function 'handler'
	/usr/local/share/nvim/runtime/lua/vim/lsp.lua:1393: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

This seems to be very similar to #59, so I performed the steps in that issue,

The autocmd appears to be registered correctly:
```
--- Autocommands ---
BufReadCmd
jdt://*lua require('jdtls').open_classfile(vim.fn.expand('<amatch>'))
	Last set from ~/.local/share/nvim/lazy/nvim-jdtls/plugin/nvim_jdtls.vim line 6
```

When manually calling ```require('jdtls').open_classfile("jdt://contents/java.base...api%5C/=/=/maven.pomderived=/true=/%3Cjava.util(Arrays.class")```
the current buffer content is replaced with the appropriate Array class content.

From some further debugging I identified that the bufnr set [here](https://github.com/mfussenegger/nvim-jdtls/blob/master/lua/jdtls.lua#L1177) is different than that when calling `vim.api.nvim_get_current_buf` in the current buffer, resulting in `client` being nil as no lsp is attached to this other bufnr.

All other functionality of jdtls appears to work (go to definition of classes in the project, signature help, rename etc.).

Any help in this regard would be greatly appreciated

**Comment by mfussenegger** [comment]
Can this be reproduced without lazy?

**Comment by WizardStark** [comment]
I moved the config around to ftplugin/java.lua as per the README and it worked as expected. This was strange to me as ftplugin just uses a ft autocmd under the hood.
Turns out the autocmd that I used to trigger start_or_attach() was at fault, this check broke it.
```
vim.api.nvim_create_autocmd("Filetype", {
				pattern = "java",
				callback = function()
					local start_opts = resolve_opts()
			->		if start_opts.root_dir and start_opts.root_dir ~= "" then
						require("jdtls").start_or_attach(start_opts)
					end
				end,
			})
```

After removing that it functioned as expected. Sorry for the unnecessary issue!

**Comment by vasigorc** [comment]
Hello @mfussenegger could we consider re-opening this?

I likewise use `Lazy` for plugin management, but unlike with @WizardStark keeping the config in `~/.config/nvim/ftplugin/java.lua` doesn't for me. In fact the config is not being picked-up. So I followed a more idiomatic Lazy approach and put it in `~/.config/nvim/lua/plugins/java.lua`.

## My setup

Neovim version: 0.11.0
nvim-jdtls version: 0.2.0

## Steps to reproduce

On a fresh Lazy installation:

Add `java` [extra](https://www.lazyvim.org/extras/lang/java) to `~/.config/nvim/lua/config/lazy.lua` like such:

```lua
require("lazy").setup({
  spec = {
    -- add LazyVim and import its plugins
    { "LazyVim/LazyVim", import = "lazyvim.plugins" },
      { import = "lazyvim.plugins.extras.lang.java" },
   -- import/override with your plugins
    { import = "plugins" },
  },
```

Add this configuration to `~/.config/nvim/lua/plugins/java.lua`:

```lua
return {
  {
    "mfussenegger/nvim-jdtls",
    ft = "java",
    config = function()
      local config = {
        cmd = {
          "/Users/vasilegorcinschi/.sdkman/candidates/java/21.0.7-tem/bin/java",
          "-Declipse.application=org.eclipse.jdt.ls.core.id1",
          "-Dosgi.bundles.defaultStartLevel=4",
          "-Declipse.product=org.eclipse.jdt.ls.core.product",
          "-Dlog.protocol=true",
          "-Dlog.level=ALL",
          "-Xmx4g",
          "--add-modules=ALL-SYSTEM",
          "--add-opens",
          "java.base/java.util=ALL-UNNAMED",
          "--add-opens",
          "java.base/java.lang=ALL-UNNAMED",
          "-jar",
          vim.fn.glob("~/.local/share/nvim/mason/packages/jdtls/plugins/org.eclipse.equinox.launcher_*.jar"),
          "-configuration",
          vim.fn.glob("~/.local/share/nvim/mason/packages/jdtls/config_mac"),
          "-data",
          vim.fn.getcwd() .. "/.workspace",
        },
        root_dir = require("jdtls.setup").find_root({ ".git", "mvnw", "gradlew" }),
        settings = {
          java = {
            configuration = {
              runtimes = {
                {
                  name = "JavaSE-21",
                  path = "/Users/vasilegorcinschi/.sdkman/candidates/java/21.0.7-tem",
                },
                {
                  name = "JavaSE-17",
                  path = "/Users/vasilegorcinschi/.sdkman/candidates/java/17.0.9-tem",
                },
                {
                  name = "JavaSE-11",
                  path = "/Users/vasilegorcinschi/.sdkman/candidates/java/11.0.20.1-tem",
                },
              },
            },
            project = {
              referencedLibraries = {
                "lib/**/*.jar",
              },
            },
          },
        },
        init_options = {
          bundles = {},
        },
      }
      require("jdtls").start_or_attach(config)
    end,
  },
}
```

In my case I had to use a command different from default java to faciliate working with some Scala projects that rely on the default JAVA being 11.

## Issue

When navigating through global symbols (`<leader>sS`) I am getting this error:

```bash
error: BufReadCmd Autocommands for "jdt://*": Vim(lua):E5108: Error executing lua .../.local/share/nvim/lazy/nvim-jdtls/lua/jdtls.lua:1237: Must have a `jdtls` client to load class file or jdt uri  
stack traceback:  
    [C]: in function 'assert'  
    ...rcinschi/.local/share/nvim/lazy/nvim-jdtls/lua/jdtls.lua:1237: in function 'open_classfile'  
    [string ":lua"]:1: in main chunk  
    [C]: in function 'bufload'  
    ...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/preview.lua:87: in function <...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/preview.lua:76>  
    [C]: in function 'pcall'  
    ...nvim/lazy/snacks.nvim/lua/snacks/picker/core/preview.lua:166: in function 'show'  
    .../nvim/lazy/snacks.nvim/lua/snacks/picker/core/picker.lua:490: in function '_show_preview'  
    .../nvim/lazy/snacks.nvim/lua/snacks/picker/core/picker.lua:149: in function 'fn'  
    ...cal/share/nvim/lazy/snacks.nvim/lua/snacks/util/init.lua:326: in function 'run'  
    ...cal/share/nvim/lazy/snacks.nvim/lua/snacks/util/init.lua:335: in function 'show_preview'  
    ...re/nvim/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:632: in function <...re/nvim/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:630>
```

**Comment by PEMessage** [comment]
> Hello [@mfussenegger](https://github.com/mfussenegger) could we consider re-opening this?
> 
> I likewise use `Lazy` for plugin management, but unlike with [@WizardStark](https://github.com/WizardStark) keeping the config in `~/.config/nvim/ftplugin/java.lua` doesn't for me. In fact the config is not being picked-up. So I followed a more idiomatic Lazy approach and put it in `~/.config/nvim/lua/plugins/java.lua`.
> 
> ## My setup
> Neovim version: 0.11.0 nvim-jdtls version: 0.2.0
> 
> ## Steps to reproduce
> On a fresh Lazy installation:
> 
> Add `java` [extra](https://www.lazyvim.org/extras/lang/java) to `~/.config/nvim/lua/config/lazy.lua` like such:
> 
> require("lazy").setup({
>   spec = {
>     -- add LazyVim and import its plugins
>     { "LazyVim/LazyVim", import = "lazyvim.plugins" },
>       { import = "lazyvim.plugins.extras.lang.java" },
>    -- import/override with your plugins
>     { import = "plugins" },
>   },
> Add this configuration to `~/.config/nvim/lua/plugins/java.lua`:
> 
> return {
>   {
>     "mfussenegger/nvim-jdtls",
>     ft = "java",
>     config = function()
>       local config = {
>         cmd = {
>           "/Users/vasilegorcinschi/.sdkman/candidates/java/21.0.7-tem/bin/java",
>           "-Declipse.application=org.eclipse.jdt.ls.core.id1",
>           "-Dosgi.bundles.defaultStartLevel=4",
>           "-Declipse.product=org.eclipse.jdt.ls.core.product",
>           "-Dlog.protocol=true",
>           "-Dlog.level=ALL",
>           "-Xmx4g",
>           "--add-modules=ALL-SYSTEM",
>           "--add-opens",
>           "java.base/java.util=ALL-UNNAMED",
>           "--add-opens",
>           "java.base/java.lang=ALL-UNNAMED",
>           "-jar",
>           vim.fn.glob("~/.local/share/nvim/mason/packages/jdtls/plugins/org.eclipse.equinox.launcher_*.jar"),
>           "-configuration",
>           vim.fn.glob("~/.local/share/nvim/mason/packages/jdtls/config_mac"),
>           "-data",
>           vim.fn.getcwd() .. "/.workspace",
>         },
>         root_dir = require("jdtls.setup").find_root({ ".git", "mvnw", "gradlew" }),
>         settings = {
>           java = {
>             configuration = {
>               runtimes = {
>                 {
>                   name = "JavaSE-21",
>                   path = "/Users/vasilegorcinschi/.sdkman/candidates/java/21.0.7-tem",
>                 },
>                 {
>                   name = "JavaSE-17",
>                   path = "/Users/vasilegorcinschi/.sdkman/candidates/java/17.0.9-tem",
>                 },
>                 {
>                   name = "JavaSE-11",
>                   path = "/Users/vasilegorcinschi/.sdkman/candidates/java/11.0.20.1-tem",
>                 },
>               },
>             },
>             project = {
>               referencedLibraries = {
>                 "lib/**/*.jar",
>               },
>             },
>           },
>         },
>         init_options = {
>           bundles = {},
>         },
>       }
>       require("jdtls").start_or_attach(config)
>     end,
>   },
> }
> In my case I had to use a command different from default java to faciliate working with some Scala projects that rely on the default JAVA being 11.
> 
> ## Issue
> When navigating through global symbols (`<leader>sS`) I am getting this error:
> 
> error: BufReadCmd Autocommands for "jdt://*": Vim(lua):E5108: Error executing lua .../.local/share/nvim/lazy/nvim-jdtls/lua/jdtls.lua:1237: Must have a `jdtls` client to load class file or jdt uri  
> stack traceback:  
>     [C]: in function 'assert'  
>     ...rcinschi/.local/share/nvim/lazy/nvim-jdtls/lua/jdtls.lua:1237: in function 'open_classfile'  
>     [string ":lua"]:1: in main chunk  
>     [C]: in function 'bufload'  
>     ...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/preview.lua:87: in function <...hare/nvim/lazy/snacks.nvim/lua/snacks/picker/preview.lua:76>  
>     [C]: in function 'pcall'  
>     ...nvim/lazy/snacks.nvim/lua/snacks/picker/core/preview.lua:166: in function 'show'  
>     .../nvim/lazy/snacks.nvim/lua/snacks/picker/core/picker.lua:490: in function '_show_preview'  
>     .../nvim/lazy/snacks.nvim/lua/snacks/picker/core/picker.lua:149: in function 'fn'  
>     ...cal/share/nvim/lazy/snacks.nvim/lua/snacks/util/init.lua:326: in function 'run'  
>     ...cal/share/nvim/lazy/snacks.nvim/lua/snacks/util/init.lua:335: in function 'show_preview'  
>     ...re/nvim/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:632: in function <...re/nvim/lazy/snacks.nvim/lua/snacks/picker/core/list.lua:630>

For those who using lazy.nvim 
(and take reference of https://github.com/mfussenegger/nvim-jdtls/wiki/Sample-Configurations#hydroakri-configuration)

might also meet this problem

It turn out lazy.nvim `ft = 'java'` seem have wild behavior compare to ftplugin or autocmd

a workaround is create a autocmd just like above

This is my configuration

```lua
    {
        'mfussenegger/nvim-jdtls',
        version = false, -- set this if you want to always pull the latest change
        -- ft = { "java" }, 
        -- UPDATE: this will cause jump to class not work as expect
        dependencies = {
            -- 'mfussenegger/nvim-dap',
            'williamboman/mason.nvim',
            'williamboman/mason-lspconfig.nvim',
            "neovim/nvim-lspconfig",
        },
        -- opts = {
        --     cmd = {}, -- leave to config staged
        --     root_dir = vim.fs.dirname(vim.fs.find({'gradlew', '.git', 'mvnw', '.root'}, { upward = true })[1]),
        -- },
        config = function (_, _)
            -- We using mason-lspconfig, not using it according to readme
            local jdtls = require('jdtls')
            opts = {
                cmd = require('lspconfig').jdtls.document_config.default_config.cmd,
                -- See: https://github.com/mfussenegger/nvim-jdtls?tab=readme-ov-file#configuration-verbose
                root_dir = require("jdtls.setup").find_root({ ".git", "mvnw", "gradlew" }),
            }

            vim.api.nvim_create_autocmd("Filetype", {
				pattern = "java",
				callback = function()
                    require("jdtls").start_or_attach(opts)
				end,
			})
        end
    },
```
