### ISSUE TITLE
Jump to class

### ISSUE THREAD

**Issue by pwntester** [mfussenegger/nvim-jdtls#64]
Hi, Thanks for the awesome plugin!

I saw in your demos that you use `<C-]>` to jump to JRE class. I tried that and got:

```
E433: No tags file
E426: tag not found: ByteArrayOutputStream
```

Does this feature require Tags to be configured and enabled?

Also, is there any equivalent to IntelliJ `<Cmd-O>` to search for a class in the src tree but also in the dependencies?

**Comment by mfussenegger** [comment]
> I saw in your demos that you use <C-]> to jump to JRE class

I've a custom tagfunc that uses the lsp definition capabilities, but you can also just map `<C-]>` to `vim.lsp.buf.definition()`


> Also, is there any equivalent to IntelliJ <Cmd-O> to search for a class in the src tree but also in the dependencies?

You can query them using `vim.lsp.buf.workspace_symbol()`

**Comment by mfussenegger** [comment]
>  I will write a Telescope dynamic picker to get workspace symbols as you type

I think there is one already :)

**Comment by pwntester** [comment]
You can use `:Telescope lsp_workspace_symbols query=xxx` but thats a static picker. Meaning that you get the results for your query and then you can fuzzy search the results for that query, but the one Im going to write is dynamic, so it will send queries to the LSP server while you type and then you can pick the final one from the results.

**Comment by James-Steve** [comment]
> > I saw in your demos that you use <C-]> to jump to JRE class
> 
> I've a custom tagfunc that uses the lsp definition capabilities, but you can also just map `<C-]>` to `vim.lsp.buf.definition()`
> 
> > Also, is there any equivalent to IntelliJ  to search for a class in the src tree but also in the dependencies?
> 
> You can query them using `vim.lsp.buf.workspace_symbol()`


Regarding `Vim.lsp.buf.defintion`, I find that the buffer which contains that class must be open in order to jump into it.
Is there any way in which we can jump into classes without the file which contains said class being open?
