### ISSUE TITLE
Allow partial overrides of the default config

### ISSUE THREAD

**Issue by SOberhoff** [mfussenegger/nvim-jdtls#647]
### Problem Statement

I'm trying to setup nvim-jdtls with the following config:

```
local jdtls_config = {
  settings = {
    java = {
      configuration = {
        runtimes = {
          {
            name = "JavaSE-21",
            path = "/path/to/java21",
          }
        }
      }
    }
  }
}
require("jdtls").start_or_attach(jdtls_config)
```

However, when I do this I get: `Failed to run "config" for nvim-jdtls
~/.local/share/nvim/lazy/nvim-jdtls/lua/jdtls/setup.lua:275: bad argument #1 to 'concat' (table expected, got nil)`.

I'm happy with the default config for `cmd`. I don't want to type it out again. Moreover, the error message is more than a little obtuse. It doesn't properly handle the case where `cmd` is nil.

### Ideas or possible solutions

If `cmd` is nil, set it to the default.

**Comment by mfussenegger** [comment]
Sounds like something specific to lazy? There is no default `cmd`, and I'm not going to add one

**Comment by SOberhoff** [comment]
Okay, how about at least not passing a nil `cmd` to table.concat so the user gets a better error message?
