### ISSUE TITLE
Goto definition results in error after commit ad5ab1c

### ISSUE THREAD

**Issue by michaelPotter** [mfussenegger/nvim-jdtls#666]
### LSP client configuration

```lua
-- This specifies extra jars that get loaded into the Language Server
local bundles = {
	vim.fn.glob('$HOME/.local/share/nvim/mason/packages/java-debug-adapter/extension/server/com.microsoft.java.debug.plugin-*.jar'),
}
vim.list_extend(bundles, vim.split(vim.fn.glob("$HOME/.local/share/nvim/mason/packages/java-test/extension/server/*.jar", true), "\n"))

local jdtls_lsp = require("mason-registry").get_package("jdtls")

local config = {
    cmd = {
		vim.fn.expand('$HOME/.local/share/nvim/mason/bin/jdtls'),
		-- https://github.com/LazyVim/LazyVim/discussions/275
		"--jvm-arg=-javaagent:" .. jdtls_lsp:get_install_path() .. "/lombok.jar",
	},
    root_dir = vim.fs.dirname(vim.fs.find({'gradlew', '.git', 'mvnw'}, { upward = true })[1]),
	on_attach = on_attach,
	settings = {
		java = {
			configuration = {
				runtimes = {
					{
						name = "JavaSE-17",
						path = "/usr/lib/jvm/java-17-openjdk/",
					},
				},
			},
		},
	},
	init_options = {
		bundles = bundles,
	},
}
```

### Steps to Reproduce

(This seems to be a regression in commit ad5ab1c? It seems to work okay on commit 1069131 or earlier.)

First checkout commit ad5ab1c or later.

Call `vim.lsp.buf.definition` on a class, eg

``` java
import java.util.Arrays;
```

### Expected Result

The class definition is opened.

### Actual Result

An empty buffer loads and I get the following error:

> Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1125: BufReadCmd Autocommands for "jdt://*": Vim(lua):E5108: Error executing lua ...mlpotter/.local/sha
> re/nvim/lazy/nvim-jdtls/lua/jdtls.lua:1193: Must have a `jdtls` client to load class file or jdt uri
> stack traceback:
>         [C]: in function 'assert'
>         ...mlpotter/.local/share/nvim/lazy/nvim-jdtls/lua/jdtls.lua:1193: in function 'open_classfile'
>         [string ":lua"]:1: in main chunk
>         [C]: in function 'nvim_win_set_buf'
>         /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1125: in function 'jump_to_location'
>         ...nvim/lazy/telescope.nvim/lua/telescope/builtin/__lsp.lua:187: in function 'handler'
>         /usr/share/nvim/runtime/lua/vim/lsp/client.lua:685: in function ''
>         vim/_editor.lua: in function <vim/_editor.lua:0>
> stack traceback:
>         [C]: in function 'nvim_win_set_buf'
>         /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1125: in function 'jump_to_location'
>         ...nvim/lazy/telescope.nvim/lua/telescope/builtin/__lsp.lua:187: in function 'handler'
>         /usr/share/nvim/runtime/lua/vim/lsp/client.lua:685: in function ''
>         vim/_editor.lua: in function <vim/_editor.lua:0>

fwiw, in both commits where it does/doesn't work, `set buftype?` returns `buftype=nofile` for the jdt:// buffer

Thanks!

**Comment by robertenjoy** [comment]
I had the same problem。
#639 
close lazy.nvim lazyload
create ~/.config/nvim/ftplugin/java.lua
Solved my problem

**Comment by michaelPotter** [comment]
Thanks!

I already configure jdtls through `~/.config/nvim/ftplugin/java.lua`. I don't lazy load either.

Some other info after reading through #639 and #59 again...

Running this ...
```
:lua require("jdtls").open_classfile("jdt://contents/java.base/java.util/Arrays.class?=jdt.ls-java-project/%5C/usr%5C/lib%5C/jvm%5C/java-17-openjdk%5C/lib%5C/jrt-fs.jar%60java.base=/javadoc_location=/https:%5C/%5C/docs.oracle.com%5C/en%5C/java%5C/javase%5C/17%5C/docs%5C/api%5C/=/%3Cjava.util(Arrays.class")
```
... DOES populate the (current, already open) buffer with both commits 1069131 and 29255ea.

**Comment by michaelPotter** [comment]
Did a little debugging... Seems like `jdtls.setup.attach_to_active_buf()` might not be doing the right thing? Assuming the goal is to find an active jdtls client instance from other buffers and `start_or_attach` should use that to short-circuit before the code added in 1069131 ?

I get this message using **both** commits... Seems to come from the bottom of attach_to_active_buf. 
> No active LSP client found to use for jdt:// document

**Comment by jamilraichouni** [comment]
Can confirm the same.

Info:

```text
NVIM v0.10.0                                                                                                                                                                                                                                  
Build type: RelWithDebInfo                                                                                                                                                                                                                    
LuaJIT 2.1.1713773202                                                                                                                                                                                                                         
Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-har
dened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -O2 -g -Og -g -flto=a
uto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-
protector-strong -Wno-conversion -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto  -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -I/usr/include/luajit-2.1 -I/usr/include -I/bu
ilddir/build/BUILD/neovim-0.10.0/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.10.0/redhat-linux-build/include -I/builddir/build/BUILD/neovim-0.10.0/redhat-linux-build/cmake.config -I/builddir/build/BUILD/neovim-0.10.0
/src         
```
With commit 1069131 I can directly open a `.class` file. With the next commit ad5ab1c I get 

```
Error detected while processing BufReadCmd Autocommands for "*.class":                                                                                                                                                                        
E5108: Error executing lua ...aichouni/.local/share/nvim/lazy/nvim-jdtls/lua/jdtls.lua:1193: Must have a `jdtls` client to load class file or jdt uri                                                                                         
stack traceback:                                                                                                                                                                                                                              
        [C]: in function 'assert'                                                                                                                                                                                                             
        ...aichouni/.local/share/nvim/lazy/nvim-jdtls/lua/jdtls.lua:1193: in function 'open_classfile'                                                                                                                                        
        [string ":lua"]:1: in main chunk                                                                                                                                                                                                      
Press ENTER or type command to continue 
```

**Comment by jamilraichouni** [comment]
I would also rename the issue, since just opening a .class file leads to the behavior in my case.
So it seems to be the decompilation with FernFlower that does (in some cases) not work anymore in `nvim-jdtls`!?

**Comment by mfussenegger** [comment]
The .class file case should work again with https://github.com/mfussenegger/nvim-jdtls/pull/673, sorry about that. 

As for jdt:// uri - I can't produce the problem. They should still be attaching via the jdt logic a bit above of the changed lines

**Comment by michaelPotter** [comment]
Hi @mfussenegger, thanks for confirming you can't repro. I've found the issue in my config so I'll close this.

Just cuz I hate open endings, here's what happened... my goto definition binding uses `require('telescope.builtin').lsp_definitions` instead of regular `vim.lsp.buf.definition()` and the root cause is there was a bug in the version of telescope I was on.

And during troubleshooting I disabled a bunch of plugins to try and isolate things (great idea right?), which caused an error in my on_attach hook causing vanilla vim.lsp.buf.definition() to break with a pretty useless stacktrace.

Oh the tangled webs we weave.

**Comment by jamilraichouni** [comment]
Checked it quickly and for me the issue is gone with 6bfd159 for
directly opening a `.class` file via `nvim /path/to/some/file.class`.

Thank you very much for this great and helpful plugin and also for fixing so quickly!

Servus nach Österreich
Jamil
