### ISSUE TITLE
very slow on large project comparing to intellij

### ISSUE THREAD

**Issue by yimingwangdell** [mfussenegger/nvim-jdtls#669]
### LSP client configuration

coc-java

### Steps to Reproduce

completion on large project has millions of lines.

### Expected Result

less than 10s

### Actual Result

need to wait more than 20s for first completion.

**Comment by yimingwangdell** [comment]
report to jdtls project.
https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3202

**Comment by vishal423** [comment]
strange.. In my case, it was one of main pain point to move away from IntelliJ 😄

**Comment by yimingwangdell** [comment]
@vishal423 my project is very large. there are some big .java files generated by protobuf, which have more that 200000 lines and some single java files more than 10000 lines is referencing classes from that protobuf java file.
