### ISSUE TITLE
not able to change memory size for runtimes

### ISSUE THREAD

**Issue by yimingwangdell** [mfussenegger/nvim-jdtls#670]
### Problem Statement

is there a way to change -Xmx value for runtimes?
we can only set name and path for now.

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-jdtls?tab=readme-ov-file#configuration-verbose for the configuration for eclipse.jdt.ls itself.

To set the memory of applications you run via nvim-dap, there's a `vmArgs` property.
