### ISSUE TITLE
Java argument files

### ISSUE THREAD

**Issue by Tired-Fox** [mfussenegger/nvim-jdtls#674]
### Problem Statement

I am able to do most things I would want a Java IDE to do. However, this ends when I want to run a test with a really long classpath and the length limit is reached. The workarounds aren't so bad, but require some effort while using the plugin.

### Ideas or possible solutions

I propose a toggle in the config to use the argument file feature in java versions 9+. This would mean that the arguments for commands that are run, like for dap or running main, would go into a temporary file and loaded with the argument `java @<path to temp file>`. This would solve the problems that come with a long classpath in a cli (especially on Windows).

*References*
- https://stackoverflow.com/a/54270831
- https://docs.oracle.com/javase/9/tools/java.htm#JSWOR-GUID-4856361B-8BFD-4964-AE84-121F5F6CF111

**Comment by mfussenegger** [comment]
java-debug supports a `shortenCommandLine` option in the launch arguments which you can set to `argfile`.
See https://github.com/microsoft/java-debug/pull/253

To pass it to tests you can call `test_nearest_method` or `test_class` with a `{ config_overrides = { ... } }` table.

E.g. the following should work:

```lua
jdtls.test_class({
  config_overrides = {
    shortenCommandLine = "argfile",
  }
})
```

**Comment by Tired-Fox** [comment]
Thank you for the response! I appreciate all the work that you are doing.

**Comment by Tired-Fox** [comment]
Thank you for the response! I appreciate all the work that you are doing.
