### ISSUE TITLE
too many logs/prints

### ISSUE THREAD

**Issue by karshPrime** [mfussenegger/nvim-jdtls#683]
### LSP client configuration
```
require('jdtls').start_or_attach({
    cmd = {'/opt/homebrew/bin/jdtls'},
    root_dir = vim.fs.dirname(vim.fs.find({'gradlew', '.git', 'mvnw'}, { upward = true })[1]),
})
```

### Eclipse.jdt.ls version

dunno how to find

### Steps to Reproduce

In a project using gradle v8.10. This is the case in any project I open, and I'm sure there gotta be a way to mute this, but I cant seem to find how.

The issue is the LSP is generating too many logs and too dynamically that it's literally distracting. every letter I enter makes it "validate document," which may be something really essential for the backend, but I dont want to keep seeing these logs.

Would really appreicaite it if I could be directed with instructions on how I can hide/mute/disable these messages.

### Expected Result

no output.

### Actual Result

<img width="472" alt="image" src="https://github.com/user-attachments/assets/3c31f5b6-98ed-43f4-9e6b-81b5cb53f206">

**Comment by karshPrime** [comment]
nevermind fixed it

**Comment by karshPrime** [comment]
nevermind fixed it

**Comment by sailingbonbini** [comment]
How though? I'm having exactly the same problem.

**Comment by karshPrime** [comment]
@sailingbonbini So I am using the [folke/noice.nvim](https://github.com/folke/noice.nvim) plugin for my notifications, as shown in the screenshot above. I got the issue by updating its config with-
```
    routes = {{
        filter = {
            event = "lsp",
            kind = "progress",
            cond = function(message)
                local client = vim.tbl_get(message.opts, "progress", "client")
                return client == "jdtls"
            end,
        },
        opts = { skip = true },
    },},
```
you can find my full config for this plugin [here](https://github.com/karshPrime/dotfiles/blob/main/shared/nvim/lua/plugins/layout.lua)
