### ISSUE TITLE
Synchroneous call of M.compile({type}) so that one can wait before any depending post-processing starts

### ISSUE THREAD

**Issue by jamilraichouni** [mfussenegger/nvim-jdtls#689]
### Problem Statement

I have no chance to know when `.class` file creation, compilation via `M.compile({type})`, is completed before I start to pack and deploy the according `.jar` file.

### Ideas or possible solutions

Make run of `M.compile({type})` snychroneous and provide return code, error message(s) etc.

**Comment by mfussenegger** [comment]
As a workaround you could make the underlying request directly with something like  `client.request_sync("java/buildWorkspace", false, 5000, bufnr)`

You won't get the logic that populates the quickfix list with errors if there are any, but if all you want is to have the compilation and then trigger something that should be good enough. I also use that in my dotfiles.


(`client` is either from on_attach/LspAttach, or you can get it via `vim.lsp.get_clients({ name = "jdtls" })[1]`)

**Comment by jamilraichouni** [comment]
Thank you @mfussenegger ,

I replaced 

```lua
require("jdtls").compile("full")
```

with

```lua
local bufnr = vim.api.nvim_get_current_buf()
local client = vim.lsp.get_clients({ name = "jdtls", bufnr = bufnr })[1]
local resp = client.request_sync("java/buildWorkspace", true, 5000, bufnr)
if resp.result > 1 then
    require("jdtls").compile("full")
    return
end
```
Looks like `resp.result` equals `1` in the case of a successful compilation.
