### ISSUE TITLE
Feature Request: Set breakpoints on decompiled methods

### ISSUE THREAD

**Issue by stevenxxiu** [mfussenegger/nvim-jdtls#691]
### Problem Statement

I'm trying to migrate from *JetBrains* *IntelliJ IDEA* over to *Neovim*.

One thing I really need is to set breakpoints on decompiled methods. *IntelliJ IDEA* and *JDB* support setting breakpoints at the start of methods, viewing their arguments, call stacks.

I see that *jdtls* supports decompiling classes. Could breakpoints be supported too?

**Comment by vishal423** [comment]
I believe that already works. Did you notice any issue?

**Comment by stevenxxiu** [comment]
Ah my original issue was due to trying to set a breakpoint in a window opened by *lspsaga*.
