### ISSUE TITLE
JDLTS Autocompletion fails with Exception

### ISSUE THREAD

**Issue by RononDex** [mfussenegger/nvim-jdtls#698]
### LSP client configuration

local home = os.getenv("HOME")
local java_cmds = vim.api.nvim_create_augroup('java_cmds', { clear = true })
local cache_vars = {}

local root_files = {
	'.git',
	'mvnw',
	'gradlew',
	'build.gradle',
}

local features = {
	-- change this to `true` to enable codelens
	codelens = true,

	-- change this to `true` if you have `nvim-dap`,
	-- `java-test` and `java-debug-adapter` installed
	debugger = true,
}

local function get_jdtls_paths()
	if cache_vars.paths then
		return cache_vars.paths
	end

	local path = {}

	path.data_dir = vim.fn.stdpath('cache') .. '/nvim-jdtls'

	local jdtls_install = require('mason-registry')
	    .get_package('jdtls')
	    :get_install_path()

	path.java_agent = jdtls_install .. '/lombok.jar'
	path.launcher_jar = vim.fn.glob(jdtls_install .. '/plugins/org.eclipse.equinox.launcher_*.jar')

	if vim.fn.has('mac') == 1 then
		path.platform_config = jdtls_install .. '/config_mac'
	elseif vim.fn.has('unix') == 1 then
		path.platform_config = jdtls_install .. '/config_linux'
	elseif vim.fn.has('win32') == 1 then
		path.platform_config = jdtls_install .. '/config_win'
	end

	path.bundles = {}

	---
	-- Include java-test bundle if present
	---
	local java_test_path = require('mason-registry')
	    .get_package('java-test')
	    :get_install_path()

	local java_test_bundle = vim.split(
		vim.fn.glob(java_test_path .. '/extension/server/*.jar'),
		'\n'
	)

	if java_test_bundle[1] ~= '' then
		vim.list_extend(path.bundles, java_test_bundle)
	end

	---
	-- Include java-debug-adapter bundle if present
	---
	local java_debug_path = require('mason-registry')
	    .get_package('java-debug-adapter')
	    :get_install_path()

	local java_debug_bundle = vim.split(
		vim.fn.glob(java_debug_path .. '/extension/server/com.microsoft.java.debug.plugin-*.jar'),
		'\n'
	)

	if java_debug_bundle[1] ~= '' then
		vim.list_extend(path.bundles, java_debug_bundle)
	end

	---
	-- Useful if you're starting jdtls with a Java version that's
	-- different from the one the project uses.
	---
	path.runtimes = {
		-- Note: the field `name` must be a valid `ExecutionEnvironment`,
		-- you can find the list here:
		-- https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request
		{
			name = "JavaSE-1.8",
			path = "/usr/lib/jvm/java-8-openjdk"
		},
		{
			name = "JavaSE-17",
			path = "/usr/lib/jvm/java-17-openjdk",
		},
		{
			name = "JavaSE-22",
			path = "/usr/lib/jvm/java-22-openjdk",
			default = true
		}
	}

	cache_vars.paths = path

	return path
end

local function enable_codelens(bufnr)
	pcall(vim.lsp.codelens.refresh)

	vim.api.nvim_create_autocmd('BufWritePost', {
		buffer = bufnr,
		group = java_cmds,
		desc = 'refresh codelens',
		callback = function()
			pcall(vim.lsp.codelens.refresh)
		end,
	})
end

local function enable_debugger(bufnr)
	require('jdtls').setup_dap({ hotcodereplace = 'auto' })

	require('dap.ext.vscode').load_launchjs(nil, {})
end

local function jdtls_on_attach(client, bufnr)
	if features.debugger then
		enable_debugger(bufnr)
	end

	if features.codelens then
		enable_codelens(bufnr)
	end

	-- The following mappings are based on the suggested usage of nvim-jdtls
	-- https://github.com/mfussenegger/nvim-jdtls#usage

	local opts = { buffer = bufnr }
end

local function jdtls_setup(event)
	local jdtls = require('jdtls')

	local path = get_jdtls_paths()
	local data_dir = path.data_dir .. '/' .. vim.fn.fnamemodify(vim.fn.getcwd(), ':p:h:t')

	if cache_vars.capabilities == nil then
		jdtls.extendedClientCapabilities.resolveAdditionalTextEditsSupport = true
		jdtls.extendedClientCapabilities.onCompletionItemSelectedCommand = "editor.action.triggerParameterHints"

		local ok_cmp, cmp_lsp = pcall(require, 'cmp_nvim_lsp')
		cache_vars.capabilities = vim.tbl_deep_extend(
			'force',
			vim.lsp.protocol.make_client_capabilities(),
			ok_cmp and cmp_lsp.default_capabilities() or {}
		)
	end

	-- The command that starts the language server
	-- See: https://github.com/eclipse/eclipse.jdt.ls#running-from-the-command-line
	local cmd = {
		'java',
		'-Declipse.application=org.eclipse.jdt.ls.core.id1',
		'-Dosgi.bundles.defaultStartLevel=4',
		'-Declipse.product=org.eclipse.jdt.ls.core.product',
		'-Dlog.protocol=true',
		'-Dlog.level=ALL',
		'-javaagent:' .. path.java_agent,
		'-Xmx1g',
		'--add-modules=ALL-SYSTEM',
		'--add-opens',
		'java.base/java.util=ALL-UNNAMED',
		'--add-opens',
		'java.base/java.lang=ALL-UNNAMED',
		'-jar',
		path.launcher_jar,
		'-configuration',
		path.platform_config,
		'-data',
		data_dir,
	}

	local lsp_settings = {
		java = {
			-- jdt = {
			--   ls = {
			--     vmargs = "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m"
			--   }
			-- },
			eclipse = {
				downloadSources = true,
			},
			configuration = {
				updateBuildConfiguration = 'interactive',
				runtimes = path.runtimes,
				saveActions = {
					organizeImports = true,
				}
			},
			maven = {
				downloadSources = true,
			},
			implementationsCodeLens = {
				enabled = true,
			},
			referencesCodeLens = {
				enabled = true,
			},
			inlayHints = {
				parameterNames = {
					enabled = 'all' -- literals, all, none
				}
			},
			format = {
				enabled = true,
				settings = {
					--   profile = 'asdf'
					url = home .. "/.config/nvim/eclipse-java-style.xml",
				},
			},
			saveActions = {
				organizeImports = true,
			}
		},
		signatureHelp = {
			enabled = true,
		},
		completion = {
			favoriteStaticMembers = {
				'org.hamcrest.MatcherAssert.assertThat',
				'org.hamcrest.Matchers.*',
				'org.hamcrest.CoreMatchers.*',
				'org.junit.jupiter.api.Assertions.*',
				'java.util.Objects.requireNonNull',
				'java.util.Objects.requireNonNullElse',
				'org.mockito.Mockito.*',
			},
		},
		contentProvider = {
			preferred = 'fernflower',
		},
		extendedClientCapabilities = jdtls.extendedClientCapabilities,
		sources = {
			organizeImports = {
				starThreshold = 9999,
				staticStarThreshold = 9999,
			}
		},
		codeGeneration = {
			toString = {
				template = '${object.className}{${member.name()}=${member.value}, ${otherMembers}}',
			},
			useBlocks = true,
		},
	}

	local extendedClientCapabilities = jdtls.extendedClientCapabilities;

	-- This starts a new client & server,
	-- or attaches to an existing client & server depending on the `root_dir`.
	jdtls.start_or_attach({
		cmd = cmd,
		settings = lsp_settings,
		on_attach = jdtls_on_attach,
		capabilities = cache_vars.capabilities,
		root_dir = jdtls.setup.find_root(root_files),
		flags = {
			allow_incremental_sync = true,
		},
		init_options = {
			bundles = path.bundles,
			extendedClientCapabilities = extendedClientCapabilities
		},
	})
end

vim.api.nvim_create_autocmd('FileType', {
	group = java_cmds,
	pattern = { 'java' },
	desc = 'Setup jdtls',
	callback = jdtls_setup,
})

### Eclipse.jdt.ls version

1.38.0

### Steps to Reproduce

Simply open any .java file (in my case a maven project) and try to type in any java code. Auto completion does not work.

This exact same jdtls config used to work last week.

### Expected Result

Auto completion is working

### Actual Result

Some of the exceptions found in "LspLog":

```
ERROR][2024-09-25 17:39:09] ...lsp/handlers.lua:623	"Sep 25, 2024, 5:39:09 PM Multiple projects are valid for evaluation."
[ERROR][2024-09-25 17:39:09] .../vim/lsp/rpc.lua:770	"rpc"	"java"	"stderr"	"Sep 25, 2024 5:39:09 PM com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider findJavaProjectByType\nSEVERE: Multiple projects are valid for evaluation.\n"

[ERROR][2024-09-25 17:39:09] .../vim/lsp/rpc.lua:770	"rpc"	"java"	"stderr"	"Sep 25, 2024 5:39:09 PM com.microsoft.java.debug.core.adapter.handler.VariablesRequestHandler handle\nINFO: Failed to get the logical size of the variable\njava.util.concurrent.ExecutionException: java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json.\n\tat java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)\n\tat java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)\n\tat com.microsoft.java.debug.core.adapter.variables.JavaLogicalStructure.getValue(JavaLogicalStructure.java:145)\n\tat com.microsoft.java.debug.core.adapter.variables.JavaLogicalStructure.getSize(JavaLogicalStructure.java:128)\n\tat com.microsoft.java.debug.core.adapter.handler.VariablesRequestHandler.handle(VariablesRequestHandler.java:288)\n\tat com.microsoft.java.debug.core.adapter.DebugAdapter.lambda$dispatchRequest$0(DebugAdapter.java:94)\n\tat java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)\n\tat java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2341)\n\tat com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:93)\n\tat com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:132)\n\tat com.microsoft.java.debug.core.protocol.AbstractProtocolServer.lambda$new$0(AbstractProtocolServer.java:81)\n\tat io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)\n\tat io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)\n\tat io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: java.lang.IllegalStateException: Cannot evaluate, please specify projectName in launch.json.\n\tat com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.findJavaProjectByType(JdtEvaluationProvider.java:299)\n\tat com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.ensureDebugTarget(JdtEvaluationProvider.java:419)\n\tat com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider.invokeMethod(JdtEvaluationProvider.java:195)\n\t... 19 more\n\n"


[ERROR][2024-09-26 08:50:01] .../vim/lsp/rpc.lua:770	"rpc"	"java"	"stderr"	"Sep 26, 2024 8:50:01 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError\nSEVERE: Internal error: java.lang.IllegalStateException: Invalid completion proposal\njava.util.concurrent.CompletionException: java.lang.IllegalStateException: Invalid completion proposal\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)\n\tat java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:747)\n\tat java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)\n\tat java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2214)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:290)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)\n\tat org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)\n\tat org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: java.lang.IllegalStateException: Invalid completion proposal\n\tat org.eclipse.jdt.ls.core.internal.handlers.CompletionResolveHandler.resolve(CompletionResolveHandler.java:106)\n\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.resolveCompletionItem(JDTLanguageServer.java:642)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:272)\n\t... 10 more\n\n"


[ERROR][2024-09-30 14:54:34] ...lsp/handlers.lua:623	"Sep 30, 2024, 2:54:34 PM Exception thrown by Java annotation processor org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor@20261fa0\njava.lang.IllegalStateException: Error processing configuration meta-data on org.esa.euclid.sgs.ial.dss.single.store.SingleStoreProperties\njava.lang.Exception: java.lang.IllegalStateException: Error processing configuration meta-data on org.esa.euclid.sgs.ial.dss.single.store.SingleStoreProperties\n\tat org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:171)\n\tat org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:123)\n\tat org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:172)\n\tat org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)\n\tat org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:972)\n\tat org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:449)\n\tat org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:425)\n\tat org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:414)\n\tat org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:369)\n\tat org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:345)\n\tat org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.incrementalBuildLoop(IncrementalImageBuilder.java:189)\n\tat org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:146)\n\tat org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:304)\n\tat org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:221)\n\tat org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)\n\tat org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)\n\tat org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)\n\tat org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)\n\tat org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)\n\tat org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)\n\tat org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)\n\tat org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)\n\tat org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)\n\tat org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)\n\tat org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)\n\tat org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)\n\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)\nCaused by: java.lang.IllegalStateException: Error processing configuration meta-data on org.esa.euclid.sgs.ial.dss.single.store.SingleStoreProperties\n\tat org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.processElement(ConfigurationMetadataAnnotationProcessor.java:226)\n\tat org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.process(ConfigurationMetadataAnnotationProcessor.java:180)\n\tat org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:141)\n\t... 26 more\nCaused by: org.eclipse.jdt.internal.compiler.problem.AbortCompilation: \n\tat org.eclipse.jdt.internal.core.builder.NameEnvironment.findClass(NameEnvironment.java:520)\n\tat org.eclipse.jdt.internal.core.builder.NameEnvironment.findType(NameEnvironment.java:590)\n\tat org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.lambda$0(LookupEnvironment.java:279)\n\tat org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForTypeFromModules(LookupEnvironment.java:414)\n\tat org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:278)\n\tat org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:1849)\n\tat org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:1818)\n\tat org.eclipse.jdt.internal.compiler.apt.model.ElementsImpl9.getTypeElement(ElementsImpl9.java:100)\n\tat org.eclipse.jdt.internal.compiler.apt.model.ElementsImpl9.getTypeElement(ElementsImpl9.java:72)\n\tat org.springframework.boot.configurationprocessor.TypeUtils.process(TypeUtils.java:237)\n\tat org.springframework.boot.configurationprocessor.TypeUtils.createTypeDescriptor(TypeUtils.java:228)\n\tat org.springframework.boot.configurationprocessor.TypeUtils.getType(TypeUtils.java:137)\n\tat org.springframework.boot.configurationprocessor.PropertyDescriptor.resolveType(PropertyDescriptor.java:155)\n\tat org.springframework.boot.configurationprocessor.PropertyDescriptor.resolveItemMetadataProperty(PropertyDescriptor.java:136)\n\tat org.springframework.boot.configurationprocessor.PropertyDescriptor.resolveItemMetadata(PropertyDescriptor.java:130)\n\tat org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.lambda$processTypeElement$0(ConfigurationMetadataAnnotationProcessor.java:263)\n\tat java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)\n\tat java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)\n\tat java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)\n\tat org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.processTypeElement(ConfigurationMetadataAnnotationProcessor.java:262)\n\tat org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.lambda$processTypeElement$0(ConfigurationMetadataAnnotationProcessor.java:268)\n\tat java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)\n\tat java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)\n\tat java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)\n\tat org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.processTypeElement(ConfigurationMetadataAnnotationProcessor.java:262)\n\tat org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.processAnnotatedTypeElement(ConfigurationMetadataAnnotationProcessor.java:233)\n\tat org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.processElement(ConfigurationMetadataAnnotationProcessor.java:218)\n\t... 28 more\n"
[ERROR][2024-09-30 14:54:34] ...lsp/handlers.lua:623	"Sep 30, 2024, 2:54:34 PM Exception thrown by Java annotation processor org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor@20261fa0\njava.lang.IllegalStateException: Failed to write metadata\njava.lang.Exception: java.lang.IllegalStateException: Failed to write metadata\n\tat org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:171)\n\tat org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:112)\n\tat org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:172)\n\tat org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)\n\tat org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:1010)\n\tat org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:449)\n\tat org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:425)\n\tat org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:414)\n\tat org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:369)\n\tat org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:345)\n\tat org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.incrementalBuildLoop(IncrementalImageBuilder.java:189)\n\tat org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:146)\n\tat org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:304)\n\tat org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:221)\n\tat org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)\n\tat org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)\n\tat org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)\n\tat org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)\n\tat org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)\n\tat org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)\n\tat org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)\n\tat org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)\n\tat org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)\n\tat org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)\n\tat org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)\n\tat org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)\n\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)\nCaused by: java.lang.IllegalStateException: Failed to write metadata\n\tat org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.process(ConfigurationMetadataAnnotationProcessor.java:194)\n\tat org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:141)\n\t... 26 more\nCaused by: org.eclipse.jdt.internal.compiler.problem.AbortCompilation: \n\tat org.eclipse.jdt.internal.core.builder.NameEnvironment.findClass(NameEnvironment.java:520)\n\tat org.eclipse.jdt.internal.core.builder.NameEnvironment.findType(NameEnvironment.java:590)\n\tat org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.lambda$0(LookupEnvironment.java:279)\n\tat org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForTypeFromModules(LookupEnvironment.java:414)\n\tat org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:278)\n\tat org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:1849)\n\tat org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getType(LookupEnvironment.java:1818)\n\tat org.eclipse.jdt.internal.compiler.apt.model.ElementsImpl9.getTypeElement(ElementsImpl9.java:100)\n\tat org.eclipse.jdt.internal.compiler.apt.model.ElementsImpl9.getTypeElement(ElementsImpl9.java:72)\n\tat org.springframework.boot.configurationprocessor.MetadataCollector.deletedInCurrentBuild(MetadataCollector.java:114)\n\tat org.springframework.boot.configurationprocessor.MetadataCollector.shouldBeMerged(MetadataCollector.java:110)\n\tat org.springframework.boot.configurationprocessor.MetadataCollector.getMetadata(MetadataCollector.java:100)\n\tat org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.writeMetadata(ConfigurationMetadataAnnotationProcessor.java:335)\n\tat org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessor.process(ConfigurationMetadataAnnotationProcessor.java:191)\n\t... 27 more\n"





```

**Comment by diego-velez** [comment]
Hello, I believe I'm having a similar issue.

Every time I accept an autocompletion, it gives me the autocompletion, but Neovim show me the following error:

```
vim.schedule callback: /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:348: method "workspace/executeClientCommand": either a result or an error must be sent to the server in response
stack traceback:
        [builtin#36]: at 0x56195ad76ba0
```

When I check `LspLop`, I see:

[ERROR][2025-07-25 14:57:57] /usr/local/share/nvim/runtime/lua/vim/lsp/log.lua:149 "rpc" "java" "stderr" "Jul 25, 2025 2:57:57 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError\nSEVERE: Internal error: java.lang.IllegalStateException: Invalid completion proposal\njava.util.concurrent.CompletionException: java.lang.IllegalStateException: Invalid completion proposal\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)\n\tat java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:747)\n\tat java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)\n\tat java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:288)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)\n\tat org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)\n\tat org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\nCaused by: java.lang.IllegalStateException: Invalid completion proposal\n\tat org.eclipse.jdt.ls.core.internal.handlers.CompletionResolveHandler.resolve(CompletionResolveHandler.java:106)\n\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.resolveCompletionItem(JDTLanguageServer.java:646)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:128)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:271)\n\t... 10 more\n\n"

Which I believe is the same error as one of the logs that was mentioned in the description.

Another user is reporting the same error from [nvim-java](https://github.com/nvim-java/nvim-java/issues/399).

I'm using JDK 21 from SdkMan.
```
-> java --version
openjdk 21.0.1 2023-10-17 LTS
OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)
```
