### ISSUE TITLE
Maven project structure not recognized

### ISSUE THREAD

**Issue by andrwui** [mfussenegger/nvim-jdtls#702]
### LSP client configuration

local java = {
  'mfussenegger/nvim-jdtls',
  config = function()
    local jdtls = require('jdtls')

    local config = {
      cmd = { vim.fn.stdpath('data') .. '/mason/bin/jdtls' },
      root_dir = vim.fs.dirname(vim.fs.find({ 'gradlew', '.git', 'mvnw' }, { upward = true })[1]),
      settings = {
        java = {
          jdkHome = '/usr/local/jdk-8/bin',
          project = {
            sourcePaths = { "src/main/java" },
          }
        }
      },
    }

    jdtls.start_or_attach(config)
  end
}

return { java }

### Eclipse.jdt.ls version

latest, i can't find it

### Steps to Reproduce

In a project using Maven, with a file structure of classes being in src/main/java, open a file in any package

### Expected Result

The laguange server recognizes correctly the package the current class is in, and imports can be resolved

### Actual Result

The language server won't recongnize the package the current class is in, also doesn't recongizes any imports
eg:
`The declared package 'com.util' does not match the expected package 'main.java.com.util`

**Comment by alex-k03** [comment]
Did you find a solution to this?

**Comment by mfussenegger** [comment]
See troubleshooting steps in the readme.

**Comment by andrwui** [comment]
Read it multiple times. didn't solve a thing.
The only viable solution was creating a .project file importing the project in Eclipse.
Nothing else worked.
