### ISSUE TITLE
Using it with init.lua

### ISSUE THREAD

**Issue by Chaitanyabsprip** [mfussenegger/nvim-jdtls#71]
I am unable to find a way to use this with init.lua, the only way I can think of is using vim.api.nvim_exec() but that would be very far from ideal cause this autocmd basically runs a lua code chunk.

**Comment by mfussenegger** [comment]
> the only way I can think of is using vim.api.nvim_exec() but that would be very far from ideal cause this autocmd basically runs a lua code chunk.

`vim.cmd` is the way to go to define autocmds from lua until neovim gains a lua API to define them. See https://github.com/neovim/neovim/pull/12378 

This is btw. also what lspconfig would do when you use the `setup` functionality there. See https://github.com/neovim/nvim-lspconfig/blob/0840c91e25557a47ed559d2281b0b65fe33b271f/lua/lspconfig/configs.lua#L60 for an example

**Comment by Chaitanyabsprip** [comment]
works fine now, thank you!
