### ISSUE TITLE
Make nvim-tree understand jdt:// uri

### ISSUE THREAD

**Issue by jugarpeupv** [mfussenegger/nvim-jdtls#720]
### Problem Statement

Hey, first, thank you for this amazin plugin! I am not sure if this is something that the file explorer should resolve or not, but i thought on posting it here to receive some feedback, if you consider it is a problem that should be handled in the concrete file explorer, then i will create it there ^^

The problem is, when i go to the definition of a type, i move to the file, that is working, but now i want to explore the file system where this file resides

<img width="1435" alt="image" src="https://github.com/user-attachments/assets/64b9e6fb-d1ae-4811-a3f9-6610324a48ca">

If i open dirbuf i get the following error:

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/7be7166e-3590-4390-b3cb-ac9c8972b1f7">

When i toggle nvimtree it does not update the view to show me the file system

I guess they do not handle jdt:// uri right?

Do you know how it could be solved?

### Ideas or possible solutions

Standarize uri so that file explorers understand them?

**Comment by mfussenegger** [comment]
`jdt://` urls are virtual documents that don't exist on the file system and there's no real folder layout for them.

If nvim-tree fails if you have any such buffers open that would need fixing in nvim-tree. It should probably ignore anything that's not a file URI.
