### ISSUE TITLE
Lsp server sometimes takes a long time to attach to buffer

### ISSUE THREAD

**Issue by goldeneas** [mfussenegger/nvim-jdtls#726]
### LSP client configuration
```
local jdtls = require('jdtls')
local mason_path = vim.fn.stdpath('data') .. '/mason'

local jdtls_path = mason_path .. '/packages/jdtls'
local lombok_path = jdtls_path .. '/lombok.jar'

local os = "unknown-os"
if vim.fn.has("mac") == 1 then
  os = "mac"
elseif vim.fn.has("unix") == 1 then
  os = "linux"
elseif vim.fn.has("win32") == 1 then
  os = "win"
end

if not os or os == "unknown-os" then
  vim.notify("jdtls: Could not detect valid OS", vim.log.levels.ERROR)
end

local cmplsp = require("cmp_nvim_lsp")
local capabilities = cmplsp.default_capabilities()

local project_name = vim.fn.fnamemodify(vim.fn.getcwd(), ':p:h:t')
local workspace_dir = vim.fn.stdpath('data') .. '/jdtls-workspace/' .. project_name

local config = {
    cmd = {
      'java',
      '-javaagent:' .. lombok_path,
      '-Declipse.application=org.eclipse.jdt.ls.core.id1',
      '-Dosgi.bundles.defaultStartLevel=4',
      '-Declipse.product=org.eclipse.jdt.ls.core.product',
      '-Dlog.protocol=true',
      '-Dlog.level=ALL',
      '-Xmx1g',
      '--add-modules=ALL-SYSTEM',
      '--add-opens', 'java.base/java.util=ALL-UNNAMED',
      '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
      '-jar', vim.fn.glob(jdtls_path .. '/plugins/org.eclipse.equinox.launcher_*.jar'),
      '-configuration', jdtls_path .. '/config_' .. os,
      '-data', workspace_dir
    },
    root_dir = vim.fs.dirname(vim.fs.find({'gradlew', '.git', 'mvnw'}, { upward = true })[1]),
    capabilities = capabilities,
}

jdtls.start_or_attach(config)
```

### Eclipse.jdt.ls version

1.41.1

### Steps to Reproduce

- Open a .java file

### Expected Result

LSP Server attaches to the buffer every time

### Actual Result

LSP Server sometimes attaches correctly; sometimes either doesnt attach at all or takes a long time (couple of minutes) to attach even if opening the same file.

LspLog Output:
`[START][2024-12-16 15:09:38] LSP logging initiated
[ERROR][2024-12-16 15:09:38] .../vim/lsp/rpc.lua:770	"rpc"	"java"	"stderr"	"WARNING: Using incubator modules: jdk.incubator.vector\n"
[ERROR][2024-12-16 15:09:38] .../vim/lsp/rpc.lua:770	"rpc"	"java"	"stderr"	"dic 16, 2024 3:09:38 PM org.apache.aries.spifly.BaseActivator log\nINFORMAZIONI: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic\n"
[ERROR][2024-12-16 15:09:38] .../vim/lsp/rpc.lua:770	"rpc"	"java"	"stderr"	"dic 16, 2024 3:09:38 PM org.apache.aries.spifly.BaseActivator log\nINFORMAZIONI: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic\n"
`

JdtShowLogs Output:
`ThreadId: 53 ThreadName: pool-1-thread-1 ThreadState: TIMED_WAITING
  Blocked On: none
  Synchronizers Locked: 
    java.util.concurrent.ThreadPoolExecutor$Worker@62f4ff3b
  Monitors Locked: none
  Stack Trace: 
    java.base@23.0.1/java.lang.Thread.sleepNanos0(Native Method)
    java.base@23.0.1/java.lang.Thread.sleepNanos(Thread.java:496)
    java.base@23.0.1/java.lang.Thread.sleep(Thread.java:527)
    org.eclipse.jdt.ls.core.internal.JobHelpers.waitForJobs(JobHelpers.java:202)
    org.eclipse.jdt.ls.core.internal.JobHelpers.waitForInitializeJobs(JobHelpers.java:177)
    org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialized(JDTLanguageServer.java:294)
    java.base@23.0.1/java.lang.invoke.LambdaForm$DMH/0x00000fff011c2000.invokeInterface(LambdaForm$DMH)
    java.base@23.0.1/java.lang.invoke.LambdaForm$MH/0x00000fff011aa400.invoke(LambdaForm$MH)
    java.base@23.0.1/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
    java.base@23.0.1/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:154)
    java.base@23.0.1/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    java.base@23.0.1/java.lang.reflect.Method.invoke(Method.java:580)
    org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
    org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint$$Lambda/0x00000fff0133bd10.apply(Unknown Source)
    org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:160)
    org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:231)
    org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:198)
    org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)
    org.eclipse.jdt.ls.core.internal.ParentProcessWatcher$$Lambda/0x00000fff013b56b8.consume(Unknown Source)
    org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
    org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
    org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
    java.base@23.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
    java.base@23.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
    java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    java.base@23.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    java.base@23.0.1/java.lang.Thread.runWith(Thread.java:1588)
    java.base@23.0.1/java.lang.Thread.run(Thread.java:1575)
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:370)
	... 17 more
`

**Comment by andreluisos** [comment]
Not sure if it's the same issue, but often when I open a project, jdtls won't completely load the workspace, getting stuck at 20%. Removing .classpath fixes the issue.

This bug should require some attention.

```
ThreadId: 62 ThreadName: Worker-5: Initialize Workspace ThreadState: TIMED_WAITING
  Blocked On: java.util.concurrent.locks.ReentrantLock$NonfairSync@2a62cd63 LockOwnerId: 52 LockOwnerName: Worker-1: Initialize After Load
  Synchronizers Locked: none
  Monitors Locked: none
  Stack Trace: 
    java.base@21.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    java.base@21.0.5/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
    java.base@21.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:756)
    java.base@21.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireNanos(AbstractQueuedSynchronizer.java:1038)
    java.base@21.0.5/java.util.concurrent.locks.ReentrantLock$Sync.tryLockNanos(ReentrantLock.java:168)
    java.base@21.0.5/java.util.concurrent.locks.ReentrantLock.tryLock(ReentrantLock.java:479)
    org.eclipse.osgi.container.Module.lockStateChange(Module.java:328)
    org.eclipse.osgi.container.Module.start(Module.java:447)
    org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:528)
    org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:122)
    org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:620)
    org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:347)
    org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:414)
    org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
    org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:516)
    org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
    org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:193)
    java.base@21.0.5/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
    org.eclipse.jdt.ls.core.internal.managers.GradleUtils.getGradleVersion(GradleUtils.java:149)
    org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.inferGradleJavaHome(GradleProjectImporter.java:342)
    org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.importToWorkspace(GradleProjectImporter.java:236)
    org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:164)
    org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:126)
    org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:277)
    org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
    org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:370)
	... 25 more

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-27 10:40:59.520
!MESSAGE Workspace initialized in 360341ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-27 10:40:59.545
!MESSAGE >> initialization job finished

!ENTRY java-debug 1 0 2024-12-27 10:41:00.390
!MESSAGE Starting com.microsoft.java.debug.plugin

!ENTRY org.eclipse.jdt.ls.core 4 0 2024-12-27 10:41:00.394
!MESSAGE Command _java.reloadBundles.command not supported on client

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-27 10:41:00.400
!MESSAGE >> build jobs finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-27 10:41:00.401
!MESSAGE >> registerWatchers'

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-27 10:41:00.837
!MESSAGE Reconciled 1. Took 1 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-27 10:41:01.604
!MESSAGE begin problem for /BackendApplication.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-27 10:41:01.608
!MESSAGE 0 problems reported for /BackendApplication.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-12-27 10:41:01.615
!MESSAGE Validated 1. Took 128 ms

```

**Comment by mfussenegger** [comment]
This needs to be reported in eclipse.jdt.ls, doesn't appear to be a nvim-jdtls issue. You'll likely also have to be able to provide a small java project where the issue can be reproduced.
