### ISSUE TITLE
Javadoc generation

### ISSUE THREAD

**Issue by elevin72** [mfussenegger/nvim-jdtls#76]
Is there a setting that will enable javadoc generation? I recall seeing something like this in coc-java

**Comment by mfussenegger** [comment]
Could you elaborate a bit what you mean with javadoc generation?

Some code generation capabilities are exposed via snippets and you need some other companion plugin to expand them (E.g. [nvim-compe](https://github.com/hrsh7th/nvim-compe)) 

There are also a couple of settings in eclipse.jdt.ls that affect the code generation snippets or code actions. For example `java.codeGeneration.generateComments` 

You can have a look at the `package.json` (https://github.com/redhat-developer/vscode-java/blob/master/package.json#L138) for available configuration options. Most of them are server options, but a few are also vscode-java specific client options. There is unfortunately no table that's specific to the server only.

**Comment by elevin72** [comment]
Hi thanks for you response. I was referring to the eclipse feature where you can type ```/**``` before a mehtod and a templated javadoc will show up with all the correct params and return type.

**Comment by mfussenegger** [comment]
Looks like this works via a snippet, but only managed to get it working if there's the corresponding ending `**/` as well, see this short clip:


https://user-images.githubusercontent.com/38700/116917080-7973f080-ac4e-11eb-9788-e884a5094fa5.mp4

**Comment by elevin72** [comment]
Thanks!
