### ISSUE TITLE
jdt.ls-java-project does not exist

### ISSUE THREAD

**Issue by zupatisc** [mfussenegger/nvim-jdtls#78]
Not sure if this is strictly speaking something going wrong with the plugin but when opening a java file the server and :LspInfo will report that jdt.ls has started and attached to the buffer but it does nothing. As the troubleshooting section suggests I looked into the `lsp.log` and found the following.
``
 [ ERROR ] 2021-05-05T21:35:24+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:410 ]>"05.05.2021, 21:35:24 Initialization failed 
jdt.ls-java-project does not exist
Java Model Exception: Java Model Status [jdt.ls-java-project does not exist]
\tat org.eclipse.jdt.internal.core.Java    Element.newJavaModelException(JavaElement.java:583)
\tat org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:254)\n\tat org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:596)\n\tat org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.j    ava:326)\n\tat org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:312)\n\tat org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:267)\n\tat org.eclipse.jdt.internal.core.JavaProject.getPackageFragmentRoots(JavaProject.java:2322)\n\tat org.eclipse.jd    t.internal.core.JavaProject.getPackageFragments(JavaProject.java:2346)\n\tat org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.cleanupResources(ProjectsManager.java:212)\n\tat org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:101)\n\ta    t org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:194)\n\tat org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)\n\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)\n"
``
Maybe someone could help shed some light onto this

**Comment by mfussenegger** [comment]
Can you delete the workspace folder and then try again?

The workspace folder is the one you configure with `-data` in your java-lsp launch file.

**Comment by zupatisc** [comment]
Ah okay I deleted the whole folder, not just the subfolders and that also got rid of some dotfiles that seem to have caused the error, I now have linting and completion working, thanks!
The `lsp.log` still reports this error `[ ERROR ] 2021-05-06T12:44:13+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:410 ]
"06.05.2021, 12:44:13 file:///home//prog2/Az3/app/src/main/java/de/assignment3/NumberEstimator.java does not resolve to a ICompilationUnit"` But not sure if that's really noteworthy now.

**Comment by mfussenegger** [comment]
I think this error can happen if you save a file that is outside of the project root or for some reason not included in the project configuration (e.g. outside the java sourceSets path)
