### ISSUE TITLE
Error executing vim.schedule lua callback: buf.lua:372: command: expected string, got nil

### ISSUE THREAD

**Issue by Filius-Patris** [mfussenegger/nvim-jdtls#79]
I wanted to import an Interface by triggering `lua vim.lsp.buf.code_action()` and selecting the first option. Instead of the hoped autoimport i got this error:

```
Error executing vim.schedule lua callback: ...nloads/nvim-osx64/share/nvim/runtime/lua/vim/lsp/buf.lua:372: command: e
xpected string, got nil
stack traceback:
        ...nloads/nvim-osx64/share/nvim/runtime/lua/vim/lsp/buf.lua:372: in function 'execute_command'
        ...s/nvim-osx64/share/nvim/runtime/lua/vim/lsp/handlers.lua:142: in function 'handler'
        .../Downloads/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:726: in function 'cb'
```

This happens for any code action option I'm presented with.

Any clues? Willing to share any system information useful, but I'm not sure what you could use.

**Comment by mfussenegger** [comment]
You have to use `require('jdtls').code_action()` instead of `vim.lsp.buf.code_action()`

The code action implementation of jdtls is a superset of the one in neovim core, so you can even use it with other language servers

**Comment by Filius-Patris** [comment]
Works, thanks! Let's hope I won't have other custom code_action implementations for other languages, but I'll think about that when the given problem arises.

**Comment by mfussenegger** [comment]
> Let's hope I won't have other custom code_action implementations for other languages

You could setup the keymap in the `on_attach` callback (see `:help vim.lsp.start_client()`). That allows you to have different keybindings per server.

There's also a pending PR against neovim that would allow extensions like nvim-jdtls to register their custom client commands https://github.com/neovim/neovim/pull/14115 - that would make it possible to use the original `vim.lsp.buf.code_action()`

**Comment by axieax** [comment]
Hello it seems that that PR has been merged now. However, I'm not quite sure how to register nvim-jdtls to use the original vim.lsp.buf.code_action(). Does anyone have any ideas on setting this up?

**Comment by mfussenegger** [comment]
> Hello it seems that that PR has been merged now. However, I'm not quite sure how to register nvim-jdtls to use the original vim.lsp.buf.code_action(). Does anyone have any ideas on setting this up?

If you run latest neovim master you can use `vim.lsp.buf.code_action()` directly and all the code-action extensions of nvim-jdtls should just work.
