### ISSUE TITLE
Choosing a different decompiler

### ISSUE THREAD

**Issue by PatOConnor43** [mfussenegger/nvim-jdtls#8]
Hi! Thanks so much for this awesome project. I've been trying to use it to replace some of my work in intelliJ Idea. My question is if you know how to set up a different decompiler to use? I would really like to use [fernflower](https://github.com/fesh0r/fernflower) if possible.

I've been reading these two wiki entries to try to get setup:
  - https://github.com/eclipse/eclipse.jdt.ls/wiki/Contribute-an-extension-bundle
  - https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request

I've put together this config in an attempt to get this to work, but it doesn't seem to be working as expected:
```lua
nvim_lsp.jdtls.setup({
    on_attach = java_attach,
    cmd = {"java-lsp"},
    filetypes = {"java"},
    init_options = {
      bundles = {
              '/home/patrickoconnor/Downloads/dg.jdt.ls.decompiler.fernflower-0.0.2-201802221740.jar',
      },
      extendedClientCapabilities = jdtls.extendedClientCapabilities,
      settings = {
        java = {
          contentProvider = {
            preferred = 'fernflower',
          },
        },
      },
    },
    on_new_config = function(config)
      jdtls.start_or_attach(config)
    end
})

```
The bundle I'm supplying was stolen from [this vscode plugin](https://github.com/dgileadi/vscode-java-decompiler). 

I know this has very little to do with your project I was just hoping you already had this set up :)

**Comment by mfussenegger** [comment]
I think the `bundles` also needs to contain the `dg.jdt.ls.decompiler.common-0.0.2-201802221740.jar` file in addition to the fernflower. Or add all of them with something like this:

```
local bundles = {}
vim.list_extend(bundles, vim.split(vim.fn.glob(home .. "/dev/dgileadi/vscode-java-decompiler/server/*.jar"), "\n"))
```

I'd btw. recommend to not launch this extension via `nvim_lsp` but rather directly call `jdtls.start_or_attach` with the options you currently pass to `nvim_lsp.jdtls.setup`

**Comment by PatOConnor43** [comment]
Perfect! I moved the `start_or_attach` call to an autocmd for java files and included the common jar as well and the generated comment does appear to be using the fernflower decompiler. Thanks!
