### ISSUE TITLE
Support hotswapping

### ISSUE THREAD

**Issue by Filius-Patris** [mfussenegger/nvim-jdtls#80]
TBH I don't really know how this all works, but I know that I can hotswap code with jdb's `redefine` command, so it should be possible for this plugin to hotswap code into a JVM. It would be quite useful to be able use this functionality, but I don't know if it is feasable for the following reason.

### Difficulties:
 - A project is not necessarily bound to running Java code. (And especially when working on Gradle project with custom 'run' tasks, this problem is apparent)
 - Does the jdt ls even produce bytecode or does it just validate / assist?

If anyone with more insight can explain to me if this is doable with the current code structure, I'd be grateful!

**Comment by Filius-Patris** [comment]
I'm trying to implement a self-stiched solution for my use-case (Minecraft Mods, Fabric). In my context, I fire up a Gradle build with `--continuous`, another Gradle task, which launches the game (with `--debug-jvm`, so I can attach jdb) and finally a vim function, that searches the .class file corresponding to the current buffer and attaches jdb and `redefine`s the implementation.

Hacky, but it (barely) works.

**Comment by mfussenegger** [comment]
Could you try out https://github.com/mfussenegger/nvim-jdtls/pull/81 ?

It adds a `hotcodereplace` flag to `setup_dap`. So if you have an active debug session and you make changes to a class it will reload it (with some limitations, e.g. the last frame on the current stack cannot be changed).

**Comment by Filius-Patris** [comment]
Awesome!! I might need a bit of time still, until I've got dap set up, but I'll defenitely check it out...

**Comment by mfussenegger** [comment]
Merged the PR, so this should now be supported.

If you've issues setting up dap I could probably give you some more pointers if you explain the problem in more detail.

**Comment by Filius-Patris** [comment]
Ok, so my issue is, that I (a) have no idea on what exactly I should set as options when I configure dap, and (b) I get no error.

My development workflow has a java application with debug port 5005 running on my local machine. I would like to connect to this process.

## Installation of dap

I followed the steps in [this repo's readme](https://github.com/mfussenegger/nvim-jdtls#java-debug-installation), except that I ran `./mvnw clean install` with the `-DskipTests` option.

Then I set up the configs for adapter and debuggee:

```
require('dap').adapters.java = function(callback, config)
	M.execute_command({command = 'vscode.java.startDebugSession'}, function(err0, port)
		assert(not err0, vim.inspect(err0))

		callback({ type = 'server'; host = '127.0.0.1'; port = port; })
	end)
end


require('dap').configurations.java = {
	{
		type = 'java';
		request = 'connect';
		name = "Launch file";
		port = 5005;
	},
}
```
(Note that I've never written Lua once in my life)

Now when I open a Java file, the LS starts up normally and works. But when I run `:lua require'dap'.continue()`, I get no feedback whatsoever. `:messages` has nothing. The only kind of feedback I get is that `:lua require'dap'.repl.open()` has `No active debug session`. That makes it rather difficult to debug...

You can view my entire nvim configuration [here](https://git.filiuspatris.net/nvim/log/?h=dap-test) ([here](https://git.sr.ht/~filiuspatris/nvim/tree/dap-test) if the my server's down, which might happen from time to time).

**Comment by mfussenegger** [comment]
Your `adapters.java` configuration is likely wrong. The installation instructions https://github.com/mfussenegger/nvim-jdtls#debugger-via-nvim-dap don't mention that you should copy it from `dap.txt`. Instead it says this:

> You also need to call require('jdtls').setup_dap() to have it register a java adapter.

**Comment by Filius-Patris** [comment]
Aaah, ok I get it, `setup_dap()` sets up the adapter, so I don't need to configure `dap.adapters`.

I copied your suggested config (whoops, I got the request option wrong), changing `dap` to `require('dap')`.

Still the same problems, still no error, still no response on `lua require'dap'.continue()`, still no debug session in REPL.

Here's everything that touches jdtls and dap (except for the install commands) in its current form:
```
function SetupJdtLs()
lua <<EOF
require('jdtls').start_or_attach({
	cmd = {'java-lsp.sh'};
	init_options = {
		bundles = {
			vim.fn.glob("./java-debug/com.microsoft.java.debug.plugin/target/com.microsoft.java.debug.plugin-*.jar")
		};
	};
	on_attach = function(client, bufnr)
		-- With `hotcodereplace = 'auto' the debug adapter will try to apply code changes
		-- you make during a debug session immediately.
		-- Remove the option if you do not want that.
		require('jdtls').setup_dap({ hotcodereplace = 'auto' })
	end
})

require('dap').configurations.java = {
	{
		type = 'java';
		request = 'attach';
		name = "Debug (Attach) - Remote";
		hostName = "127.0.0.1";
		port = 5005;
	},
}

EOF
endfunction

augroup lsp
	au!
	au FileType java call SetupJdtLs()
augroup end
```

I'm sorry if I missed something that was in the docs 😓.

**Comment by mfussenegger** [comment]
That `org.osgi.framework.BundleException:` indicates that something with the `bundles` setup is wrong.

Did you compile both eclipse.jdt.ls and the vscode-java-debug plugin with the same java version, and ensure both are up to date?

You can also use `:lua print(vim.inspect(vim.lsp.get_active_clients()))` and look for the `bundles` output to see if the glob got resolved correctly. 

Unfortunately the language server doesn't respond if you invoke a command it cannot handle - this is why you don't get any feedback if you try to start a debug session.

**Comment by Filius-Patris** [comment]
> Did you compile both eclipse.jdt.ls and the vscode-java-debug plugin with the same java version, and ensure both are up to date?

This is the version of eclipse.jdt.ls (should be latest master):
```
eclispe.jdt.ls $ git describe
v1.1.2-2-g9741dfb8
```

This is the version of java-debug (should be latest master):
```
java-debug $ git describe
0.12.0-115-g7943067
```

Java version is not really recent, but most recent for homebrew, as far as I know:
```
$ java --version
openjdk 15.0.2 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7)
OpenJDK 64-Bit Server VM (build 15.0.2+7, mixed mode, sharing)
$ javac --version
javac 15.0.2
```

I did run `./mvnw clean install -DskipTests` for both directories again. They have both built successfully.

> You can also use `:lua print(vim.inspect(vim.lsp.get_active_clients()))` and look for the bundles output to see if the glob got resolved correctly.

When I used the relative path I got an empty object, but when I used the full path, it had this string: `/Users/tobtobxx/.config/nvim/java-debug/com.microsoft.java.debug.plugin/target/com.microsoft.java.debug.plugin-0.32.0.jar`.

--------
I'll look into updating the JDK...

**Comment by mfussenegger** [comment]
Could you try with https://github.com/mfussenegger/nvim-jdtls/pull/89 ?

**Comment by Filius-Patris** [comment]
Nope, I get an `IndexOutOfBoundsException` (in the lsp.log).

[lsp.log](https://gist.github.com/Filius-Patris/b40d8e65c5a54394dfc2a94bd990dc51)

**Comment by Filius-Patris** [comment]
UPDATE:

I had success getting it to run by replacing `config.projectName` with `""` on line 33 and 37 of dap.lua. I can't tell if (what) side effects this has, but it works for me.

Patch:
```patch
diff --git a/lua/jdtls/dap.lua b/lua/jdtls/dap.lua
index 3a820d0..5a1705b 100644
--- a/lua/jdtls/dap.lua
+++ b/lua/jdtls/dap.lua
@@ -30,11 +30,11 @@ local function enrich_dap_config(config_, on_config)
         end
       end
     end
-    with_java_executable(config.mainClass, config.projectName, function(java_exec)
+    with_java_executable(config.mainClass, "", function(java_exec)
       config.javaExec = config.javaExec or java_exec
       local params = {
         command = 'vscode.java.resolveClasspath',
-        arguments = { config.mainClass, config.projectName }
+        arguments = { config.mainClass, "" }
       }
       util.execute_command(params, function(err1, paths)
         assert(not err1, err1 and (err1.message or vim.inspect(err1)))
```

**Comment by mfussenegger** [comment]
I updated the PR and merged it to fallback to the empty string.

So this should be resolved, right?
