### ISSUE TITLE
Goto definition of a external library class causes an error and get an empty buffer

### ISSUE THREAD

**Issue by NiYanhhhhh** [mfussenegger/nvim-jdtls#86]
When I try to goto definition of a class defined in external library in my gradle project, everything works fine for the first time. Then I press <C-o> to go back to my code. However, as I goto definition of the same class, I get an error:

> Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:935: Vim(lua):E5108: Error executing lua ...niyan/.config/nvim/.vim/plugged/nvim-jdtls/lua/jdtls.lua:917: Buffer is not 'modifiable'

Then an empty buffer is presented, whose url(get by `:echo expand('%')`):

> jdt://contents/forge-1.16.5-36.1.0_mapped_snapshot_20201028-1.16.3-recomp.jar/net.minecraftforge.fml.javafmlmod/FMLJavaModLoadingContext.class?=POD/%5C/home%5C/niyan%5C/.gradle%5C/caches%5C/forge_gradle%5C/minecraft_user_repo%5C/net%5C/minecraftforge%5C/forge%5C/1.16.5-36.1.0_mapped_snapshot_20201028-1.16.3%5C/forge-1.16.5-36.1.0_mapped_snapshot_20201028-1.16.3-recomp.jar=/gradle_used_by_scope=/main,test=/%3Cnet.minecraftforge.fml.javafmlmod(FMLJavaModLoadingContext.class

After that, whenever I try to goto definition of this class, I get this error and an empty buffer.

**Comment by mfussenegger** [comment]
Could you try https://github.com/mfussenegger/nvim-jdtls/pull/87 ? I think it should solve the issue.

**Comment by NiYanhhhhh** [comment]
Yes, it works. Thanks very much!
