### ISSUE TITLE
signatureHelp always empty

### ISSUE THREAD

**Issue by jemag** [mfussenegger/nvim-jdtls#88]
Just curious if you were able to make signatureHelp work in your case?

I have it enabled in my configuration through:
``` lua
    require('jdtls').start_or_attach({
    cmd = {'java-lsp.sh', workspace_folder},
    capabilities = capabilities,
    settings = {
      java = {
        signatureHelp = { enabled = true };
        contentProvider = { preferred = 'fernflower' };
...
```
Full lsp config: https://gitlab.com/jemag/dotfiles/-/blob/master/neovim/.config/nvim/lua/plugin-configs/nvim-lspconfig.lua#L274

While I am properly asking the language server for signature help, it seems like the response is always empty, i.e.:
`"decoded"       {  id = 132,  jsonrpc = "2.0",  result = {    signatures = {}  }}`

It seems like it is possible to use since they do have an option to enable it, however not sure why it won't work once enabled.

**Comment by mfussenegger** [comment]
I think you need to add something like this:

```lua
on_init = function(client)
  if client.config.settings then
    client.notify('workspace/didChangeConfiguration', { settings = client.config.settings })
  end
end
```

To your `config` table. Otherwise eclipse.jdt.ls won't read the `settings`.
I was hoping neovim would do that by default at some point, but the PR for it wasn't merged so far. I guess it would make sense for nvim-jdtls to do it implicitly instead

**Comment by jemag** [comment]
Thanks a lot! It works now. Don't think I would have figured that one out on my own

**Comment by mfussenegger** [comment]
I [merged a change]( https://github.com/mfussenegger/nvim-jdtls/pull/92) so that the `didChangeConfiguration` notification is sent implicitly.
