### ISSUE TITLE
Add code action to generate doc comments

### ISSUE THREAD

**Issue by minhduc0711** [mfussenegger/nvim-jdtls#91]
Hi, is it possible to add a code action for generating Java doc comments like this?

![image](https://user-images.githubusercontent.com/34294427/119213736-bb74b180-baeb-11eb-8fe5-37a1ff4a62fc.png)

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-jdtls/issues/76 - it is possible via snippet. There is no dedicated code action for it as far as I'm aware.

**Comment by minhduc0711** [comment]
Ah sorry for not catching that issue. The auto-indent does not work for me for some reason though...
![image](https://user-images.githubusercontent.com/34294427/120570436-56518200-c442-11eb-8f9e-d25ec517772b.png)

**Comment by mfussenegger** [comment]
Could be that the indentation settings of the editor weren't picked up because of a missing `didChangeConfiguration`. 

Could you try again with https://github.com/mfussenegger/nvim-jdtls/pull/92 being merged?

**Comment by minhduc0711** [comment]
Hmm #92 does not seem to fix it.

**Comment by mfussenegger** [comment]
Which eclipse.jdt.ls version are you using? https://github.com/eclipse/eclipse.jdt.ls/pull/1657 is required for it to pick up indentation/tab settings.

**Comment by minhduc0711** [comment]
I'm using `jdtls-1.1.2-1`, the latest one I think.

**Comment by mfussenegger** [comment]
You could try setting the format options explicitly in your config:

```
local config = {
  settings = {
    java = {
      format = {
        insertSpaces = vim.api.nvim_buf_get_option(bufnr, 'expandtab'),
        tabSize = vim.lsp.util.get_effective_tabstop(bufnr)
      }
    }
  }
}
```

These options are automatically added by nvim-jdtls if they are absent. Not sure why it isn't working for you.

Maybe your neovim expandtab/tabstop settings don't match the indentation style of your java file?

**Comment by minhduc0711** [comment]
When I hit TAB, indentation is correct so I guess the neovim settings are fine.

The explicit config does not fix it still. Am I doing this correctly?
```lua
local config = {
  cmd = {'java-lsp', workspace_folder},
  settings = {
    java = {
      format = {
        insertSpaces = vim.api.nvim_buf_get_option(bufnr, 'expandtab'),
        tabSize = vim.lsp.util.get_effective_tabstop(bufnr)
      }
    }
  }
}
require('jdtls').start_or_attach(config)
```

**Comment by lidulibai** [comment]
Try setting the snippetSupport option after settings in your config:
```lua
local config = {
  settings = {
    java = {...}
  },
  capabilities = {
    textDocument = {
      completion = {
        completionItem = {
          snippetSupport = true
        }
      },
    },
```
