### ISSUE TITLE
jdtls doesn't attach to new buffer

### ISSUE THREAD

**Issue by c3n21** [mfussenegger/nvim-jdtls#93]
When I open an existing **.java** file inside the project, `LspInfo` shows me that jdtls is running but it's not attached; only the first file has jdtls running, i.e. if I run `nvim Test.java` only Test.java would have jdtls attached, the files I open afterwards don't.

Any suggestion about how to fix this?

**Comment by mfussenegger** [comment]
`LspInfo` is a function from lspconfig and doesn't pick up on nvim-jdtls. The output you see there is related to the `jdtls` setup within lspconfig and you shouldn't attempt to use both. 

See https://github.com/mfussenegger/nvim-jdtls#lspconfig and https://github.com/mfussenegger/nvim-jdtls#troubleshooting

**Comment by c3n21** [comment]
> `LspInfo` is a function from lspconfig and doesn't pick up on nvim-jdtls. The output you see there is related to the `jdtls` setup within lspconfig and you shouldn't attempt to use both.
> 
> See https://github.com/mfussenegger/nvim-jdtls#lspconfig and https://github.com/mfussenegger/nvim-jdtls#troubleshooting

My bad, btw I did follow the installation tutorial (even though I didn't build jdtls on my own since it gave me error), but I've installed it from here https://download.eclipse.org/jdtls/milestones/1.1.2/ and here https://download.eclipse.org/jdtls/snapshots/?d

The plugin works fine only on the first file I open, but it won't work on other files of the same NeoVim instance, so if I have runned `nvim Test.java` only `Test.java` will get autocompletion and all the features, but if I'm opening another **.java** file it just don't work; obviously the file is still in the same project.

If I run **:JdtCompile** in the quickfix list the errors in other files do show up.

`[ WARN ] 2021-06-05T15:07:51+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:108 ]      "The language server jdt.ls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"` this is the only thing I get in the log.

I don't know if it's something that involves maven or gradle, right now I just run **git init** to initialize a Java project.

And this is how I setup nvim-jdtls

`require('jdtls').start_or_attach({
    cmd = {
        'nvim-jdtls.sh',
--        vim.fn.getenv('WORKSPACE') .. vim.fn.fnamemodify(vim.fn.getcwd(),':p:h:t')
    },
    root_dir = require('jdtls.setup').find_root({'gradle.build', 'pom.xml', '.git'})
})`

**Comment by mfussenegger** [comment]
Just to be sure, you run `start_or_attach` within a `FileType` autocmd event? `start_or_attach` must be executed within each new java buffer.

**Comment by c3n21** [comment]
I think I got the error.

I've put this
`  augroup lsp
    au!
    au FileType java lua require('jdtls').start_or_attach({cmd = {'java-lsp.sh'}})
  augroup end`

in `~/.config/nvim/after/ftplugin/java.vim` and I guess that's the reason why it didn't work

Thanks for the help!

**Comment by mfussenegger** [comment]
Glad you got it working. If you've a suggestion how the README could be clarified so that it would have helped to avoid your problem, please let me know.

**Comment by c3n21** [comment]
> Glad you got it working. If you've a suggestion how the README could be clarified so that it would have helped to avoid your problem, please let me know.

You could add `https://download.eclipse.org/jdtls/milestones/1.1.2/` or `https://download.eclipse.org/jdtls/snapshots/?d` so that people like me having troubles building jdtls can at least download it right away.

Thanks you really much with your work with this plugin anyway :)
